Radarr/Radarr

src/UI/AddMovies/Existing/AddExistingSeriesCollectionViewTemplate.hbs, src/UI/AddMovies/NotFoundViewTemplate.hbs, src/UI/AddMovies/RootFolders/RootFolderCollectionView.js, src/UI/AddMovies/RootFolders/RootFolderItemView.js, src/UI/AddMovies/RootFolders/RootFolderLayout.js, src/UI/AddMovies/RootFolders/RootFolderLayoutTemplate.hbs, src/UI/Movies/Details/EpisodeNumberCell.js, src/UI/Movies/Details/InfoView.js, src/UI/Movies/Details/SeasonLayout.js, src/UI/Movies/Index/EmptyTemplate.hbs, src/UI/Movies/Index/EmptyView.js, src/UI/Movies/Index/FooterView.js, src/UI/Movies/Index/Overview/SeriesOverviewCollectionView.js
NO
Cleaning up some strings that refer to "Series" rather than "Movies". Referencing the proper templates in others.
* N/A
=> Fix template references and 'movie' strings

src/NzbDrone.Core/Organizer/FileNameBuilder.cs
NO
Improvement on the colon fix.
* https://github.com/galli-leo/Radarr/issues/20
=> Better folder name.

src/NzbDrone.Core/Download/Clients/Blackhole/UsenetBlackhole.cs, src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortex.cs, src/NzbDrone.Core/Download/Clients/Nzbget/Nzbget.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs, src/NzbDrone.Core/Download/DownloadService.cs, src/NzbDrone.Core/Download/UsenetClientBase.cs
NO
This pull request fixes all usenet download clients. All except for NZBGet & SABnzbd need testing.
* https://github.com/galli-leo/Radarr/issues/14
=> Fixes all usenet download clients.

src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotatoRequestGenerator.cs
NO
Instead of searching for imdbid (which jackett may or may not have depending on the tracker) search for a word instead.
=> Instead of searching for imdbid (which jackett may or may not have depending on the tracker) search for a word instead.

src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs, src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs
NO
To get rTorrent/ruTorrent up and running. 'Dirty' because priority isn't functional (disabled like Deluge is)
* rTorrent/ruTorrent can be used as a download client
=> dirty fix for rtorrent

src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
NO
Harden parsing of imported movie titles
*
=> Harden parsing of imported movie titles

src/NzbDrone.Common/Extensions/PathExtensions.cs, src/NzbDrone.Core/Update/InstallUpdateService.cs, src/NzbDrone.Update/UpdateApp.cs, src/NzbDrone.Update/UpdateEngine/InstallUpdateService.cs
NO
This is required in order for the auto-updater to work.
* https://github.com/galli-leo/Radarr/issues/13
=> Change Sonarr / NzbDrone auto-updater stuff to Radarr.

src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcorn.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornApi.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornInfo.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornParser.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornRequestGenerator.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornSettings.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/Parser/Model/TorrentInfo.cs
NO
Added PassThePopcorn indexer, search is working however, RSS sync looks broken for all indexers since it looks for Seasons
#17
=> Added PassThePopcorn indexer

src/NzbDrone.Core/Indexers/Omgwtfnzbs/OmgwtfnzbsRequestGenerator.cs
NO
Fix search and RSS sync for Omgwtfnzbs indexer
Omgwtfnzbs indexer functionality
*
=> update rss sync and fix search for omgwtfnzbs indexer

src/NzbDrone.Core/Notifications/Boxcar/BoxcarProxy.cs, src/NzbDrone.Core/Notifications/Growl/GrowlService.cs, src/NzbDrone.Core/Notifications/Join/JoinProxy.cs, src/NzbDrone.Core/Notifications/NotifyMyAndroid/NotifyMyAndroidProxy.cs, src/NzbDrone.Core/Notifications/Prowl/ProwlService.cs, src/NzbDrone.Core/Notifications/PushBullet/PushBulletProxy.cs, src/NzbDrone.Core/Notifications/Pushalot/PushalotProxy.cs, src/NzbDrone.Core/Notifications/Pushover/PushoverService.cs, src/NzbDrone.Core/Notifications/Telegram/TelegramService.cs
Replace Sonarr with Radarr in Test notification messages
=> Replace Sonarr with Radarr in Test notification messages

src/UI/AddMovies/SearchResultView.js, src/UI/AddMovies/SearchResultViewTemplate.hbs
NO
When adding a movie, monitored toggle doesn't apply and always defaults to being monitored
#100
=> When adding a movie, monitored toggle doesn't apply and always defaults to being monitored

src/NzbDrone.Api/Frontend/Mappers/BackupFileMapper.cs, src/NzbDrone.Core/Backup/BackupService.cs
=> Fixes #104 - Backup/update fail Access to the path "/tmp/nzbdrone_backup/config.xml" is denied

src/UI/AddMovies/SearchResultViewTemplate.hbs
=> fix #108 - Links to IMDB not working when searching for movies

src/NzbDrone.Core/Indexers/Wombles/Wombles.cs
=> Fix Wombles for movies

src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs, src/NzbDrone.Core/Download/Clients/Transmission/TransmissionSettings.cs
=> Fix transmission

src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs
=> Add category 2035 to Newznab providers for WEB-DL search support. #123

src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabRssParser.cs, src/NzbDrone.Core/Parser/Model/ReleaseInfo.cs
NO
search imdbid for usenet indexers that support it
#146
=> search imdbid for usenet indexers that support it

src/NzbDrone.Core/Indexers/Newznab/Newznab.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabCapabilities.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
=> fix some spelling mistakes and update the newznab api 'imdbid'

src/NzbDrone.Core/Notifications/Plex/PlexServerProxy.cs
=> update plex movie libraries instead of series

src/NzbDrone.Core/MetadataSource/SkyHook/Resource/TMDBResources.cs
=> Problem with Avatar (2009) #168

src/NzbDrone.Core/Datastore/Migration/115_update_movie_sorttitle.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/UI/Movies/MoviesCollection.js
=> Movies in list don't sort correctly #174

src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs
=> Add UHD to default movie categories for newsnab providers

src/NzbDrone.Core/Indexers/Newznab/Newznab.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs
=> improved categories, added Nzb-Tortuga as a preset

src/NzbDrone.Core.Test/Files/Indexers/Omgwtfnzbs/Omgwtfnzbs.xml, src/NzbDrone.Core.Test/IndexerTests/OmgwtfnzbsTests/OmgwtfnzbsFixture.cs, src/NzbDrone.Core/Indexers/Omgwtfnzbs/OmgwtfnzbsRssParser.cs
NO
Now gets info url for rss items. Indexer test are also geared towards movies
*
=> omgwtfnzbs: fixed parsing of GetInfoUrl and updated tests

src/UI/AddMovies/MonitoringTooltipTemplate.hbs, src/UI/AddMovies/SearchResultView.js
NO
Update tooltip for monitoring options when adding movie
N/A
*
=> update movie monitor tooltip

src/NzbDrone.Core/Queue/QueueService.cs
=> Queue Service should now work properly again.

src/NzbDrone.Core.Test/Download/DownloadClientTests/DelugeTests/DelugeFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/RTorrentTests/RTorrentFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/TransmissionTests/TransmissionFixtureBase.cs, src/NzbDrone.Core/Datastore/Migration/116_update_movie_sorttitle_again.cs, src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs, src/NzbDrone.Core/Download/Clients/Deluge/DelugeSettings.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxy.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs, src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs, src/NzbDrone.Core/Download/Clients/Transmission/TransmissionSettings.cs, src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs, src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentDirectoryValidator.cs, src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs, src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHD.cs, src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHDApi.cs, src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHDRequestGenerator.cs, src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHDRssParser.cs, src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHDSettings.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/UI/Movies/Index/MoviesIndexLayout.js
=> awesomeHD indexer support - Clean up Deluge, Transmission, rTorrent, QBitTorrent - Fix Sorting Titles

src/UI/Movies/Index/MoviesIndexLayout.js, src/UI/Movies/MoviesCollection.js
=> Add Filter Missing

src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotatoParser.cs, src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotatoRequestGenerator.cs, src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotatoResponse.cs, src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotatoSettings.cs
NO
Fixed user being needed & fixed age on torrentpotato
#236 
#239
=> #236 #239 - Fixed user being needed & fixed age on torrentpotato

src/NzbDrone.Core/Indexers/Torznab/Torznab.cs, src/NzbDrone.Core/Indexers/Torznab/TorznabRssParser.cs
=> Update Torznab to work with movies

src/NzbDrone.Core/Datastore/Migration/117_fix_movie_slugs.cs, src/NzbDrone.Core/MetadataSource/SkyHook/Resource/TMDBResources.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
YES
Update Slugs to be alpha-numeric only, and make sure every movie has the year appended to the titleSlug
Please try it out in the branch before accepting, I was having probs with the migration and cannot test it since I messed it up once.
#233
=> Fix movie title slugs

src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHD.cs, src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHDRequestGenerator.cs
=> Add rss sync to awesome-hd

src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs
Reference:
https://github.com/Sonarr/Sonarr/commit/68ea8a551ce83f6ff001e5adf3f07358b28ad189
=> Fixed: Parsing of SABnzbd develop version

src/NzbDrone.Core/Indexers/Newznab/Newznab.cs
=> Use DOGnzb name as the default rather than the URL

src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotatoRequestGenerator.cs
=> Torpotato username regression

src/NzbDrone.Core/Datastore/Migration/118_update_movie_slug.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
=> Fixed TitleSlug For Realz!

src/UI/Cells/MovieStatusCell.js
=> Add in theaters to 1st coumn in movie list

README.md
=> Reworked README

src/NzbDrone.Api/Series/MovieResource.cs, src/NzbDrone.Core/Datastore/Migration/119_add_youtube_trailer_id_table .cs, src/NzbDrone.Core/MetadataSource/SkyHook/Resource/TMDBResources.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/Tv/Movie.cs, src/NzbDrone.Core/Tv/RefreshMovieService.cs, src/UI/Cells/MovieLinksTemplate.hbs, src/UI/Handlebars/Helpers/Series.js, src/UI/Movies/Details/InfoViewTemplate.hbs, src/UI/Movies/Index/Overview/SeriesOverviewItemViewTemplate.hbs, src/UI/Movies/Index/Posters/SeriesPostersItemViewTemplate.hbs, src/UI/Movies/movies.less
YES 
A new link appears under the movies page and the movies overview under the IMDB one for all views.
* added YouTubeTrailerId to movie model
* db migration for new column
* added videos to append_to_response for tmdb
* increased height of .series-posters-item
* new handlebar helper to build the trailer url
* #255
=> Added trailer link to movie links (#255)

src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotatoParser.cs
=> Removed duplicate PublishDate

src/NzbDrone.Api/Series/MovieResource.cs, src/NzbDrone.Core/Datastore/Migration/120_add_studio_to_table.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/Tv/Movie.cs, src/NzbDrone.Core/Tv/RefreshMovieService.cs, src/UI/Movies/Details/InfoViewTemplate.hbs
YES 
* modified Movie model
* db migration
* ui template modification
*  #262
=> Added movie studio to movie details page (#262)

src/UI/Wanted/Missing/MissingLayout.js
NO
Change wording of "Search All Missing" prompt to replace episodes with movies
Issue # 91
=> Fix: Issue #91 - "Search All Missing" wording

src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotatoParser.cs, src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotatoResponse.cs, src/NzbDrone.Core/Indexers/Torznab/TorznabRssParser.cs
=> Fix publish date for jackett #239

src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
Couldn't refresh info for [tt2032572][USS Indianapolis: Men of Courage]: Object reference not set to an instance of an object
=> Maybe this will solve the error Object reference not set to an instance of an object

src/NzbDrone.Core.Test/Download/DownloadClientTests/NzbgetTests/NzbgetFixture.cs, src/NzbDrone.Core/Download/Clients/Nzbget/Nzbget.cs, src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetProxy.cs, src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetSettings.cs
Adds option to pause nzb option sending to NZBGET downloader.
Database Migration
NO
Description
Allows user to set option to pause NZB when sending to NZBGet.
https://github.com/Radarr/Radarr/issues/322
*
=> Nzbgetaddpaused

src/NzbDrone.Core/Jobs/TaskManager.cs
=> Turn off scene mapping task #329, update TaskManager to use 'DownloadedMovieScanCommand

src/NzbDrone.Api/NzbDrone.Api.csproj, src/NzbDrone.Api/Wanted/MissingModule.cs, src/NzbDrone.Api/Wanted/MovieMissingModule.cs, src/NzbDrone.Core/Tv/MovieRepository.cs, src/NzbDrone.Core/Tv/MovieService.cs, src/UI/Cells/MovieStatusWithTextCell.js, src/UI/Cells/cells.less, src/UI/Wanted/Missing/MissingCollection.js, src/UI/Wanted/Missing/MissingLayout.js
NO
* top buttons don't yet work
* new missing module for movies
*  find missing movies method to movie service
* new movie status cell with text
* adapted UI missing collection and layout
* helps with #31 but not is not complete
=> basic implementation of the wanted tab

src/NzbDrone.Core/Organizer/FileNameBuilder.cs, src/NzbDrone.Core/Organizer/FileNameSampleService.cs, src/UI/Settings/MediaManagement/Naming/NamingViewTemplate.hbs, src/UI/Settings/MediaManagement/Naming/Partials/ImdbIdNamingPartial.hbs
=> Add IMDb ID to file naming

src/NzbDrone.Core/Notifications/Pushover/PushoverPriority.cs
YES | NO
Correct the priority value for silent pushes. 
*
=> Fix pushover priority values.

src/NzbDrone.Core/Tv/MovieRepository.cs
=> bug fix for 15 movie wanted tab limit

src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedMovie.cs, src/NzbDrone.Core/MediaFiles/MediaFileService.cs, src/NzbDrone.Core/MediaFiles/MediaFileTableCleanupService.cs, src/NzbDrone.Core/MediaFiles/UpdateMovieFileService.cs, src/NzbDrone.Core/Tv/MovieRepository.cs, src/NzbDrone.Core/Tv/MovieService.cs
Fixes #314. Still have multiple movieFiles issue to clean up.
=> Fix issue with reimporting on movie fresh

src/UI/Navbar/Search.js
=> add year to search

src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetSettings.cs
Requires nzbget 16 or greater.
NO
*
=> Add helptext to nzbget "add paused" settings.

src/NzbDrone.Core/Organizer/FileNameBuilder.cs, src/NzbDrone.Core/Organizer/FileNameSampleService.cs, src/UI/Settings/MediaManagement/Naming/Partials/MovieTitleNamingPartial.hbs
NO
adds "Movie Title, The" filename option
* #321
=> adds 'Movie Title, The' filename option

src/NzbDrone.Core/Download/RedownloadFailedDownloadService.cs, src/NzbDrone.Core/IndexerSearch/MissingMoviesSearchCommand.cs, src/NzbDrone.Core/IndexerSearch/MoviesSearchService.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/Tv/MovieScannedHandler.cs, src/UI/Movies/Details/MoviesDetailsLayout.js, src/UI/Wanted/Missing/MissingLayout.js
NO
* switched MoviesSearchCommand to a list of id's
* adapted the MovieSearchService
* adapted UI files to use the new command
* some progress on #31
=> search selected button in wanted tab works

src/UI/Movies/Index/MoviesIndexLayout.js, src/UI/Movies/MoviesCollection.js
=> Add more filter options to movie list

src/NzbDrone.Core/Notifications/Boxcar/Boxcar.cs, src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs, src/NzbDrone.Core/Notifications/DownloadMessage.cs, src/NzbDrone.Core/Notifications/Email/Email.cs, src/NzbDrone.Core/Notifications/GrabMessage.cs, src/NzbDrone.Core/Notifications/Growl/Growl.cs, src/NzbDrone.Core/Notifications/INotification.cs, src/NzbDrone.Core/Notifications/Join/Join.cs, src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowser.cs, src/NzbDrone.Core/Notifications/NotificationBase.cs, src/NzbDrone.Core/Notifications/NotificationService.cs, src/NzbDrone.Core/Notifications/NotifyMyAndroid/NotifyMyAndroid.cs, src/NzbDrone.Core/Notifications/Plex/PlexClient.cs, src/NzbDrone.Core/Notifications/Plex/PlexHomeTheater.cs, src/NzbDrone.Core/Notifications/Plex/PlexServer.cs, src/NzbDrone.Core/Notifications/Prowl/Prowl.cs, src/NzbDrone.Core/Notifications/PushBullet/PushBullet.cs, src/NzbDrone.Core/Notifications/Pushalot/Pushalot.cs, src/NzbDrone.Core/Notifications/Pushover/Pushover.cs, src/NzbDrone.Core/Notifications/Slack/Slack.cs, src/NzbDrone.Core/Notifications/Synology/SynologyIndexer.cs, src/NzbDrone.Core/Notifications/Telegram/Telegram.cs, src/NzbDrone.Core/Notifications/Twitter/Twitter.cs, src/NzbDrone.Core/Notifications/Webhook/Webhook.cs, src/NzbDrone.Core/Notifications/Xbmc/Xbmc.cs
NO
Download and Grab notifications should work.
At least partially 
https://github.com/Radarr/Radarr/issues/200
*
=> Initial Notification Updates and Support

src/UI/Movies/MoviesCollection.js
=> update default sort order

src/NzbDrone.Core/Organizer/FileNameBuilder.cs
=> Allow renaming of movies that don't have an "Edition"

src/UI/Activity/Queue/QueueLayout.js, src/UI/Cells/MovieTitleHistoryCell.js
=> Add link to Activity -> History Tab

src/NzbDrone.Core/Extras/ExtraService.cs
=> "fixed" error message

src/NzbDrone.Api/Validation/RssSyncIntervalValidator.cs
NO
This should fix commit #428 done for increasing RSS sync threshold #292
Currently the GUI doesn't allow you to use new values, this should resolve it.
=> fix new rss-sync threshold

src/NzbDrone.Core/Notifications/Plex/PlexServer.cs, src/NzbDrone.Core/Notifications/Plex/PlexServerProxy.cs, src/NzbDrone.Core/Notifications/Plex/PlexServerService.cs, src/NzbDrone.Core/Notifications/Slack/Slack.cs
NO
Additional updates to notifications.
-- Update Slack for Movies (unable to test, I do not use slack)
-- Changes to Plex Media Server for Movie Section Update
*
=> Notification Fixes/Updates

src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHDRequestGenerator.cs, src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHDSettings.cs
=> include only internal for AHD

src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHDRequestGenerator.cs, src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHDSettings.cs
=> only use internal for RSS Sync

src/NzbDrone.Core/Notifications/Join/JoinProxy.cs
=> Fixes issue #447 (Notification Icon for Join)

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
NO
Fix release quality, parse movie not episode. 
*
=> Custom Script Fix: Parse movie not episode

src/NzbDrone.Core/Notifications/NotificationService.cs
Fix downloaded movie quality and add space between movie name and quality.
NO
Fix downloaded movie quality reporting and add space between movie title and quality. 
*
=> Download Movie Quality & Formatting

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
NO
Remove moviefile ID environment variable until further debugging can be completed, hopefully will make custom script functional. 
*
=> Remove mofilefile id for now

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs, src/NzbDrone.Core/Notifications/NotificationService.cs
NO
Should fix custom script issue on download movie notification. 
*
=> Assign moviefile object when calling download message. 

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs, src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowser.cs, src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs, src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserService.cs, src/NzbDrone.Core/Notifications/Xbmc/HttpApiProvider.cs, src/NzbDrone.Core/Notifications/Xbmc/IApiProvider.cs, src/NzbDrone.Core/Notifications/Xbmc/JsonApiProvider.cs, src/NzbDrone.Core/Notifications/Xbmc/Xbmc.cs, src/NzbDrone.Core/Notifications/Xbmc/XbmcService.cs
NO
- Add movie_path to custom script.
- Add Emby library update support for movies.
Possibly add Kodi library update support (untested)
*
=> More Notification Updates

src/NzbDrone.Core/Notifications/Xbmc/Xbmc.cs
NO
Kodi Update Fix: OldFiles -> OldMovieFiles
*
=> Kodi Update Fix: OldFiles -> OldMovieFiles

src/NzbDrone.Core/Notifications/NotificationService.cs
=> Add movie year to NotificationService

src/UI/Settings/Profile/Edit/EditProfileView.js
NO
Allows you to weigh certain words more heavily. 
ex. This, This, That = This > That
*
=> Allow Duplicate Preferred Words

src/NzbDrone.Core/Notifications/Synology/SynologyIndexer.cs
NO
Update Synology Indexer For Movies
*
=> Notifications: Update Synology Indexer 

src/NzbDrone.Core/NetImport/CouchPotato/CouchPotatoSettings.cs, src/NzbDrone.Core/NetImport/Trakt/TraktImport.cs, src/NzbDrone.Core/NetImport/Trakt/TraktListType.cs, src/NzbDrone.Core/NetImport/Trakt/TraktRequestGenerator.cs, src/NzbDrone.Core/NetImport/Trakt/TraktSettings.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
=> Added options for watched, and watchlist, and customlist to trakt

src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornRequestGenerator.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornSettings.cs
=> Use username, password and passkey for passthepopcorn

src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcorn.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornApi.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornRequestGenerator.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornSettings.cs
=> updates to ptp, and using caching for cookie

src/UI/Movies/MoviesCollection.js
=> Fix the filter modes on the movie list xD

src/UI/Movies/MoviesCollection.js
=> add importfromlist abck

src/NzbDrone.Core/Organizer/FileNameBuilder.cs
NO
Fixes up my previous PR which had episodeFile instead of movieFile
=> Use movieFile instead of episodeFile.

src/NzbDrone.Core/Organizer/FileNameBuilder.cs
NO
Add's "ES" audioProfile detection for files that report only ES
=> Add plain "ES" audioProfile.

src/UI/Settings/General/GeneralViewTemplate.hbs
=> Add warning for docker users when switching branch

src/NzbDrone.Core/NetImport/Trakt/TraktAPI.cs, src/NzbDrone.Core/NetImport/Trakt/TraktListType.cs, src/NzbDrone.Core/NetImport/Trakt/TraktParser.cs, src/NzbDrone.Core/NetImport/Trakt/TraktRequestGenerator.cs, src/NzbDrone.Core/NetImport/Trakt/TraktSettings.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
=> Added more options to trakt, popular movies, upcoming, anticipated etc..

src/UI/Settings/Profile/Edit/EditProfileViewTemplate.hbs
=> Added 'Case Insensitive.' to preferred tags info to help-inline

src/NzbDrone.Core/DecisionEngine/Specifications/CutoffSpecification.cs, src/NzbDrone.Core/DecisionEngine/Specifications/RssSync/DelaySpecification.cs
NO
- Only do the upgradable file check if there are existing files. (Fix)
- Delay profile will wait until at least 1 preferred word is contained in release. (Enhancement)
https://github.com/Radarr/Radarr/issues/410
*
=> Delay Profile: Upgradable Check Fix

src/NzbDrone.Core/DecisionEngine/Specifications/RssSync/DelaySpecification.cs
YES | NO
Fix for when preferred words is null.
*
=> Delay Profile: Fix for when preferred words is null.

src/NzbDrone.Core/MediaFiles/RenameMovieFileService.cs, src/UI/AddMovies/NotFoundViewTemplate.hbs, src/UI/Settings/Quality/Definition/QualityDefinitionItemViewTemplate.hbs
NO
Update some overlooked conversions from Sonarr to Radarr, Fixed link for "[UPDATE LINK] Why can't I find my movie?".
n/a
=> Various ui text fixes

src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
=> Use Movie Name-TmdbId for slug, update toUrlSlug

src/NzbDrone.Core/Download/Clients/Blackhole/TorrentBlackhole.cs, src/NzbDrone.Core/Download/Clients/Blackhole/UsenetBlackhole.cs, src/NzbDrone.Core/Download/Clients/Hadouken/Hadouken.cs, src/NzbDrone.Core/Download/Clients/Hadouken/HadoukenSettings.cs, src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs, src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentSettings.cs
=> Clean up download clients to use radarr as label, fix hoduken, and blackhole.

src/UI/Cells/MovieTitleHistoryCell.js
=> Fixed Movie link in history tab

src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs, src/NzbDrone.Core/Parser/ParsingService.cs
=> Fix movies not showing up in Queue when downloading

src/UI/AddMovies/List/AddFromListView.js
=> Update notif list warning when importing from a list

src/NzbDrone.Core/Datastore/Migration/129_remove_kickass_again.cs
YES
Added another migration to remove Kat
=> Correct the Kickass migration

src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
=> Wait 5 seconds before getting the next 35 movies from TMDb using X-RateLimit-Remaining

src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornParser.cs
=> Fix ordering in PTP, should prefer GP releases

src/UI/ManualImport/Cells/MovieCell.js, src/UI/ManualImport/Movie/SelectMovieLayout.js
Fixes #589
Fixes #632
NO
Just a couple UI enhancements
* #589 
* #632
=> UI Enhancements for Manual Import

src/NzbDrone.Core/MediaCover/MediaCoverService.cs, src/UI/Wanted/Missing/MissingCollection.js
=> * Make Missing/Wanted Load

src/NzbDrone.Api/NzbDrone.Api.csproj, src/NzbDrone.Api/Wanted/MovieCutoffModule.cs, src/NzbDrone.Api/Wanted/MovieMissingModule.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/Tv/MovieCutoffService.cs, src/NzbDrone.Core/Tv/MovieRepository.cs, src/UI/Wanted/Cutoff/CutoffUnmetCollection.js, src/UI/Wanted/Cutoff/CutoffUnmetLayout.js, src/UI/Wanted/Missing/MissingLayout.js
=> Wanted & Missing

src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornParser.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornRequestGenerator.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornSettings.cs
=> Add required GP flag for PTP

src/NzbDrone.Api/Movies/MovieModuleWithSignalR.cs, src/NzbDrone.Api/NzbDrone.Api.csproj, src/NzbDrone.Api/Wanted/MovieCutoffModule.cs, src/NzbDrone.Api/Wanted/MovieMissingModule.cs
=> Pass at seeing if wanted -> cutoff works on linux now

src/UI/Wanted/Cutoff/CutoffUnmetLayout.js, src/UI/Wanted/Missing/MissingLayout.js
=> Fixed Sorting In Wanted and Cutoff

src/UI/Cells/MovieLinksTemplate.hbs, src/UI/Handlebars/Helpers/Series.js, src/UI/Movies/Details/InfoViewTemplate.hbs, src/UI/Movies/Index/Overview/SeriesOverviewItemViewTemplate.hbs, src/UI/Movies/Index/Posters/SeriesPostersItemViewTemplate.hbs
NO
Sonarr has trakt links. the code in Radarr was there but it was either commented out or not updated to handle movies. NO API call is required its a simple link via tmdbid.
*
=> fix trakt links for movies (like sonarr for shows)

src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
=> Limit TMDb requests when importing via IMDBid

src/NzbDrone.Core/IndexerSearch/MoviesSearchService.cs
NO
The search all functionality on the missing tab should now work. NB: I'm very new to programming so I was mainly following what Sonarr did and converting to movies as I went. Keep that in mind if something makes no sense. :)
#525 
*
=> search all missing movie works - missing tab only

src/UI/Movies/Index/MoviesIndexLayout.js
NO
Matches the index page column headers to the sort options available in the right button options.
Partial #299  only. Do we want a sort on the first unlabelled column?
*
=> changed sort options to match UI

src/NzbDrone.Core/NetImport/RSSImport/RSSImportParser.cs
=> NetImport - Do not allow TV Series / Mini-Series (works with IMDb) #699

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs, src/NzbDrone.Core/Parser/QualityParser.cs
NO
Will match all
* Movie.Title.2016.1080p.KORSUB.WEBRip.x264.AAC2.0-RADARR
* Movie.Title.2016.1080p.KORSUB**S**.WEBRip.x264.AAC2.0-RADARR
* Movie.Title.2016.1080p.DKSUB.WEBRip.x264.AAC2.0-RADARR
* Movie.Title.2016.1080p.DKSUB**S**.WEBRip.x264.AAC2.0-RADARR
* #711
=> Fix Hardcoded .DKSubs.

src/NzbDrone.Core/NetImport/Trakt/TraktListType.cs, src/NzbDrone.Core/NetImport/Trakt/TraktParser.cs, src/NzbDrone.Core/NetImport/Trakt/TraktRequestGenerator.cs, src/NzbDrone.Core/NetImport/Trakt/TraktSettings.cs
=> Clean up Trakt a little

src/UI/Movies/Editor/MovieEditorLayout.js
Add a downloaded column to movie editor.
#700
=> Add a downloaded column to movie editor.

src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHDRequestGenerator.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornRequestGenerator.cs
=> Small consistancy updates to PTP and AwesomeHD

src/NzbDrone.Core/NetImport/TMDb/TMDbParser.cs, src/NzbDrone.Core/NetImport/TMDb/TMDbRequestGenerator.cs, src/NzbDrone.Core/NetImport/TMDb/TMDbSettings.cs
=> TMDb Filtering Options: Rating, Min Votes, Min Vote Ave, Original Language, TMDb Genre Ids (CSV).

src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs
NO
Cherry picked from sonarr. Adding this test to prevent users from entering a wrong folder when adding the client.
=> Diskstation check outputpath settings

src/NzbDrone.Core/NetImport/CouchPotato/CouchPotatoImport.cs, src/NzbDrone.Core/NetImport/RSSImport/RSSImport.cs, src/NzbDrone.Core/NetImport/StevenLu/StevenLuImport.cs, src/NzbDrone.Core/NetImport/TMDb/TMDbImport.cs, src/NzbDrone.Core/NetImport/Trakt/TraktImport.cs
=> Roll back some code on Net Import

src/NzbDrone.Core/NetImport/CouchPotato/CouchPotatoAPI.cs, src/NzbDrone.Core/NetImport/CouchPotato/CouchPotatoImport.cs, src/NzbDrone.Core/NetImport/CouchPotato/CouchPotatoParser.cs, src/NzbDrone.Core/NetImport/CouchPotato/CouchPotatoRequestGenerator.cs, src/NzbDrone.Core/NetImport/CouchPotato/CouchPotatoSettings.cs, src/NzbDrone.Core/NetImport/HttpNetImportBase.cs, src/NzbDrone.Core/NetImport/INetImport.cs, src/NzbDrone.Core/NetImport/INetImportRequestGenerator.cs, src/NzbDrone.Core/NetImport/IProcessNetImportResponse.cs, src/NzbDrone.Core/NetImport/NetImportBase.cs, src/NzbDrone.Core/NetImport/NetImportBaseSettings.cs, src/NzbDrone.Core/NetImport/NetImportSearchService.cs, src/NzbDrone.Core/NetImport/RSSImport/RSSImport.cs, src/NzbDrone.Core/NetImport/RSSImport/RSSImportParser.cs, src/NzbDrone.Core/NetImport/RSSImport/RSSImportRequestGenerator.cs, src/NzbDrone.Core/NetImport/RSSImport/RSSImportSettings.cs, src/NzbDrone.Core/NetImport/StevenLu/StevenLuAPI.cs, src/NzbDrone.Core/NetImport/StevenLu/StevenLuImport.cs, src/NzbDrone.Core/NetImport/StevenLu/StevenLuParser.cs, src/NzbDrone.Core/NetImport/StevenLu/StevenLuRequestGenerator.cs, src/NzbDrone.Core/NetImport/StevenLu/StevenLuSettings.cs, src/NzbDrone.Core/NetImport/TMDb/TMDbRequestGenerator.cs, src/NzbDrone.Core/NetImport/TMDb/TMDbSettings.cs, src/NzbDrone.Core/NetImport/Trakt/TraktAPI.cs, src/NzbDrone.Core/NetImport/Trakt/TraktImport.cs, src/NzbDrone.Core/NetImport/Trakt/TraktParser.cs, src/NzbDrone.Core/NetImport/Trakt/TraktRequestGenerator.cs
=> TMDb Lists should be working now :)

src/NzbDrone.Core/Notifications/Prowl/ProwlService.cs
NO
Change application name for PROWL notifications to Radarr
* #770
=> Set PROWL application to Radarr (#770)

src/NzbDrone.Core/Validation/Paths/MovieExistsValidator.cs
NO
Changes MovieExistsValidator error message from "This series has already been added" to "This movie has already been added"
* #723
=> Fixes error message for MovieExistsValidator to state the movie doesn't exist (#723)

src/NzbDrone.Core/Notifications/Boxcar/BoxcarProxy.cs, src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs, src/NzbDrone.Core/Notifications/Prowl/ProwlService.cs, src/NzbDrone.Core/Notifications/Pushalot/PushalotProxy.cs, src/NzbDrone.Core/Notifications/Xbmc/HttpApiProvider.cs
NO
Replace Sonarr links with Radarr
=> Update notification logos

src/NzbDrone.Core/Download/Clients/DownloadStation/DownloadStationSettings.cs, src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs
NO
Rename Sonarr to Radarr in DownloadStation client.
=> Rename Sonarr to Radarr in DownloadStation client

src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
Closes #818
NO
Add URL Encode for Newznab query strings, closes #818
* #818
=> URL Encode for newznab query strings, closes #818

src/NzbDrone.Api/Wanted/MovieMissingModule.cs, src/UI/Content/progress-bars.less, src/UI/Handlebars/Helpers/Series.js, src/UI/Movies/Details/InfoViewTemplate.hbs, src/UI/Movies/Index/FooterViewTemplate.hbs, src/UI/Movies/Index/MoviesIndexLayout.js, src/UI/Wanted/Missing/MissingLayout.js
NO
I realize you already merged this.. but I have one more small commit that I already committed to this branch... Can you just merge this branch again. Thanks!
just cleaned up the footer, added a bunch of counts and added Downlaoded/Not MOnitored to the legend.
* #
=> Cleanup min availability

src/NzbDrone.Core/Tv/MovieService.cs
=> Ignore Deleted Movies (#755)

src/NzbDrone.Core/Indexers/HDBits/HDBitsApi.cs, src/NzbDrone.Core/Indexers/HDBits/HDBitsInfo.cs, src/NzbDrone.Core/Indexers/HDBits/HDBitsParser.cs, src/NzbDrone.Core/Indexers/HDBits/HDBitsRequestGenerator.cs, src/NzbDrone.Core/Indexers/HDBits/HDBitsSettings.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
=> HDBits prefer/require internal release (#584)

src/UI/Content/theme.less, src/UI/Movies/movies.less
NO
-Increase max-width so that table view fits and an extra column of posters are added
-Increase poster item height so all tags/links fit
=> Small UI fixes

src/NzbDrone.Core/Download/Clients/Nzbget/Nzbget.cs
NO
Sometimes NZBGet fails to parse an NZB file, which results in a status "Delete:SCAN". Radarr doesn't pick that up as a failure. This fixes that.
Reference:
https://github.com/Sonarr/Sonarr/commit/0af48fb2e8054db8951d0304fb04a05c9a49ccfa
=> NZBGet delete:scan treated as failure

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs, src/NzbDrone.Core/Parser/LanguageParser.cs
=> Update parsing french movies

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs, src/NzbDrone.Core/Datastore/Migration/134_add_remux_qualities_for_the_wankers.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/Parser/QualityParser.cs, src/NzbDrone.Core/Profiles/ProfileService.cs, src/NzbDrone.Core/Qualities/Quality.cs
YES
Adds Remux1080p and Remux2160p as qualities
It's on Feathub
=> Add remux 1080p and 2160p as qualities

src/UI/Movies/Editor/MovieEditorLayout.js
NO
Just some more filters on the movieEditor page... similar to the main  MovieIndex page...
* #
=> added more filters to the movie editor

src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs, src/NzbDrone.Core/NetImport/CouchPotato/CouchPotatoImport.cs, src/NzbDrone.Core/NetImport/CouchPotato/CouchPotatoParser.cs, src/NzbDrone.Core/NetImport/CouchPotato/CouchPotatoSettings.cs, src/NzbDrone.Core/NetImport/TMDb/TMDbParser.cs
=> Fixed problem with TMDb list when Year is null, Revert using UrlPathEncode on newznab requests

src/UI/Settings/NetImport/Options/NetImportOptionsView.js
NO
it takes too long to grab the names everytime.. need to cache them.. but for now just show imdb or tmdb id.. 
https://github.com/Radarr/Radarr/issues/945
* #
=> just show imdbid or tmdbid for now in exclusions

src/NzbDrone.Core/MediaFiles/UpgradeMediaFileService.cs, src/UI/Movies/Index/MoviesIndexLayout.js, src/UI/Movies/Index/Overview/SeriesOverviewItemViewTemplate.hbs
=> Date added in Movie List & Possible Fix for Importing Movies.

src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DiskStationProxyBase.cs, src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs, src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs
NO
Latest fixes from sonarr
* #965
=> Download station fixes

src/NzbDrone.Core/MediaFiles/UpgradeMediaFileService.cs
=> Hotfix when importing movie

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
=> Possible fix for Custom script

src/UI/Movies/Editor/MovieEditorFooterView.js
NO
save across pages in movieEditor
* #
=> reset filters on save..

src/NzbDrone.Api/PagingResource.cs, src/NzbDrone.Api/REST/RestModule.cs, src/NzbDrone.Api/Series/MovieModule.cs, src/UI/ManualImport/Movie/SelectMovieLayout.js, src/UI/Mixins/AsFilteredCollection.js
NO
needed to have the FE pass the filterType, have the BE receive it.. and handle it when creating the filterExpression.
https://github.com/Radarr/Radarr/issues/962
* #
=> [Fix] filtering on Manual Import

src/UI/Wanted/Cutoff/CutoffUnmetCollection.js, src/UI/Wanted/Cutoff/CutoffUnmetLayout.js, src/UI/Wanted/Missing/MissingCollection.js, src/UI/Wanted/Missing/MissingLayout.js
=> Default Wanted and Cutoff to be 50 movies per page, added filtering options to Cutoff and a Search all

src/NzbDrone.Core/NetImport/NetImportSearchService.cs
was also causing movies to be added when they shouldnt have been...
NO
* #
=> the movie was not being printed correctly, and i believe this

src/UI/Movies/Editor/MovieEditorLayout.js, src/UI/Movies/Index/MoviesIndexLayout.js
NO
if you changed the pageSize in the Settings, it would not be reflected unless you reloaded the page in the browser. Now it will be reflected when you switch back to the Movies view or the MovieEditor without totally reloading the page...
* #
=> respect the pageSize when initializing the layout

package.json, src/NzbDrone.Api/Config/NetImportConfigResource.cs, src/NzbDrone.Core/Configuration/ConfigService.cs, src/NzbDrone.Core/Configuration/IConfigService.cs, src/NzbDrone.Core/NetImport/Trakt/TraktImport.cs, src/NzbDrone.Core/NetImport/Trakt/TraktRequestGenerator.cs, src/UI/Settings/NetImport/Options/NetImportOptionsView.js, src/UI/Settings/NetImport/Options/NetImportOptionsViewTemplate.hbs
NO
I messed up a rebase and so I had to close the old PR and open this cleaner PR with a fully up to date base against develop.
using api.couchpota.to with comments indicating required changes for when updated RadarrAPI is deployed
Trakt authentication
=> fully functional traktAuthentication

src/NzbDrone.Core/NetImport/NetImportSearchService.cs, src/NzbDrone.Core/Tv/MovieService.cs, src/UI/JsLibraries/bootstrap.tagsinput.js, src/UI/Settings/NetImport/Options/NetImportOptionsView.js, src/UI/Settings/NetImport/Options/NetImportOptionsViewTemplate.hbs
NO
now use titleSlug in exclusions
always do comparison using tmdbId
https://github.com/Radarr/Radarr/issues/995
* #
=> Exclusions fix

src/NzbDrone.Core.Test/Files/Indexers/TorrentRss/AlphaRatio.xml, src/NzbDrone.Core.Test/IndexerTests/TorrentRssIndexerTests/TorrentRssIndexerFixture.cs, src/NzbDrone.Core.Test/IndexerTests/TorrentRssIndexerTests/TorrentRssSettingsDetectorFixture.cs, src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj, src/NzbDrone.Core/Indexers/RssParser.cs, src/NzbDrone.Core/Indexers/TorrentRss/TorrentRssSettingsDetector.cs, src/NzbDrone.Core/Indexers/XmlCleaner.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Fixes issue as described in https://github.com/Sonarr/Sonarr/issues/1518.
Reference:
https://github.com/Sonarr/Sonarr/commit/9b162f2d5e78ab0234c900dd232216c6b2410d7a
=> Clean RSS feed before detecting type

src/NzbDrone.Core/NetImport/Trakt/TraktImport.cs, src/NzbDrone.Core/NetImport/Trakt/TraktRequestGenerator.cs
NO
cleanup the code in TraktRequestGenerator to use http request builder
* #
=> use http request builder (aided by onedrop)

src/NzbDrone.Core/Indexers/Newznab/Newznab.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabRssParser.cs
=> Try to add year to release titles that have no year (foreign release groups)

src/UI/Settings/NetImport/Options/NetImportOptionsView.js
=> use href instead of hostname+port

src/UI/Movies/Index/MoviesIndexLayout.js
but now the filterState is respected when returning from another page
NO
the filter was not being respectd when returning from another page. The problem was intermittent for me.... I couldnt reproduce in the debugger but could reproduce without the debugger. Eventually I came to this fix. I hope it deosnt break anythnig else --> people in discord will test and let me know.
* #
=> im not too sure why this fixes the problem

src/UI/Movies/Index/MoviesIndexLayout.js
as we dont show the pager before we have the proper filterd data.
NO
* #
=> this seems to make it more stable

src/UI/Movies/MoviesCollection.js
NO
adding new movies would not be sorted properly until a refresh. This seems to fix the issue.
* #
=> fixes sorting after adding movies

src/UI/Settings/MediaManagement/Naming/NamingViewTemplate.hbs
NO
Update the wiki link for sorting and renaming in settings under Media Management next to "Standard Movie Format"
* #
=> Update wiki link for sorting and renaming

src/NzbDrone.Api/REST/RestModule.cs, src/UI/Movies/Editor/MovieEditorLayout.js, src/UI/Movies/Index/MoviesIndexLayout.js, src/UI/Movies/MoviesCollection.js
=> fix client mode fetching.. only setPageSize when necessary

src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
Closes #818 again
NO
Closes #818 again
* #818
=> URLEncode the string for searching

src/UI/Movies/Index/MoviesIndexLayout.js
=> oops -- this was a fix from the last merge - sorry

src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs, src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabRssParser.cs, src/NzbDrone.Core/Parser/Parser.cs, src/NzbDrone.Core/Parser/ParsingService.cs, src/NzbDrone.Core/Tv/MovieRepository.cs, src/UI/Content/icons.less, src/UI/Content/navbar.less, src/UI/Navbar/NavbarLayoutTemplate.hbs
=> Correct DownloadDescisionMaker to use ImdbId, and update the ui a little.

src/NzbDrone.Core/HealthCheck/Checks/IndexerRssCheck.cs
YES | NO
No
Replace Sonarr in the message with Radarr
None
* #
=> Update error to include Radarr instead of Sonarr

src/NzbDrone.Api/Series/MovieModule.cs, src/UI/Movies/FullMovieCollection.js, src/UI/Movies/MoviesController.js
=> Loads only request movie first into full collection. Should fix things.

README.md
NO
Clean up the README.md to add a new Install section with links to Installation, Docker and Setup Guide in wiki.
Also adds Feathub and Wiki to Support list.
=> Add Installation, Docker and Setup Guide to new Install section and add Feathub and Wiki to Support

src/NzbDrone.Api/Config/DownloadClientConfigModule.cs, src/NzbDrone.Api/Config/DownloadClientConfigResource.cs, src/NzbDrone.Core.Test/Download/CompletedDownloadServiceFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/PneumaticProviderFixture.cs, src/NzbDrone.Core.Test/HealthCheck/Checks/DroneFactoryCheckFixture.cs, src/NzbDrone.Core.Test/HealthCheck/Checks/ImportMechanismCheckFixture.cs, src/NzbDrone.Core.Test/MediaFiles/DownloadedMoviesCommandServiceFixture.cs, src/NzbDrone.Core.Test/MediaFiles/DownloadedMoviesImportServiceFixture.cs, src/NzbDrone.Core.Test/Messaging/Commands/CommandEqualityComparerFixture.cs, src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj, src/NzbDrone.Core.Test/RootFolderTests/RootFolderServiceFixture.cs, src/NzbDrone.Core/Configuration/ConfigService.cs, src/NzbDrone.Core/Configuration/IConfigService.cs, src/NzbDrone.Core/DiskSpace/DiskSpaceService.cs, src/NzbDrone.Core/Download/Clients/Pneumatic/Pneumatic.cs, src/NzbDrone.Core/Download/CompletedDownloadService.cs, src/NzbDrone.Core/HealthCheck/Checks/DroneFactoryCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/ImportMechanismCheck.cs, src/NzbDrone.Core/Jobs/TaskManager.cs, src/NzbDrone.Core/MediaFiles/Commands/DownloadedMovieScanCommand.cs, src/NzbDrone.Core/MediaFiles/DownloadedMovieCommandService.cs, src/NzbDrone.Core/MediaFiles/DownloadedMovieImportService.cs, src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs, src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/RootFolders/RootFolderService.cs, src/NzbDrone.Core/Validation/Paths/DroneFactoryValidator.cs, src/UI/Settings/DownloadClient/DroneFactory/DroneFactoryViewTemplate.hbs
4 DownloadedMoviesImportServiceFixure tests fail and I'm unsure why.
YES | NO
* #
=> Ensure drone factory runs on its specificed interval

src/NzbDrone.Core/NetImport/Trakt/TraktSettings.cs
NO
use .GreaterThan(0) validation instead of .InclusiveBetween(1, 500)
* #
=> allow larger trakt lists than 500

src/NzbDrone.Api/Wanted/MovieCutoffModule.cs
=>  new filters were added, but they werent being handled via the API

src/NzbDrone.Core/Parser/Parser.cs
=> incorrect check for imdbId prefix

src/NzbDrone.Api/History/HistoryModule.cs, src/NzbDrone.Core.Test/Blacklisting/BlacklistServiceFixture.cs, src/NzbDrone.Core/Blacklisting/BlacklistService.cs, src/NzbDrone.Core/History/History.cs, src/NzbDrone.Core/History/HistoryRepository.cs, src/NzbDrone.Core/History/HistoryService.cs, src/UI/Activity/Blacklist/BlacklistCollection.js, src/UI/Activity/Blacklist/BlacklistLayout.js, src/UI/Activity/Blacklist/BlacklistModel.js, src/UI/Activity/History/HistoryCollection.js, src/UI/Cells/EventTypeCell.js, src/UI/Movies/MovieModel.js
NO
Update Blacklist to work with movies
* #736
=> Update blacklist to work with movies

src/NzbDrone.Core/Tv/MovieService.cs, src/UI/Movies/MoviesCollection.js, src/UI/Wanted/Cutoff/CutoffUnmetCollection.js, src/UI/Wanted/Missing/MissingCollection.js
=> this needs to match with the property forclient mode

src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornParser.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornRequestGenerator.cs
=> QOL changes to PTP logic

src/NzbDrone.Api/Series/MovieResource.cs, src/NzbDrone.Core/Tv/Movie.cs, src/UI/Movies/Editor/MovieEditorFooterView.js
the path needs to be updated on models that are changes
NO
https://github.com/Radarr/Radarr/issues/1091
* #
=> keep the current page the same after clicking Save

src/NzbDrone.Core/NetImport/CouchPotato/CouchPotatoSettings.cs
Fix spelling of "CouchPotato" and also reword the HelpText for CouchPotato lists so it is a little more informative.
CoouchPootato made me lol.
=> Grammar check HelpText for CouchPotato lists

src/NzbDrone.Core/NetImport/NetImportSearchService.cs
=> Small changes to list sync

src/UI/AddMovies/AddMoviesLayout.js, src/UI/AddMovies/AddMoviesView.js, src/UI/Content/navbar.less, src/UI/Controller.js, src/UI/Navbar/Search.js
NO
If the library search comes up empty, you can search for the string in the input.
* #1149
=> New movie search

src/UI/AddMovies/AddMoviesLayout.js, src/UI/AddMovies/AddMoviesView.js, src/UI/Movies/Index/MoviesIndexLayout.js, src/UI/Movies/MoviesCollection.js, src/UI/Movies/MoviesController.js, src/UI/Navbar/Search.js, src/UI/Settings/NetImport/Options/NetImportOptionsView.js
NO
Clean up jsHint console warnings
No tests needed
None that I'm aware of
=> Clean up jsHint warnings

src/UI/Cells/MovieStatusCell.js
let me know if there is a reason it was removed.
NO
* #
=> not sure why this was removed but this commit adds it back

src/NzbDrone.Core/NetImport/Trakt/TraktRequestGenerator.cs, src/NzbDrone.Core/NetImport/Trakt/TraktSettings.cs
Added Additional Parameters field similar to Indexers
NO
Added "Additional Parameters" field to Trakt RSS
Added "Additional Parameters" to Trakt API Request generator
I'm a hobbyist, but this seemed like a straightforward change. I followed the comments in the issue and after not seeing anything for a few days thought I'd take a swing at it. I followed the suggestions in the issue and made an "Additional Parameters" field similar to how Indexers work.
* #1275
=> Added "Additional Parameters Field" for Trakt RSS Feed

src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabCapabilitiesProviderFixture.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs
NO
Reference:
https://github.com/Sonarr/Sonarr/commit/e7331539f0b30a14b80f0350f74e2a1981848211
=> Newznab default capabilities erroneously cached if indexer is unavailable

src/NzbDrone.Core.Test/Download/DownloadClientTests/SabnzbdTests/SabnzbdFixture.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/Responses/SabnzbdFullStatusResponse.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdFullStatus.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdQueue.cs, src/NzbDrone.Core/Download/DownloadClientBase.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Reference:
https://github.com/Sonarr/Sonarr/commit/70f7404499d916d5c9279b96a5c3a6c3eb261601
https://github.com/Sonarr/Sonarr/commit/a1a5e29c3ec22a42819397163f5a0634b459d9d0
https://github.com/Sonarr/Sonarr/commit/56ecbf4a31e105ccf970ff6f70102b14d18d6637
=> SABnzbd 2.0 API compatibility

src/UI/Settings/Notifications/Edit/NotificationEditViewTemplate.hbs
=> Update Series reference to Movies, should fix #1399

build-appveyor.cake, build.sh, osx/Radarr, osx/Radarr.app/Contents/Info.plist, package.sh
NO
Rename Sonarr to Radarr
None
=> Rename Sonarr to Radarr

src/NzbDrone.Api/NzbDrone.Api.csproj, src/NzbDrone.Api/Series/MovieDiscoverModule.cs, src/NzbDrone.Core/MetadataSource/IDiscoverNewMovies.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/UI/AddMovies/AddMoviesLayout.js, src/UI/AddMovies/AddMoviesLayoutTemplate.hbs, src/UI/AddMovies/AddMoviesView.js, src/UI/AddMovies/AddMoviesViewTemplate.hbs, src/UI/AddMovies/DiscoverMoviesCollection.js, src/UI/AddMovies/SearchResultCollectionView.js, src/UI/AddMovies/SearchResultViewTemplate.hbs, src/UI/Content/icons.less
Also added TMDB score to search results.
=> Added discovery tab based on tmdb recommendations.

src/NzbDrone.Core/Notifications/Xbmc/XbmcJsonApiProxy.cs
=> Update Kodi icon, could/should fix #1464

src/UI/Series/series.less
NO
CSS fix for issue #1475 
Tested: Android Chrome, Windows Chrome, Windows Edge, Windows Firefox.
Have not tested: OSX, iOS, Safari, Opera
Issue #1475 
* #
=> Fixed design issue when deleting - css bug

src/NzbDrone.Core/HealthCheck/Checks/IndexerSearchCheck.cs
YES | **NO**
Correct Program Name
=> Correct Program Name

src/UI/Calendar/calendar.less, src/UI/Content/fullcalendar.css
NO
Fixes two contrast css bugs in the list calendar view
Ensures the text hover color contrasts with the hover background color. 
Updates the Announced category text color to white 
* #983
=> Fixed design calendar css bug

src/NzbDrone.Core/Notifications/NotificationService.cs
NO
A few people (including myself) liked the IMDB link in the download notification, so I've added it.
NA
NA
=> Add IMDB URL to notifications

build-appveyor.cake
=> Chmod osx file as executable.

README.md, src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotato.cs, src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotatoSettings.cs, src/NzbDrone.Core/Indexers/Torznab/Torznab.cs
NO
Encourage users to use Torznab with Jackett. Torznab is better designed and contains more information to return better results. 
eg.  https://github.com/Jackett/Jackett/issues/1404
* #
=> Encourage Torznab use with Jackett

src/NzbDrone.Core/Notifications/Twitter/Twitter.cs
NO
Just a simple addition to Twitter notifications to identify the source of the tweet as coming from Radarr.
* # None - just a simple enhancement.
=> Added [Radarr] tag for Twitter Notifications

src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
Useful for e.g. french profile. When movie is named in original language, but actually has french tag.
=> Search 5 alternative titles as well

gulp/less.js, package.json
NO
Use a better CSS compressor. clean-css performs well https://goalsmashers.github.io/css-minification-benchmark/
https://github.com/Sonarr/Sonarr/commit/312136a57c78a750ffdf404d3733fe7e784bc072
=> Use clean-css for minification

src/UI/Settings/Notifications/Edit/NotificationEditView.js
NO
Fixed Twitter oAuth callback URL
https://github.com/Sonarr/Sonarr/commit/d7cb5090fcab0206d5214ff47bed145433c16784
=> Twitter oAuth callback URL

src/NzbDrone.Host/Bootstrap.cs, src/NzbDrone.Host/SingleInstancePolicy.cs
Apply https://github.com/Sonarr/Sonarr/commit/23552c326706f7fb4d7e2a08e7f27514f69a3388
Additionally rename some Sonarr mentions to Radarr in SingleInstancePolicy.cs log messages
NO
Migrate changes from Sonarr upstream
* #1765
=> Relax SingleInstancePolicy when using a custom data directory

test.ps1
NO
Makes it possible to easily run tests on windows.
=> Run tests through powershell.

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs, src/NzbDrone.Core/Parser/IsoLanguages.cs, src/NzbDrone.Core/Parser/Language.cs, src/NzbDrone.Core/Parser/LanguageParser.cs
NO
Followed the Hungarian language, added a test
Added TestCase for Hebrew language parsing
* #1904
=> Added hebrew language

package.json, src/UI/.jshintrc, src/UI/AddMovies/AddMoviesView.js, src/UI/Cells/IndexerFlagsCell.js, src/UI/Movies/Edit/EditMovieView.js, src/UI/Settings/NetImport/Edit/NetImportEditView.js
NO
Fix various jshint warnings displayed when running `npm start` (gulp). Also correctly displays Radarr as the app name in the output.
=> Fix gulp jshint warnings

src/UI/System/Info/MoreInfo/MoreInfoViewTemplate.hbs
NO
* References to "Github" replaced with the correct "GitHub"
* Fixed unclosed `<dd>` tags
* Change label of "home page" to "Homepage"
* Used a `{{!-- --}}` comment on a Sonarr reference instead of HTML comment so it won't appear in the actual code
* Fix indents
=> Fix minor issues on MoreInfoViewTemplate.hbs

src/UI/Movies/Titles/SourceCell.js, src/UI/Release/ForceDownloadView.js, src/UI/Release/ReleaseModel.js
NO
Some additional jslint warnings fixes for npm gulp watch process
=> Fix additional jshint warnings for gulp

src/UI/Settings/MediaManagement/FileManagement/FileManagementViewTemplate.hbs, src/UI/Settings/MediaManagement/Naming/Basic/BasicNamingViewTemplate.hbs
NO
Adjust a couple of `<select>` sizes for larger viewports on the Media Management section.
* Increase "Change File Date" `<select>` size to fit current options
* Decrease size of "Separator" option, as its rather wide for the options it holds.
=> Adjust column sizes relative to size of dropdown values

src/NzbDrone.Core/Notifications/Slack/Payloads/SlackPayload.cs, src/NzbDrone.Core/Notifications/Slack/Slack.cs, src/NzbDrone.Core/Notifications/Slack/SlackProxy.cs, src/NzbDrone.Core/Notifications/Slack/SlackSettings.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
NO
So looks like Sonarr implemented some improvements for Slack/Mattermost notifications in July. 
https://github.com/Sonarr/Sonarr/commit/e10717f6bb866baf545cc7071f34e276d4218321
I've ported these over to Radarr, however, I don't use Slack/Mattermost for notifications, therefore I'd want the original author of the linked issue to test/confirm if this fixes the issue or if further work is needed i.e. regressions.
Alternatively, I'll be willing to setup a test Slack channel or Mattermost server in a VM if no response from OP is forthcoming.
I will ping the original author in the issue
* #1769
=> [wip] Slack/Mattermost notifications improvements from Sonarr

package-lock.json
NO
Newer versions of npm (v5.0.0) generate a `package-lock.json` in addition to the main `package.json`.
https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md
=> Add package-lock.json for npm 5

README.md
=> Update docker nightly image reference

README.md
=> Update appveyor builds url to exclude pull requests

README.md
=> Indicate proper release types for docker image

src/NzbDrone.Common/Disk/DiskProviderBase.cs, src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs, src/NzbDrone.Common/Http/HttpProvider.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/UTorrentTests/UTorrentFixture.cs, src/NzbDrone.Core/Download/Clients/DownloadStation/DownloadStationSettings.cs, src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs, src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs, src/NzbDrone.Core/Notifications/Growl/GrowlService.cs, src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserService.cs, src/NzbDrone.Core/Rest/RestClientFactory.cs, src/NzbDrone.Core/Validation/RuleBuilderExtensions.cs, src/NzbDrone.Integration.Test/HttpLogFixture.cs
NO
Picks off a chunk of references for logger from "Sonarr" "Radarr"
Not sure, if changing the UA will cause any breakage from an API perspective?
=> Adjust Sonarr references to Radarr

src/UI/index.html
NO
JavaScript should be loaded before the `</body>` tag.
=> UI index.html template fix scripts being loaded after </body> tag

src/UI/Wanted/Cutoff/CutoffUnmetLayout.js
NO
Add a space after a question mark
* #
=> Add space in confirmation message

src/UI/AddMovies/Existing/AddExistingMovieCollectionViewTemplate.hbs
NO
I don't think the search results are coming from the TheTVDB!
=> Change message correct provider of search results

src/UI/AddMovies/BulkImport/BulkImportViewTemplate.hbs
NO
Fixes the unclosed span. Maybe causing some minor layout issues somewhere.
=> Fix unclosed <span> tag on BulkImportViewTemplate.hbs

src/NzbDrone.Core/Indexers/HDBits/HDBitsSettings.cs
According to LSL1337 on Discord there's a new codec option HEVC with ID=5
=> Add new codec HEVC with ID=5 for HDBits

src/NzbDrone.Api/Calendar/CalendarFeedModule.cs
NO
When adding the additional properties I over complicated the original code declaring the Ical.net library.
=> Simplify ical ProductId code since adding properties

src/UI/Movies/MoviesCollection.js
NO
Fix minor jshint warnings since: https://github.com/Radarr/Radarr/commit/e77d9ce84823f30fc03531df74430c9db46a35a5
=> Fix jshint warnings in MoviesCollection.js

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
NO
Add IsUpgrade and related deleted file paths for CustomScript
* #
=> Add IsUpgrade and related deleted file paths for CustomScript

src/NzbDrone.Core.Test/Download/DownloadClientTests/NzbgetTests/NzbgetFixture.cs, src/NzbDrone.Core/Download/Clients/Nzbget/Nzbget.cs, src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetProxy.cs, src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetResponse.cs, src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetSettings.cs
NO
Marked as TODO, a while ago. Here's the update for Nzbget, also updated some inconsistent references when using the name in help blocks, log entries etc.
=> Nzbget Rename TvCategory references to MovieCategory

src/NzbDrone.Core.Test/Download/DownloadClientTests/SabnzbdTests/SabnzbdFixture.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdSettings.cs
NO
* Similar to the rename work on Nzbget, but also updated the test cases to be specific to Sabnzbd. Purely cosmetic, but thought it should be different.
* Also updates references of `Sabnzbd` to `SABnzbd`
=> Sabnzbd Update test cases and rename to MovieCategory

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
NO
Add Movie_Quality to onGrab for CustomScript Notification
* #1833
=> Add Movie_Quality to onGrab

.gitignore, src/NzbDrone.Api/NancyBootstrapper.cs, src/NzbDrone.Host/ApplicationServer.cs
YES | **NO**
Cherry-picked https://github.com/Sonarr/Sonarr/commit/f53cad822ad54614c0062926262e6474cae25d57.
* #2218
=> Fixes #2218.

src/NzbDrone.Core/Notifications/Webhook/Webhook.cs, src/NzbDrone.Core/Notifications/Webhook/WebhookMovie.cs
Added the path to the movie webhook. The framework for this was already in place from the Sonarr fork. The test for this variable was already included in the test, probably since the fork as well.
=> Added FolderPath to the Movie Webhook

src/NzbDrone.Api/Series/MovieFileResource.cs
NO
Add sceneName to movieFile API output for Sub-Zero
* #2245
=> add sceneName to MovieFile API output

.gitignore, src/NzbDrone.Api/NancyBootstrapper.cs, src/NzbDrone.Console/ConsoleApp.cs, src/NzbDrone.Host/ApplicationServer.cs, src/NzbDrone.Host/Bootstrap.cs
YES | **NO**
Ongoing PR to resolve #2218.
* #2218
=> Attempt to fix #2218

src/UI/Calendar/CalendarView.js, src/UI/Calendar/UpcomingItemView.js, src/UI/Cells/RelativeDateCell.js, src/UI/Commands/CommandController.js, src/UI/Movies/Details/SeasonLayout.js, src/UI/Series/Details/SeasonLayout.js, src/UI/Shared/FormatHelpers.js, src/UI/System/Logs/Table/LogTimeCell.js
NO
fixed moment.js deprecated zone and add functions.
Had a lot of issues with the last one so made a fresh start and it is fully tested and working now.
* https://github.com/Radarr/Radarr/pull/2232
* https://github.com/Radarr/Radarr/issues/2231
=> fixed moment.js deprecated zone and add functions

src/NzbDrone.Mono/Disk/DiskProvider.cs
NO
fix build problem on windows
* #
=> fix build problem on windows

src/UI/Movies/Editor/MovieEditorLayout.js
NO
add selectAll and unselectAll buttons to the movie Editor
* #
=> selectAll and deselectAll MovieEditor buttons

src/NzbDrone.Update.Test/StartNzbDroneService.cs
NO
Fixes failing unit test in NzbDrone.Update.Test
* #
=> Fixed: StartNzbDroneService.cs unit test

src/UI/Navbar/Search.js
NO
The code to generate the empty template for typeahead search results was concatenating the unsanitized query into the template HTML, making it possible to add malicious JavaScript code.
* #2503
=> Fixed: XSS vulnerability in the navbar search.

src/NzbDrone.Host/AccessControl/FirewallAdapter.cs
=> Update NzbDrone references in FirewallAdapter.cs

src/NzbDrone.Api/System/Backup/BackupModule.cs, src/NzbDrone.Core/Backup/Backup.cs, src/NzbDrone.Core/Backup/BackupCommand.cs, src/NzbDrone.Core/Backup/BackupService.cs, src/NzbDrone.Core/Backup/MakeDatabaseBackup.cs, src/NzbDrone.Core/Datastore/Database.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Pulls Backup Improvements from Sonarr
#2440
=> Backup improvements from Sonarr

src/UI/Handlebars/Helpers/Series.js
=> Add quotes around alternative titles

src/UI/Content/form.less
NO
Center help icon for inputs
Fixes #2528
* #
=> Fixed: Help icon not centered

src/NzbDrone.Core/Notifications/Join/JoinProxy.cs, src/NzbDrone.Core/Notifications/Join/JoinSettings.cs
NO
Add Device names to join notifications. Mark DeviceID as depreciated. 
Closes #2406
* #
=> New: Device names for Join notifications

src/NzbDrone.Common/Processes/ProcessProvider.cs, src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
NO
Should fix #1460, prevent environmental variable set failure if IMDB is null. 
fixes #1460
* #
=> Fixed: Unable to execute custom scripts if IMDB ID is null

osx/Radarr.app/Contents/Info.plist
not sure if this makes any real difference, but figure it couldnt hurt to fix
=> osx app has bundle name of Sonarr

src/UI/Movies/Editor/Delete/DeleteSelectedTemplate.hbs
=> Wrap div in form-group. Fixes #2537

src/NzbDrone.Common/Http/HttpUri.cs
=> Add underscore to host part of URI regex

src/NzbDrone.Api/Config/IndexerConfigModule.cs, src/NzbDrone.Api/Config/IndexerConfigResource.cs, src/NzbDrone.Core.Test/DecisionEngineTests/MaximumSizeSpecificationFixture.cs, src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj, src/NzbDrone.Core/Configuration/ConfigService.cs, src/NzbDrone.Core/Configuration/IConfigService.cs, src/NzbDrone.Core/DecisionEngine/Specifications/MaximumSizeSpecification.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/UI/Settings/Indexers/Options/IndexerOptionsViewTemplate.hbs
NO
https://github.com/Sonarr/Sonarr/commit/d25e5fe3298e21f811edc2bacf5869807138fa3c
Closes #2652 
* #
=> New: Setting for absolute maximum size for a release

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxy.cs
NO
Ensure form parameter for `category` is added before we process the request. 
https://github.com/Sonarr/Sonarr/commit/700751715b889c13181deb878466c83c857a5fa6
=> Fixed: Add form param before submitting request

src/NzbDrone.Core.Test/Download/DownloadClientTests/NzbVortexTests/NzbVortexFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/NzbgetTests/NzbgetFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/SabnzbdTests/SabnzbdFixture.cs, src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs, src/NzbDrone.Core/Download/Clients/Deluge/DelugeSettings.cs, src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortex.cs, src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexSettings.cs, src/NzbDrone.Core/Download/Clients/Nzbget/Nzbget.cs, src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetSettings.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentPreferences.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdSettings.cs, src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs, src/NzbDrone.Core/Download/Clients/Transmission/TransmissionSettings.cs, src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs, src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs, src/NzbDrone.Core/Download/Clients/uTorrent/UTorrent.cs, src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentSettings.cs, src/NzbDrone.Core/Movies/Movie.cs, src/NzbDrone.Core/Parser/Model/RemoteMovie.cs, src/UI/Form/CheckboxTemplate.hbs, src/UI/Form/SelectTemplate.hbs
NO
Re-enable Download Client Priorities
Fixes #229
=> Added: Enable Download Client Priorities

src/NzbDrone.Core/Indexers/Omgwtfnzbs/OmgwtfnzbsRequestGenerator.cs
NO
Add new movie categories UHD (31) and Full BR (35) to the RequestGenerator. Category Other (18) mostly contains movies with foreign language, not sure if that is desired.
Fixes #2724
=> Fixed: Omgwtfnzbs api categories search need to be fix

src/NzbDrone.Core/Movies/AlternativeTitles/AlternativeTitleRepository.cs, src/NzbDrone.Core/Movies/AlternativeTitles/AlternativeTitleService.cs
NO
- Removes alt titles on movie delete
- Fixes `GetAllTitlesForMovie` function (wasn't being used for anything else so this really didn't fix anything)
Fixes #2542
=> New: Purge alt titles on movie delete

src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentTorrent.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
NO
https://github.com/Sonarr/Sonarr/commit/03997e2a0d3c1418ed4723d839385e5a3fbf000f
https://github.com/Sonarr/Sonarr/commit/55d01f620acb26b05533afdde4635ba8a49097da
Fixes #2785
=> Fixed: Qbittorrent state and eta fixes

src/NzbDrone.Core/Datastore/Migration/148_remove_extra_naming_config.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/Organizer/NamingConfigService.cs
NO
https://github.com/Sonarr/Sonarr/commit/0553a39a02fd78a2926ef1d0e2acf9fc3f9bf25f
Fixes #2773
=> Fixed: Rare timing issue on first-use causing duplicate naming config

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
Added indexer flags to the list of environmental variable for customs scripts (on grab). #1282
YES | NO
#1282
* #
=> New: Added indexer flags to the list of environmental variables

src/UI/Movies/Editor/MovieEditorLayout.js, src/UI/Movies/Index/MoviesIndexLayout.js, src/UI/Movies/MoviesCollection.js
NO
Adds a filter option for un-monitored as requested on feathub.
https://feathub.com/Radarr/Radarr/+40
* #
=> Added: Adds unmonitored filter option in index and editor

src/UI/Content/theme.less
NO
Fixes the movie list view in table view to not use two lines because of "links"
=> Fixed: multiline in table view

src/NzbDrone.Core/DecisionEngine/Specifications/QualityAllowedByProfileSpecification.cs
=> Fixed: Debug log Series reference in QualityAllowedByProfile spec

src/NzbDrone.Core/Extras/Subtitles/SubtitleFileExtensions.cs
NO
https://github.com/Sonarr/Sonarr/commit/e407145d10c7e280edd8a2f4492647c2306a8660
* #
=> Fixed: .vtt files treated as subtitles

src/UI/AddMovies/SearchResultViewTemplate.hbs, src/UI/AddMovies/addMovies.less
NO
Small fixes to class names on the 'add movies screen', one was making the poster much larger, the other was just to fix class naming consistency.
=> Fixed class names on the 'add movies screen'

src/NzbDrone.Core/Parser/ParsingService.cs
=> Allow directory to be parsed similar to past implementation

src/UI/AddMovies/BulkImport/QualityCellTemplate.hbs
NO
Fixes quality badge not being shown on bulk movie import.
* Fixes #3106.
=> Fixes quality badge not being shown on bulk movie import

src/UI/Settings/NetImport/Edit/NetImportEditView.js
NO
Should fix quirky behavior with root folder path option within lists.
* Fixes #3036 (supposedly).
=> Improve model and UI handling for lists

src/NzbDrone.Common/Cloud/RadarrCloudRequestBuilder.cs, src/NzbDrone.Common/NzbDrone.Common.csproj, src/NzbDrone.Core.Test/Framework/CoreTest.cs, src/NzbDrone.Core/HealthCheck/Checks/ProxyCheck.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/MetadataSource/TmdbConfigurationService.cs, src/NzbDrone.Core/NetImport/RSSImport/RSSImport.cs, src/NzbDrone.Core/NetImport/RSSImport/RSSImportSettings.cs, src/NzbDrone.Core/Notifications/NotificationService.cs, src/NzbDrone.Core/Update/UpdatePackageProvider.cs, src/UI/Handlebars/Helpers/Movie.js
NO
Changes service URL and various link URLs to `https`
Fixes #3186 
* #
=> New: Secure URLs for Links and Services

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
Also added a warning message upon hitting new unknown states so that they can be handled properly at some point
NO
* none
=> Added support for forcedUP status

src/NzbDrone.Core/HealthCheck/Checks/PTPOldSettingsCheck.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornRequestGenerator.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornSettings.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Allow users to use APIKey & APIUser. Also deprecated other methods of authenticating.
* #646
=> New: Use APIKey & APIUser for authenticating to PassThePopcorn.

README.md
NO
Updates the link from hotio/suitarr to hotio/radarr
=> Update docker link in README

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
=> Fixed: Prevent NullRef in CustomScript on Grab for Indexer

src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowser.cs, src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs, src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserService.cs
Description
Update emby api call for library update
Issues Fixed or Closed by this PR
#3158
=> Fix emby library update

src/NzbDrone.Core/Indexers/XmlCleaner.cs
NO
Pull from https://github.com/Sonarr/Sonarr/commit/ff994d594a815f284102a3bdae128b822f600ffe
Maybe some effect on #2355 ?
* #
=> Fixed: Error in unicode cleanup code removing most non-latin chars

src/NzbDrone.Common/Http/HttpUri.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/NzbgetTests/NzbgetFixture.cs, src/NzbDrone.Core.Test/Download/NzbValidationServiceFixture.cs, src/NzbDrone.Core.Test/Files/Nzbs/NoFiles.nzb, src/NzbDrone.Core.Test/Files/Nzbs/NotNzb.nzb, src/NzbDrone.Core.Test/Files/Nzbs/ValidNzb.nzb, src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj, src/NzbDrone.Core/Download/Clients/Blackhole/UsenetBlackhole.cs, src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs, src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortex.cs, src/NzbDrone.Core/Download/Clients/Nzbget/Nzbget.cs, src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetProxy.cs, src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetSettings.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdSettings.cs, src/NzbDrone.Core/Download/InvalidNzbException.cs, src/NzbDrone.Core/Download/NzbValidationService.cs, src/NzbDrone.Core/Download/UsenetClientBase.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
NO
- Adds nzb file validation before download
- Adds URLBase setting to NZBGet and SAB
Fixes #3146 
Fixes #3109 
* #
=> New: Nzb Validation and Nzbget/SAB URLBase

src/UI/Settings/Quality/Definition/QualityDefinitionItemView.js, src/UI/Settings/Quality/Definition/QualityDefinitionItemViewTemplate.hbs
NO
Changes the max up to 400. We can go higher, but it starts making the bottom end difficult to adjust. Tops out at around 55gb for 140min movie
Fixes #1797
=> Changed: Adjust Max Slider Value for Qualities

src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
NO
Adds `uniqueids` tags to Kodi Metadata
Fixes #3001 
* #
=> New: Support Krypton Kodi Unique Ids

src/NzbDrone.Core.Test/IndexerTests/IPTorrentsTests/IPTorrentsFixture.cs, src/NzbDrone.Core/Indexers/IPTorrents/IPTorrentsSettings.cs
NO
Cherry-pick from Lidarr
Fixes #3279
=> Fixed: Support new feed url format IPTorrents

src/NzbDrone.Core/Download/Clients/Deluge/DelugeProxy.cs
NO
Fix Deluge v2 Authentication based on https://github.com/Sonarr/Sonarr/commit/e52fcf843c092441f6d79128d744a2183d7871fa
* #3562
=> Authentication fix for Deluge v2

.circleci/config.yml, src/NzbDrone.Api/Wanted/MovieCutoffModule.cs, src/NzbDrone.Api/Wanted/MovieMissingModule.cs, src/NzbDrone.Common.Test/Http/HttpClientFixture.cs, src/NzbDrone.Integration.Test/ApiTests/CommandFixture.cs, src/NzbDrone.Integration.Test/ApiTests/WantedTests/CutoffUnmetFixture.cs, src/NzbDrone.Integration.Test/ApiTests/WantedTests/MissingFixture.cs, src/NzbDrone.Integration.Test/IntegrationTestBase.cs, src/NzbDrone.Integration.Test/NzbDrone.Integration.Test.csproj
NO
Fixed all integration tests so that they now run correctly. Also added them to the CircleCI build. Additionally, fixed some code that was wrong, specifically in the wanted modules.
* #
=> Fixed: All integration tests and some code which was wrong.

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs, src/NzbDrone.Core/Parser/IsoLanguages.cs, src/NzbDrone.Core/Parser/Language.cs, src/NzbDrone.Core/Parser/LanguageParser.cs
=> Add support for Ukrainian language.

package-lock.json, package.json
NO
Regenerate package-lock.json for secondary package updates
=> Changed: Regenerate package-lock.json for secondary package updates

src/UI/Settings/CustomFormats/CustomFormatsLayoutTemplate.hbs
NO
Fixed link to the custom-format examples
=> Fixed: link to the custom format examples

src/UI/jQuery/RouteBinder.js
NO
This adds support to open links in new tabs for all the operating systems.
* #3830
=> Fixed: open links in new tab on meta click

frontend/src/Settings/Notifications/Notifications/EditNotificationModalContent.js, frontend/src/Settings/Notifications/Notifications/Notification.js, src/NzbDrone.Core.Test/NotificationTests/NotificationBaseFixture.cs, src/NzbDrone.Core/Datastore/Migration/160_health_issue_notification.cs, src/NzbDrone.Core/Datastore/TableMapping.cs, src/NzbDrone.Core/HealthCheck/HealthCheckFailedEvent.cs, src/NzbDrone.Core/HealthCheck/HealthCheckService.cs, src/NzbDrone.Core/Notifications/Boxcar/Boxcar.cs, src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs, src/NzbDrone.Core/Notifications/Discord/Discord.cs, src/NzbDrone.Core/Notifications/Email/Email.cs, src/NzbDrone.Core/Notifications/Gotify/Gotify.cs, src/NzbDrone.Core/Notifications/INotification.cs, src/NzbDrone.Core/Notifications/Join/Join.cs, src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowser.cs, src/NzbDrone.Core/Notifications/NotificationBase.cs, src/NzbDrone.Core/Notifications/NotificationDefinition.cs, src/NzbDrone.Core/Notifications/NotificationFactory.cs, src/NzbDrone.Core/Notifications/NotificationService.cs, src/NzbDrone.Core/Notifications/PushBullet/PushBullet.cs, src/NzbDrone.Core/Notifications/Pushover/Pushover.cs, src/NzbDrone.Core/Notifications/Slack/Slack.cs, src/NzbDrone.Core/Notifications/Telegram/Telegram.cs, src/NzbDrone.Core/Notifications/Twitter/Twitter.cs, src/NzbDrone.Core/Notifications/Xbmc/Xbmc.cs, src/Radarr.Api.V2/Notifications/NotificationResource.cs
YES
Copied from https://github.com/Sonarr/Sonarr/commit/f2efebf7d94cf707e0594dabcbb5a6394e32622c#diff-679385d99ccb91f84501a19825481613
=> New: Option to send notification when a Health Check warning occurs

src/NzbDrone.Core/Movies/RefreshMovieService.cs
=> Fixed: TVDB references in RefreshMovieService.cs

frontend/src/Movie/MovieStatus.js, frontend/src/Movie/MovieStatusConnector.js, frontend/src/Store/Actions/movieActions.js
This makes aphrodite consistent with older radarr
NO
it was checking release status based on inCinemas date.. which is incorrect.
the code to handle this is already leftover from old radarr
This change properly uses isAvailable which makes the behavior consistent with old radarr
* #
=> use isAvailable to determine if a movie isAvailable.

frontend/src/Movie/Index/MovieIndexFooterConnector.js, frontend/src/Movie/MovieStatus.js
changed color of downloaded but unmonitored to match legend and old radarr UI
NO
2 minor UI changes
(1) hasFile needed to be added to the MovieIndexFooterConnector since the Movie File count was always 0.
(2) change the colour in the movieIndex for downloaded movies that are not monitored to match the legend (and more consistent with old radarr UI)
* #
=>  needed to add hasFile in the FooterConnector otherwise getting 0

src/UI/Settings/CustomFormats/Edit/CustomFormatEditViewTemplate.hbs
NO
Added links to wiki and examples from add/edit custom tags dialog
=> New: Added links to wiki and examples from add/edit custom tags dialog

frontend/src/Settings/NetImport/NetImport/EditNetImportModalContent.js, src/Radarr.Api.V2/NetImport/NetImportResource.cs
NO
minimumavailability specification for items added via netimport lists
this was in develop but didn't get ported over to aphrodite. 
* #
=> FIXED: minimumAvailability spec for lists missing(was in develop)

frontend/gulp/webpack.js
NO
Inline the worker until we come up with a better solution
* #
=> Fixed: UI Search

azure-pipelines.yml, src/NzbDrone.Api.Test/Radarr.Api.Test.csproj, src/NzbDrone.Common.Test/Radarr.Common.Test.csproj, src/NzbDrone.Core.Test/Radarr.Core.Test.csproj, src/NzbDrone.Host.Test/Radarr.Host.Test.csproj, src/NzbDrone.Libraries.Test/Radarr.Libraries.Test.csproj, src/NzbDrone.Mono.Test/Radarr.Mono.Test.csproj, src/NzbDrone.Update.Test/Radarr.Update.Test.csproj, src/NzbDrone.Windows.Test/Radarr.Windows.Test.csproj, src/coverlet.runsettings, test.sh
NO
SonarCloud Code Analysis
* #
=> New: Hookup SonarCloud

frontend/src/Movie/Index/Overview/MovieIndexOverviews.js, frontend/src/Movie/Index/Posters/MovieIndexPosters.js
NO
Make sure grid re-renders cells when switching mode
* #3931
=> Fixed: Poster/Overview checkbox in Movie Editor mode

azure-pipelines.yml
NO
Skip Sonar Analysis on Forks until we can figure out a way to enable without allowing full access to our secure connections in Azure.
This will skip frontend and backend sonar but leave coverage intact.
* #
=> Fixed: Sonar failure on external forks

src/NzbDrone.Core.Test/IndexerTests/RarbgTests/RarbgFixture.cs, src/NzbDrone.Core/Indexers/Rarbg/RarbgParser.cs
NO
Applied new RARBG URL format as used in Sonarr.
For comparison see: https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core/Indexers/Rarbg/RarbgParser.cs#L54
* #
=> Fix RARBG URL Scheme

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs, src/NzbDrone.Core/Extras/ExtraService.cs, src/NzbDrone.Core/Extras/Subtitles/SubtitleService.cs, src/NzbDrone.Core/Parser/LanguageParser.cs
=> Revert "Fixed: .srt files in subfolders are not being imported"

frontend/src/Activity/History/HistoryRow.js, frontend/src/Store/Actions/historyActions.js
No
Fix property name per discord conversation
None
=> Fix languages property

src/NzbDrone.Api/Config/NetImportConfigResource.cs, src/NzbDrone.Core/Configuration/ConfigService.cs, src/NzbDrone.Core/Configuration/IConfigService.cs, src/NzbDrone.Core/NetImport/NetImportRepository.cs, src/NzbDrone.Core/NetImport/Trakt/TraktImport.cs, src/NzbDrone.Core/NetImport/Trakt/TraktRequestGenerator.cs, src/NzbDrone.Core/NetImport/Trakt/TraktSettings.cs, src/Radarr.Api.V3/Config/NetImportConfigResource.cs
NO
Move Trakt Auth to per List
=> New: Trakt Auth per List

src/NzbDrone.Automation.Test/AutomationTest.cs
=> New: Change Automation timeout to 3min

frontend/src/System/Tasks/Scheduled/ScheduledTaskRow.css, frontend/src/System/Tasks/Scheduled/ScheduledTaskRow.js, frontend/src/System/Tasks/Scheduled/ScheduledTasks.js, src/NzbDrone.Core/Datastore/Migration/163_task_duration.cs, src/NzbDrone.Core/Jobs/ScheduledTask.cs, src/NzbDrone.Core/Jobs/ScheduledTaskRepository.cs, src/NzbDrone.Core/Jobs/Scheduler.cs, src/NzbDrone.Core/Jobs/TaskManager.cs, src/NzbDrone.Core/Messaging/Commands/Command.cs, src/NzbDrone.Core/Messaging/Commands/CommandQueueManager.cs, src/NzbDrone.Core/MetadataSource/IProvideMovieInfo.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/Movies/RefreshMovieService.cs, src/Radarr.Api.V3/System/Tasks/TaskModule.cs, src/Radarr.Api.V3/System/Tasks/TaskResource.cs
YES
- Store LastStartTime for Scheduled Task in DB.
- Add Last Duration to Tasks Page in UI.
- Refresh only movies that TMDB says have changed since our last refresh.
* #
=> New: Aphrodite smart refresh

src/NzbDrone.Core/Parser/Parser.cs
=> fix language debug

src/NzbDrone.Core/Download/DownloadService.cs
=> Fixed: Use Download Client name for grabbed history events

src/NzbDrone.Core/Parser/ParsingService.cs
=> Fixed: Null exception on EnhanceMovieInfo

azure-pipelines.yml
NO
Run oldest supported (5.10), current recommended (5.20), latest
stable (6.6) and preview (6.8)
=> Slim down mono test suite

azure-pipelines.yml, frontend/src/Store/Middleware/createSentryMiddleware.js, src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs
NO
Switch to self hosted sentry
=> Update sentry DSN to self hosted

azure-pipelines.yml
=> Fix sentry project names

src/NzbDrone.Core.Test/NetImport/NetImportSearchServiceFixture.cs, src/NzbDrone.Core/NetImport/NetImportSearchService.cs
https://github.com/Radarr/Radarr/commit/c300af82415c6f71af67a74d1f59ae9b2b30c674#diff-4199a537105793b9a05a6232cb0531bb
that caused SQL error when doing netimport search
NO
* #
=> Fixed: Reverted a change that caused SQL error on Netimport

azure-pipelines.yml
NO
Changes logic to run full if backend changes instead of not running full on any non backend changes. (Mixed PRs were running light builds)
Show Regex Matches in build log.
* #
=> Fixed: Build on Backend, Not Don’t Build If any Non Backend

src/NzbDrone.Core/MediaFiles/UpdateMovieFileService.cs, src/NzbDrone.Core/Movies/MovieRepository.cs, src/NzbDrone.Core/Movies/MovieService.cs
NO
Remove wonky query and use moviefile property directly.
Fixes RADARR3-5V
=> Fixed: Regression setting file date

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
NO
Add Radarr_Download_Client to OnDownload CustomScript
None
=> Add Radarr_Download_Client to OnDownload

frontend/src/Components/Form/FormInputGroup.js, frontend/src/Components/Form/ProviderFieldFormGroup.js, frontend/src/Components/Form/TagSelectInputConnector.js, frontend/src/Helpers/Props/inputTypes.js, src/NzbDrone.Core/Annotations/FieldDefinitionAttribute.cs, src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHDSettings.cs, src/NzbDrone.Core/Indexers/HDBits/HDBitsSettings.cs, src/NzbDrone.Core/Indexers/IPTorrents/IPTorrentsSettings.cs, src/NzbDrone.Core/Indexers/ITorrentIndexerSettings.cs, src/NzbDrone.Core/Indexers/Nyaa/NyaaSettings.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornSettings.cs, src/NzbDrone.Core/Indexers/Rarbg/RarbgSettings.cs, src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotatoSettings.cs, src/NzbDrone.Core/Indexers/TorrentRss/TorrentRssIndexerSettings.cs, src/NzbDrone.Core/Indexers/Torznab/TorznabSettings.cs, src/Radarr.Http/ClientSchema/SchemaBuilder.cs
NO
- Fixes Indexer Seed options by setting public settler for SeedCriteriaSettings due to restraint by System.Text.JSON
- Add Field Type for TagSelect and Re-Enable Indexer Flags field for torrent indexers.
Fixes #4031
=> Fix indexer seed options, Re-Enable Indexer Flags

src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatAudioChannelsFixture.cs, src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
NO
Handles cases when audio channel position is 3/2/0.2.1
Thought there was an issue dealing with this as well, but can't find it. 
Fixes RADARR3-7
Fixes RADARR3-6
=> Fixed: Handle 3 digit audio channels

src/NzbDrone.Core/Indexers/Newznab/Newznab.cs
As discussed here https://github.com/Radarr/Radarr/pull/3568
=> Fix NZB Finder categories

src/NzbDrone.Core.Test/MediaFiles/UpgradeMediaFileServiceFixture.cs, src/NzbDrone.Core/HealthCheck/Checks/RootFolderCheck.cs, src/NzbDrone.Core/MediaFiles/Events/MovieImportFailedEvent.cs, src/NzbDrone.Core/MediaFiles/MovieFileMovingService.cs, src/NzbDrone.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs, src/NzbDrone.Core/MediaFiles/MovieImport/RootFolderNotFoundException.cs, src/NzbDrone.Core/MediaFiles/UpgradeMediaFileService.cs
NO
Adds better import error logging in certain cases, fixes #4066
Pulled from Sonarr
Fixes #4066
=> Fixed: Not deleting movie files during upgrade when root folder is missing

.editorconfig, src/NzbDrone.Core/Datastore/Migration/166_fix_tmdb_list_config.cs, src/NzbDrone.Core/NetImport/TMDb/Popular/TMDbPopularRequestGenerator.cs, src/NzbDrone.Core/NetImport/TMDb/Popular/TMDbPopularSettings.cs, src/NzbDrone.Core/NetImport/TMDb/TMDbFilterSettings.cs, src/NzbDrone.Core/NetImport/Trakt/TraktParser.cs, src/NzbDrone.Core/NetImport/Trakt/TraktRequestGenerator.cs, src/NzbDrone.Core/NetImport/Trakt/TraktSettings.cs
YES (166)
Add in missing migration to convert old `TMDbImport` to `TMDbListImport` and `TMDbPopularImport`
* Radarr fails to start in 2525
Fixes #3840
=> Fixed: Migrate the old TMDb list definitions to new type

src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
=> Fix null tmdb images

frontend/src/InteractiveSearch/InteractiveSearchContent.js
NO
Changes episode to movie for UI string when search results can't be loaded.
* #
=> fix: no search results ui string

azure-pipelines.yml
NO
Bump Ubuntu and osx agent version
* fixes #4100
=> Upgrade build agents

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
New: Add Release Date and Cinema Date to Custom Script (Backport aphrodite)
=> New: Add Release Date and Cinema Date to Custom Script (Backport aphrodite)

src/NzbDrone.Core/HealthCheck/Checks/UpdateCheck.cs
=> Fixed: Don't check update folder writable in docker

src/NzbDrone.Core.Test/MetadataSource/SkyHook/SkyHookProxyFixture.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/Movies/MovieService.cs
NO
Fixes #4152, Pulled from Aphrodite
=> Fixed: Populate Info in Lookup Results if Existing Movie

frontend/src/Components/Form/QualityProfileSelectInputConnector.js, frontend/src/InteractiveImport/Movie/SelectMovieModalContent.css, frontend/src/InteractiveImport/Movie/SelectMovieModalContent.js, frontend/src/InteractiveImport/Movie/SelectMovieModalContentConnector.js, frontend/src/InteractiveImport/Movie/SelectMovieRow.css, frontend/src/Settings/DownloadClients/DownloadClients/DownloadClients.js, frontend/src/Settings/DownloadClients/DownloadClients/DownloadClientsConnector.js, frontend/src/Settings/Indexers/Indexers/Indexers.js, frontend/src/Settings/Indexers/Indexers/IndexersConnector.js, frontend/src/Settings/Metadata/Metadata/Metadatas.js, frontend/src/Settings/Metadata/Metadata/MetadatasConnector.js, frontend/src/Settings/NetImport/NetImport/NetImports.js, frontend/src/Settings/NetImport/NetImport/NetImportsConnector.js, frontend/src/Settings/Notifications/Notifications/Notifications.js, frontend/src/Settings/Notifications/Notifications/NotificationsConnector.js, frontend/src/Settings/Profiles/Quality/QualityProfiles.js, frontend/src/Settings/Profiles/Quality/QualityProfilesConnector.js, frontend/src/Store/Selectors/createSortedSectionSelector.js
NO
Separates out the non-CF stuff from #4102 
- Fixes state mutation bug so changes to setting appear to affect the wrong item.
- Improve performance of manual import movie select and hook up to the fuse worker async search
- Fixes #4110 
- Fixes #4136
=> Fixed: Frontend itemMap issues and movie select performance

azure-pipelines.yml
=> New: Bump .net core to 3.1.102

frontend/src/Components/Page/Header/PageHeader.css
NO
Fixes the vertical centering of the new logo
N/A
=> Fix Logo (logo, logoFull) Vertical Centering

azure-pipelines.yml
=> Change to Servarr TestImages

src/NzbDrone.Api/MovieFiles/MovieFileModule.cs, src/NzbDrone.Core.Test/MediaFiles/MediaFileDeletionService/DeleteMovieFileFixture.cs, src/NzbDrone.Core/MediaFiles/MediaFileDeletionService.cs, src/NzbDrone.Core/MediaFiles/RecycleBinProvider.cs, src/Radarr.Api.V3/MovieFiles/MovieFileModule.cs
Pull from Sonarr
Reference https://github.com/Sonarr/Sonarr/issues/1782 and https://github.com/Sonarr/Sonarr/commit/c2b66cf52476baea9336b8f023d9c1e446183870
NO
=> Fixed: Delete a movie file from the UI that was already deleted from disk

frontend/src/Components/Modal/ConfirmModal.js
* # All quality profiles being deleted when pressing enter on the quality profile deletion screen.
=> Fixed: Enter on Delete profile confirmation deleting all unused profiles

src/NzbDrone.Mono/Disk/DiskProvider.cs
NO
Catch UnauthorizedAccessException and attempt to clean up where we know it's not doing the right thing.
* #4194
=> Fixed: Workaround for mono 6.x file copy/move issues

src/NzbDrone.Core.Test/HealthCheck/Checks/ReleaseBranchCheckFixture.cs, src/NzbDrone.Core/HealthCheck/Checks/ReleaseBranchCheck.cs
NO
Warn user if branch is invalid
=> New: HealthCheck for valid Branch value

src/NzbDrone.Core/Datastore/Migration/157_remove_growl_prowl.cs, src/NzbDrone.Core/Notifications/Prowl/Prowl.cs, src/NzbDrone.Core/Notifications/Prowl/ProwlException.cs, src/NzbDrone.Core/Notifications/Prowl/ProwlPriority.cs, src/NzbDrone.Core/Notifications/Prowl/ProwlProxy.cs, src/NzbDrone.Core/Notifications/Prowl/ProwlSettings.cs
NO (Modify Existing DB Migration to Not Remove Prowl on Upgrade)
Adds Prowl Notification support native in Radarr.
#3919
=> New: Add back Prowl Notifications

src/NzbDrone.Core/NetImport/Trakt/TraktSettings.cs
NO
Adds UserCustomList to the Username validation rule
None
Fixes #4255
=> Fixed: Made Username required for UserCustomList (#4255)

frontend/src/Movie/Details/MovieDetails.css, frontend/src/Movie/Details/MovieDetails.js, frontend/src/Settings/MediaManagement/Naming/NamingModal.js, frontend/src/Settings/Metadata/MetadataSettings.js, frontend/src/Settings/Metadata/Options/MetadataOptions.js, frontend/src/Settings/Metadata/Options/MetadataOptionsConnector.js, frontend/src/Store/Actions/Settings/metadataOptions.js, frontend/src/Store/Actions/movieIndexActions.js, frontend/src/Store/Actions/settingsActions.js, src/NzbDrone.Core/Configuration/ConfigService.cs, src/NzbDrone.Core/Configuration/IConfigService.cs, src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs, src/NzbDrone.Core/Languages/LanguagesComparer.cs, src/NzbDrone.Core/MetadataSource/SkyHook/Resource/TMDbCountryCode.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/Notifications/Telegram/TelegramService.cs, src/NzbDrone.Core/Organizer/FileNameBuilder.cs, src/NzbDrone.Core/Parser/Augmenters/AugmentWithMediaInfo.cs, src/NzbDrone.Core/Qualities/Quality.cs, src/NzbDrone.Core/Qualities/QualityFinder.cs, src/Radarr.Api.V3/Config/MetadataConfigModule.cs, src/Radarr.Api.V3/Config/MetadataConfigResource.cs
NO
- Fills in movie certifications (MPAA Rating, etc) with country options 
- ~~Allows enable of Radarr “Bonarr Mode” (Adult Content)~~ Shelf for another PR
- ~~[ ] Movie Type so we can filter, sort, search different for adult?~~ Shelf
Fixes #4254 
Fixes #844 
* #
=> New: Movie Certifications

frontend/src/Settings/General/UpdateSettings.js, frontend/src/System/Status/About/About.js, frontend/src/System/Updates/Updates.js, src/NzbDrone.Core/Configuration/DeploymentInfoProvider.cs, src/NzbDrone.Core/Update/ConfigureUpdateMechanism.cs, src/NzbDrone.Core/Update/InstallUpdateService.cs, src/NzbDrone.Core/Update/UpdateMechanism.cs, src/Radarr.Api.V3/System/SystemModule.cs
NO
Set the Radarr branch and updateMechanism from package_info file
=> New: Set Branch, Update Mech from PackageInfo

azure-pipelines.yml
NO
A better Discord Notification
Fixes #4060
=> Discord Azure Notification

azure-pipelines.yml
=> Bump .net core to 3.1.4

src/NzbDrone.Common/Disk/DiskProviderBase.cs, src/NzbDrone.Common/Disk/IDiskProvider.cs, src/NzbDrone.Core.Test/MediaFiles/DiskScanServiceTests/ScanFixture.cs, src/NzbDrone.Core/MediaFiles/DiskScanService.cs
NO
Pull scanning speedup from sonarr
=> Fixed: Performance issue when scanning large root folder

src/NzbDrone.Core.Test/Datastore/TableMapperFixture.cs, src/NzbDrone.Core.Test/Datastore/WhereBuilderFixture.cs, src/NzbDrone.Core/Blacklisting/BlacklistRepository.cs, src/NzbDrone.Core/Datastore/BasicRepository.cs, src/NzbDrone.Core/Datastore/Extensions/BuilderExtensions.cs, src/NzbDrone.Core/Datastore/Extensions/MappingExtensions.cs, src/NzbDrone.Core/Datastore/Extensions/SqlMapperExtensions.cs, src/NzbDrone.Core/Datastore/LazyLoaded.cs, src/NzbDrone.Core/Datastore/SqlBuilder.cs, src/NzbDrone.Core/Datastore/TableMapper.cs, src/NzbDrone.Core/Datastore/WhereBuilder.cs, src/NzbDrone.Core/History/HistoryRepository.cs, src/NzbDrone.Core/Movies/MovieRepository.cs, src/NzbDrone.Core/Profiles/ProfileRepository.cs, src/NzbDrone.Core/Radarr.Core.csproj, src/NzbDrone.Core/ThingiProvider/ProviderRepository.cs
NO
Also pulls across Dapper improvements from Readarr.
Fixes Sentry RADARR-1V
Fixes #4359
=> Fixed: Rename more than 999 movies in one go

src/NzbDrone.Console/ConsoleApp.cs, src/NzbDrone.Core/Validation/Paths/FileExistsValidator.cs, src/NzbDrone.Host/WebHost/WebHostController.cs, src/Radarr.Api.V3/Config/HostConfigModule.cs
NO
Trap kestrel address bind error to avoid bootloop
Trap missing cert file exception
Add validator to ensure certificate file exists and is valid before saving config
* # 4403
=> Fix boot loop

src/NzbDrone.Core.Test/Datastore/TableMapperFixture.cs, src/NzbDrone.Core.Test/Datastore/WhereBuilderFixture.cs, src/NzbDrone.Core/Blacklisting/BlacklistRepository.cs, src/NzbDrone.Core/Datastore/BasicRepository.cs, src/NzbDrone.Core/Datastore/Extensions/BuilderExtensions.cs, src/NzbDrone.Core/Datastore/Extensions/MappingExtensions.cs, src/NzbDrone.Core/Datastore/Extensions/SqlMapperExtensions.cs, src/NzbDrone.Core/Datastore/LazyLoaded.cs, src/NzbDrone.Core/Datastore/SqlBuilder.cs, src/NzbDrone.Core/Datastore/TableMapper.cs, src/NzbDrone.Core/Datastore/WhereBuilder.cs, src/NzbDrone.Core/History/HistoryRepository.cs, src/NzbDrone.Core/Movies/MovieRepository.cs, src/NzbDrone.Core/Profiles/ProfileRepository.cs, src/NzbDrone.Core/Radarr.Core.csproj, src/NzbDrone.Core/ThingiProvider/ProviderRepository.cs
NO
This time with correct SQL queries for checking if column value in a list.
=> Fixed: Rename more than 999 movies in one go (v2)

frontend/src/Components/SignalRConnector.js, frontend/src/Store/Selectors/createHealthCheckSelector.js, frontend/src/System/Status/Health/HealthConnector.js, frontend/src/System/Status/Health/HealthStatusConnector.js
NO
Warn in UI if signalr fails to connect. Its perhaps a bit of a bodge editing the health check items browser side, let me know if you have a better idea.
* #
=> New: Warn if UI won't update due to SignalR errors

src/NzbDrone.Core.Test/MovieTests/RefreshMovieServiceFixture.cs, src/NzbDrone.Core.Test/NetImport/NetImportSearchServiceFixture.cs, src/NzbDrone.Core/Movies/RefreshMovieService.cs, src/NzbDrone.Core/NetImport/NetImportSearchService.cs
This reverts commit 2bdd806565594c465b1e6f4b84dde50527df9ded.
NO
Revert async refresh
* #
=> Revert "Use async api calls for Refresh and NetImportSync"

src/NzbDrone.Common/Extensions/StreamExtensions.cs, src/NzbDrone.Common/Http/Dispatchers/IHttpDispatcher.cs, src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs, src/NzbDrone.Common/Http/HttpClient.cs, src/NzbDrone.Common/TPL/RateLimitService.cs, src/NzbDrone.Core.Test/MovieTests/RefreshMovieServiceFixture.cs, src/NzbDrone.Core.Test/NetImport/NetImportSearchServiceFixture.cs, src/NzbDrone.Core/MetadataSource/IProvideMovieInfo.cs, src/NzbDrone.Core/MetadataSource/ISearchForNewMovie.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/Movies/RefreshMovieService.cs, src/NzbDrone.Core/NetImport/NetImportSearchService.cs, src/NzbDrone.Core/NetImport/TMDb/TMDbImportBase.cs, src/NzbDrone.Host/ApplicationServer.cs, src/Radarr.Api.V3/Movies/FetchMovieListModule.cs
NO
Revert Async HttpClient/Refresh/Mapping for now
=> Async revert

src/NuGet.config, src/NzbDrone.Common/Radarr.Common.csproj, src/NzbDrone.Core.Test/Radarr.Core.Test.csproj, src/NzbDrone.Core/Radarr.Core.csproj
NO
Upgrade sqlite to 3.30.1 and system.data.sqlite to 1.0.112
=> New: Upgrade sqlite to 3.32.1 and system.data.sqlite to 1.0.113

src/NzbDrone.Core.Test/Datastore/Migration/174_email_multiple_addressesFixture.cs, src/NzbDrone.Core.Test/NotificationTests/EmailTests/EmailSettingsValidatorFixture.cs, src/NzbDrone.Core/Datastore/Migration/174_email_multiple_addresses.cs, src/NzbDrone.Core/Notifications/Email/EmailService.cs, src/NzbDrone.Core/Notifications/Email/EmailSettings.cs, src/Radarr.Http/ClientSchema/SchemaBuilder.cs
NO
- Add Ability to specify multiple recipients
- Add Ability to add CC and Bcc recipients
Fixes #3580
=> New: Multiple Recipients on Email Notifications (Also CC, BCC)

frontend/src/Settings/MediaManagement/MediaManagement.js, src/NzbDrone.Api/Config/MediaManagementConfigModule.cs, src/NzbDrone.Api/Config/MediaManagementConfigResource.cs, src/NzbDrone.Common.Test/DiskTests/DiskTransferServiceFixture.cs, src/NzbDrone.Common/Disk/DiskProviderBase.cs, src/NzbDrone.Common/Disk/IDiskProvider.cs, src/NzbDrone.Core/Configuration/ConfigService.cs, src/NzbDrone.Core/Configuration/IConfigService.cs, src/NzbDrone.Core/Datastore/Migration/175_remove_chown_and_folderchmod_config.cs, src/NzbDrone.Core/MediaFiles/DiskScanService.cs, src/NzbDrone.Core/MediaFiles/MediaFileAttributeService.cs, src/NzbDrone.Core/Update/InstallUpdateService.cs, src/NzbDrone.Core/Validation/FileChmodValidator.cs, src/NzbDrone.Mono.Test/DiskProviderTests/DiskProviderFixture.cs, src/NzbDrone.Mono/Disk/DiskProvider.cs, src/NzbDrone.Update/UpdateEngine/InstallUpdateService.cs, src/NzbDrone.Windows/Disk/DiskProvider.cs, src/Radarr.Api.V3/Config/MediaManagementConfigModule.cs, src/Radarr.Api.V3/Config/MediaManagementConfigResource.cs
YES (175 remove config settings)
Removed chown and simplified chmod options for linux/osx
Pulled from Sonarr
=> New: Removed chown and simplified chmod options for linux/osx

src/NzbDrone.Common.Test/PathExtensionFixture.cs, src/NzbDrone.Common/Cloud/RadarrCloudRequestBuilder.cs, src/NzbDrone.Common/Extensions/PathExtensions.cs, src/NzbDrone.Core.Test/UpdateTests/UpdateServiceFixture.cs, src/NzbDrone.Core/Update/InstallUpdateService.cs
No
Debug Aphrodite Update Paths
=> v0.2 > v3 Update Fixes

src/NzbDrone.Common.Test/PathExtensionFixture.cs, src/NzbDrone.Common/Extensions/PathExtensions.cs, src/NzbDrone.Core/Update/InstallUpdateService.cs
NO
Use .exe update executable if updating to another 0.X package on mac
Fixes #4536
=> Develop update fix

src/NzbDrone.Core.Test/Languages/LanguageFixture.cs, src/NzbDrone.Core.Test/ParserTests/IsoLanguagesFixture.cs, src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs, src/NzbDrone.Core/Parser/IsoLanguage.cs, src/NzbDrone.Core/Parser/IsoLanguages.cs, src/NzbDrone.Core/Parser/LanguageParser.cs
NO
Adds back language parser tests
~~Adds Brazilian language (need some actual release test cases)~~ Future
Adds support for parsing IETF language tags (pt-BR)
=> New: Add Language Tests

src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/TorrentDownloadStationFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/UsenetDownloadStationFixture.cs, src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs, src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs
=> Fix false positive on remotepathhealthcheck for downloadstation client 

frontend/src/Movie/Index/MovieIndex.js, frontend/src/Movie/Index/MovieIndexConnector.js, src/NzbDrone.Core.Test/MovieTests/RefreshMovieServiceFixture.cs, src/NzbDrone.Core/Movies/Commands/RefreshMovieCommand.cs, src/NzbDrone.Core/Movies/MovieAddedHandler.cs, src/NzbDrone.Core/Movies/RefreshMovieService.cs, src/NzbDrone.Integration.Test/IntegrationTestBase.cs
NO
Ability to Refresh certain items
=> New: Refresh Selected in Editor Mode

frontend/src/Movie/Details/MovieDetailsConnector.js, frontend/src/Movie/Index/MovieIndexItemConnector.js
NO
Restore single movie refresh functionality 
* #
=> Fixed: Refresh from MovieDetails doesn’t refresh single

src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs, src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHDRssParser.cs, src/NzbDrone.Core/Parser/Model/ReleaseInfo.cs
=> Added support for AHD User Release indexer flag

frontend/src/Movie/Index/MovieIndexFooter.css, frontend/src/Movie/Index/MovieIndexFooter.js, frontend/src/Movie/Index/MovieIndexFooterConnector.js
=> Bug Fix: Movie index legend not respecting color blind setting

azure-pipelines.yml
=> Drop mono 6.8 tests, add 6.12

src/NzbDrone.Core.Test/Files/Indexers/Nyaa/Nyaa.xml, src/NzbDrone.Core.Test/IndexerTests/NyaaTests/NyaaFixture.cs, src/NzbDrone.Core/Indexers/Nyaa/NyaaRequestGenerator.cs, src/NzbDrone.Core/Indexers/Nyaa/NyaaSettings.cs
NO
- Fix the TLD; from se to si
- Fix the URL containing &term= twice
=> Nyaa indexer fixes

frontend/src/Movie/Index/Overview/MovieIndexOverview.css, frontend/src/Movie/Index/Overview/MovieIndexOverview.js, frontend/src/Movie/Index/Posters/MovieIndexPoster.css, frontend/src/Movie/Index/Posters/MovieIndexPoster.js, frontend/src/Movie/Index/Table/MovieIndexRow.css, frontend/src/Movie/Index/Table/MovieIndexRow.js
=> Added external links to movie index (formerly in v2)

frontend/src/DiscoverMovie/Overview/AddListMovieOverview.js, frontend/src/DiscoverMovie/Overview/AddListMovieOverviews.css, frontend/src/DiscoverMovie/Posters/AddListMoviePoster.css, frontend/src/DiscoverMovie/Posters/AddListMoviePoster.js, frontend/src/DiscoverMovie/Table/AddListMovieRow.css, frontend/src/DiscoverMovie/Table/AddListMovieRow.js, frontend/src/Movie/Details/MovieDetailsLinks.js
=> Added external links to Movies > Discovery

frontend/src/MovieFile/Editor/MovieFileEditorRow.css, frontend/src/MovieFile/Editor/MovieFileEditorTableContent.js
=> Fix issue with images stacking on the movie details page

frontend/src/AddMovie/AddNewMovie/AddNewMovieSearchResult.css, frontend/src/AddMovie/AddNewMovie/AddNewMovieSearchResult.js
NO
Adds external links to search results table. Original request for putting on the modal i dont think is realistic. To much information on the modal (also wanted actors/director) so adding the external links to the result table saves clicking each one to get to the links and having to cancel to get back to the table. 
Fixes #4583
=> Added external links to the search for movies.

frontend/src/Movie/Details/Credits/Cast/MovieCastPoster.js, frontend/src/Movie/Details/Credits/Crew/MovieCrewPoster.js, frontend/src/Movie/Index/Posters/MovieIndexPoster.css
NO
Fixed: UI issues with Cast/Crew on movie description page
Fixes #4652
=> Fix issue with containers not matching posters on cast/crew tabs

frontend/src/DiscoverMovie/DiscoverMovieFooter.js, frontend/src/DiscoverMovie/DiscoverMovieFooterConnector.js, frontend/src/Store/Actions/discoverMovieActions.js
NO
New: Add search checkbox to Movies > Discover
Fixes #4614
=> Add the search checkbox Movies > Discover

frontend/src/Components/HeartRating.js, frontend/src/Movie/Details/MovieDetails.css, frontend/src/Movie/Details/MovieDetails.js, frontend/src/MovieFile/Editor/MovieFileEditorRow.js, frontend/src/MovieFile/FileDetailsModal.js
NO
Fixed: Address issue with mobile view causing link/tags icon to drop a line on mobile view of the movie details
New: Changed runtime from ex 123 Minutes to 2h 3m
Fixes #4523
=> Fix the details page to be mobile friendly on the line with rating

frontend/src/Movie/Index/Table/MovieIndexRow.css
NO
Fix the spacing for the external links icon and fix the width to accommodate a new icon when search icon is showing
=> Movies > Table view > actions column mobile fix

frontend/src/Movie/Index/Table/MovieIndexHeader.css
=> Fix issue with headers on movie index table view not being aligned

frontend/src/AddMovie/ImportMovie/Import/ImportMovie.js
=> Cherry pick from PR 4784 to add changes related to lint & importing movies

frontend/src/Components/Filter/Builder/DateFilterBuilderRowValue.js, frontend/src/Helpers/Props/filterBuilderTypes.js, frontend/src/Helpers/Props/filterTypes.js, frontend/src/Utilities/Date/dateFilterPredicate.js
NO
New: Added new custom filters for Not in Last/Next for date filters
Fixes #4809
=> New: Added new custom filters for Not in Last/Next for date filters

src/NzbDrone.Core/Datastore/Migration/170_fix_trakt_list_config.cs, src/NzbDrone.Core/NetImport/Trakt/List/TraktListImport.cs, src/NzbDrone.Core/NetImport/Trakt/List/TraktListRequestGenerator.cs, src/NzbDrone.Core/NetImport/Trakt/Popular/TraktPopularImport.cs, src/NzbDrone.Core/NetImport/Trakt/Popular/TraktPopularRequestGenerator.cs, src/NzbDrone.Core/NetImport/Trakt/TraktImportBase.cs, src/NzbDrone.Core/NetImport/Trakt/TraktSettingsBase.cs, src/NzbDrone.Core/NetImport/Trakt/User/TraktUserImport.cs, src/NzbDrone.Core/NetImport/Trakt/User/TraktUserRequestGenerator.cs
=> Fix migration 170

frontend/src/Store/Selectors/createQueueItemSelector.js
=> Don't process queue item without details

src/NzbDrone.Core/Movies/RefreshMovieService.cs
NO
Fixed: Updating a movie during a refresh would reset the saved changes
Fixes #4807
=> Cherry pick from PR 4807 updating a movie during a refresh would reset the saved changes

frontend/src/Movie/History/MovieHistoryRow.css, frontend/src/Movie/History/MovieHistoryRow.js
NO
Fixed: Long paths overflowing in series history
Fixes #4835
=> Fixed: Long paths overflowing in series history

src/NzbDrone.Core/Localization/Core/en.json
NO
Fixing a typo mentioned in the discord. 
* No issue opened
=> Fix typo in English localization.

frontend/src/Components/Table/Table.js
=> Cherry pick from PR 4784 to disable autofocus on table scroller

frontend/jsconfig.json, frontend/src/Components/Page/Header/MovieSearchInput.css, frontend/src/Components/Page/Header/MovieSearchInput.js, frontend/src/Components/Page/Header/fuse.worker.js, frontend/src/Movie/MovieImage.js, src/NzbDrone.Common/Composition/ContainerBuilderBase.cs, src/NzbDrone.Common/Reflection/ReflectionExtensions.cs, src/NzbDrone.Core/Datastore/DbFactory.cs, src/NzbDrone.Core/Extras/Metadata/MetadataService.cs, src/NzbDrone.Core/MediaCover/MediaCover.cs, src/NzbDrone.Core/MediaCover/MediaCoverProxy.cs, src/NzbDrone.Core/MediaCover/MediaCoverService.cs, src/NzbDrone.Host/CancelHandler.cs, src/Radarr.Api.V3/Movies/MovieLookupModule.cs, src/Radarr.Http/Frontend/Mappers/MediaCoverMapper.cs, src/Radarr.Http/Frontend/Mappers/MediaCoverProxyMapper.cs
=> Sonarr pulls 081520

frontend/src/Components/Link/Link.js, frontend/src/InteractiveSearch/InteractiveSearchRow.css, frontend/src/InteractiveSearch/InteractiveSearchRow.js
NO
Fixed: Address issue with table width on Movie > Details > Search when the title is extremely wide
=> Fix issue with the table stretching on the Movie > Details > Search

src/NzbDrone.Core/Notifications/Telegram/TelegramService.cs, src/NzbDrone.Core/Notifications/Telegram/TelegramSettings.cs
NO
New: Added silent notification option to telegram
Fixes #4877
=> New: Added silent notification option to telegram

frontend/src/Components/Form/DeviceInputConnector.js, frontend/src/Components/Form/ProviderFieldFormGroup.js, frontend/src/Store/Actions/providerOptionActions.js, src/NzbDrone.Core/Annotations/FieldDefinitionAttribute.cs, src/NzbDrone.Core/NetImport/Radarr/RadarrAPIResource.cs, src/NzbDrone.Core/NetImport/Radarr/RadarrImport.cs, src/NzbDrone.Core/NetImport/Radarr/RadarrSettings.cs, src/NzbDrone.Core/NetImport/Radarr/RadarrV3Proxy.cs, src/NzbDrone.Core/Notifications/PushBullet/PushBulletSettings.cs, src/Radarr.Http/ClientSchema/Field.cs, src/Radarr.Http/ClientSchema/SchemaBuilder.cs
NO
Adds ability to pass requestAction from field
Add ability to sync by tag for 2nd instance Radarr List
Fixes #4826
=> New: Allow Radarr List Sync by Source Tag

azure-pipelines.yml, package.json, src/NzbDrone.Api.Test/Radarr.Api.Test.csproj, src/NzbDrone.Automation.Test/Radarr.Automation.Test.csproj, src/NzbDrone.Common.Test/Radarr.Common.Test.csproj, src/NzbDrone.Common/Radarr.Common.csproj, src/NzbDrone.Core.Test/Radarr.Core.Test.csproj, src/NzbDrone.Host.Test/Radarr.Host.Test.csproj, src/NzbDrone.Host/Radarr.Host.csproj, src/NzbDrone.Integration.Test/Radarr.Integration.Test.csproj, src/NzbDrone.Libraries.Test/Radarr.Libraries.Test.csproj, src/NzbDrone.Mono.Test/Radarr.Mono.Test.csproj, src/NzbDrone.Update.Test/Radarr.Update.Test.csproj, src/NzbDrone.Windows.Test/Radarr.Windows.Test.csproj, yarn.lock
=> Bump to dotnet 3.1.7

azure-pipelines.yml, build.sh, src/NzbDrone.Automation.Test/AutomationTest.cs
NO
See if new driver fixes windows intermittent failures due to timeouts, also use default service instead of making our own
=> Try to fix windows automation tests

frontend/src/Movie/Details/MovieDetails.js, frontend/src/Movie/Index/Table/MovieIndexRow.js, frontend/src/Utilities/Date/formatRuntime.js
NO
Fix: Address issue with runtime on Movies > Details & Movie > Index > Table view
=> Fix: Address issue with runtime on Movies > Details

src/NzbDrone.Common.Test/Http/HttpClientFixture.cs, src/NzbDrone.Common/Http/Dispatchers/IHttpDispatcher.cs, src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs, src/NzbDrone.Common/Http/HttpClient.cs, src/NzbDrone.Common/Http/Proxy/IHttpProxySettingsProvider.cs, src/NzbDrone.Core.Test/Framework/CoreTest.cs, src/NzbDrone.Core/Http/HttpProxySettingsProvider.cs, src/NzbDrone.Core/Notifications/Trakt/TraktProxy.cs
NO
Movie DownloadFile to dispatcher, proxy all downloads. @Taloth per our conversation on changes to #4239. Mind taking a look at this?
Replaces #4239 
Fixes #3126 
Fixes #2656
Fixes #4673 
Closes #4691 
Closes #4675 
Closes #4676 
Closes #4777
=> Fixed: Use Proxy for MediaCovers and Metadata

src/NzbDrone.Api/Movies/MovieModule.cs, src/Radarr.Api.V3/Movies/MovieModule.cs
NO
Fix: Remove title requirement in the API for adding movies when the TMDb is provided since that will over-ride the given title.
=> Fix: Remove title requirement in the API for adding movies when the TMDb is provided since that will over-ride the given title.

src/NzbDrone.Common/EnvironmentInfo/OsInfo.cs
No
Return empty output if RunAndCapture fails in process to prevent epic failure 
#4890 
#4927 ?
=> Fixed: Don't fail if ldd doesn't exist

README.md
N/A
Add: Note that v0.2 is critical break/fix only
Fix: Clearify Docker Table
Remove: Feathub
Comment: Feature "* Scanning PreDB to know when a new release is available" Probably needs to be replaced
Add: Feature -  Importing movies from various online sources... "Trakt"
Remove: Planned Features
Change: Feature Request Link
N/A
N/A
* #
=> Readme Updates Part 1

frontend/src/Calendar/CalendarPage.js, frontend/src/Movie/Index/MovieIndex.js, frontend/src/Settings/General/HostSettings.js, frontend/src/Settings/Indexers/Options/IndexerOptions.js, frontend/src/System/Status/About/About.js, frontend/src/Utilities/String/translate.js, src/Radarr.Api.V3/Localization/LocalizationModule.cs
NO
Localization endpoint should not be CamelCase due to case sensitivity with keys
=> Don't Camel Case Localization Endpoint

frontend/src/System/Status/DiskSpace/DiskSpace.js
NO
New: Add label to disk usage progress bar
=> Add label to disk usage progress bar

frontend/src/Settings/Settings.js
NO
Fix a type in the translation of UI
=> Fix a type in the translation of UI

frontend/src/Movie/Index/Table/MovieIndexHeader.css, frontend/src/Movie/Index/Table/MovieIndexRow.css
NO
Adjust the width of runtime & added since they are to wide
=> Adjust the width of runtime & added since they are to wide

src/NzbDrone.Core/Notifications/Trakt/TraktService.cs
Just updated on production at Trakt's end. They are still discussing adding a new format for TV
NO
Trakt added some new audio formats, so refining the metadata we are sending to them.
* #
=> add more audio codecs for Trakt connection

src/NzbDrone.Core/Notifications/DiscordNotifier/DiscordNotifier.cs, src/NzbDrone.Core/Notifications/DiscordNotifier/DiscordNotifierException.cs, src/NzbDrone.Core/Notifications/DiscordNotifier/DiscordNotifierProxy.cs, src/NzbDrone.Core/Notifications/DiscordNotifier/DiscordNotifierSettings.cs
NO
Adds support for notifications using discordnotifier.com (fully configurable notifications vs webhook notifications)
=> Add support for discordnotifier connect type

src/Radarr.Api.V3/swagger.json
NO
Ongoing updates to the API docs
=> Update API Docs

frontend/src/Movie/Details/MovieStatusLabel.js, frontend/src/Movie/Index/Overview/MovieIndexOverview.js, frontend/src/Movie/Index/Posters/MovieIndexPoster.js, frontend/src/Movie/Index/ProgressBar/MovieIndexProgressBar.js, frontend/src/Movie/MovieFileStatus.js, frontend/src/Utilities/Movie/getProgressBarKind.js
NO
Fixed: Fix issue where status text was not consistent across all 3 index views and the details
=> Fix issue where status text was not consistent across all 3 index views and the details

frontend/src/Movie/Details/MovieStatusLabel.css, frontend/src/Movie/Details/MovieStatusLabel.js, frontend/src/Movie/Index/ProgressBar/MovieIndexProgressBar.js, frontend/src/Movie/MovieFileStatus.js, frontend/src/Utilities/Movie/getQueueStatusText.js, frontend/src/Utilities/String/firstCharToUpper.js
NO
Fix: Addressed issue with status color not showing on Movie > Details (only purple was working)
Fix: Address label confusion with status (purple & green both showing as Downloaded)
=> Fix: Addressed issue with status color not showing on Movie > Details

frontend/src/Components/Table/Cells/VirtualTableRowCell.js, frontend/src/Movie/Index/Table/MovieIndexRow.js, frontend/src/Movie/MovieTitleLink.js
NO
Add tooltip to path & movie title on the movie index table view
=> Add tooltip to path & movie title on the movie index table view

frontend/src/Calendar/Agenda/AgendaEvent.css, frontend/src/Calendar/Agenda/AgendaEvent.js, frontend/src/Calendar/Agenda/AgendaEventConnector.js
NO
Fix: Address issue with incorrect dates showing on the calendar agenda and add icons for which date type it is
=> Fix: Address issue with incorrect dates showing on the calendar agenda

frontend/src/System/Status/DiskSpace/DiskSpace.js, frontend/src/System/Status/DiskSpace/DiskSpaceConnector.js
NO
Fix issue with the disk space label percents overlapping on small screens
=> Fix issue with the disk space label percents overlapping on small screens

src/NzbDrone.Core/Notifications/Discord/Discord.cs, src/NzbDrone.Core/Notifications/Discord/DiscordColors.cs, src/NzbDrone.Core/Notifications/Discord/DiscordFieldType.cs, src/NzbDrone.Core/Notifications/Discord/DiscordSettings.cs, src/NzbDrone.Core/Notifications/Discord/Payloads/DiscordAuthor.cs, src/NzbDrone.Core/Notifications/Discord/Payloads/DiscordField.cs, src/NzbDrone.Core/Notifications/Discord/Payloads/DiscordImage.cs, src/NzbDrone.Core/Notifications/Discord/Payloads/Embed.cs
NO
- Better looking and completely customizable grab and import discord notifications... Thanks to @hotio for the inspiration.
- Fix healthcheck notifications
=> New: Customizable Discord Notifications (Thanks @hotio)

src/NzbDrone.Core/MediaFiles/MovieImport/Manual/ManualImportService.cs
NO
Fixed: Ignore files in subfolders during a manual import
Fixes: #5038 
Fixes: #5053
=> Fixed: Ignore files in subfolders during a manual import

frontend/src/Calendar/Agenda/AgendaEvent.js
NO
Fixed: Fix the grouping of movies on the same date in the calendar agenda view
=> Fix the grouping of movies on the same date in the calendar agenda view

src/NzbDrone.Core.Test/HealthCheck/Checks/ReleaseBranchCheckFixture.cs, src/NzbDrone.Core/HealthCheck/Checks/ReleaseBranchCheck.cs, src/NzbDrone.Core/Localization/Core/en.json
=> Aphrodite merged health check

frontend/src/Movie/Details/MovieDetails.js
NO
Fixed: Fix issue with arrow navigation from details working outside of the details page
=> Fix issue with arrow navigation from details working outside of the details page

frontend/src/System/Updates/UpdateChanges.js
NO
Add a link to the github issue if it is added to the change notes
=> Add a link to the github issue if it is added to the change notes

frontend/src/Movie/Details/MovieDetails.js
NO
Fixes: Fix find error on movie details
=> Fix find error on movie details

frontend/src/Movie/Details/MovieDetails.js
NO
Fix issue with arrow keys switching movie when using them inside a textbox (or any element really)
=> Fix issue with arrow keys switching movie when using them inside a textbox (or any element really)

frontend/src/InteractiveSearch/InteractiveSearchRowConnector.js, frontend/src/Movie/Details/MovieDetailsConnector.js, frontend/src/Store/Actions/index.js, frontend/src/Store/Actions/movieBlacklistActions.js, src/NzbDrone.Core.Test/Blacklisting/BlacklistRepositoryFixture.cs, src/NzbDrone.Core/Blacklisting/BlacklistRepository.cs, src/NzbDrone.Core/Blacklisting/BlacklistService.cs, src/NzbDrone.Core/CustomFormats/CustomFormatCalculationService.cs, src/Radarr.Api.V3/Blacklist/BlacklistModule.cs
NO
Add endpoint to fetch blacklist items by movie
Fixes #5066
=> Fixed: Fetch blacklist by Movie instead of all

frontend/src/Calendar/Agenda/Agenda.js, frontend/src/Calendar/Agenda/AgendaEvent.css, frontend/src/Calendar/Agenda/AgendaEvent.js, frontend/src/Calendar/Agenda/AgendaEventConnector.js, frontend/src/Calendar/Header/CalendarHeader.js
NO
Fixed: Fix the sorting on the agenda to respect using all dates instead of only cinema date to sort
=> Fix the sorting on the agenda to respect using all dates instead of only cinema date to sort

frontend/src/Settings/MediaManagement/Naming/NamingModal.js, src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs, src/NzbDrone.Core/Organizer/FileNameBuilder.cs
NO
Name by original movie title
* #
=> New: Allow naming with original Movie title (in original language)

CONTRIBUTING.md
=> Correct Contributing (don't have forums or IRC) [skip ci]

frontend/src/AddMovie/AddNewMovie/AddNewMovieModalContent.js, frontend/src/Components/Form/RootFolderSelectInputOption.css
NO
Fix: Address issue with movie title stretching the add window
Fixes: #5096
=> Address issue with movie title stretching the add window

src/Radarr.Api.V3/swagger.json
NO
Added group names & some more endpoints.
=> Ongoing updates to api docs

frontend/src/Movie/Index/Posters/MovieIndexPosterInfo.js
NO
Fix broken translations on index
=> Fix broken translations on index

frontend/src/Movie/Delete/DeleteMovieModalContentConnector.js, frontend/src/Movie/Details/MovieDetails.js
NO
Fix issue with deleting a movie not going to previous one for some users (missing the URL base)
Swapped it from previous to next
=> Fix issue with deleting a movie not going to previous one for some users

frontend/src/Components/Form/EnhancedSelectInput.js, frontend/src/Components/Form/EnhancedSelectInputOption.css, frontend/src/Components/Form/EnhancedSelectInputOption.js, frontend/src/Components/Form/HintedSelectInputOption.js, frontend/src/Components/Form/HintedSelectInputSelectedValue.js, frontend/src/Components/Form/ProviderFieldFormGroup.js, src/NzbDrone.Core/Annotations/FieldDefinitionAttribute.cs, src/NzbDrone.Core/Annotations/SelectOption.cs, src/NzbDrone.Core/Indexers/FileList/FileListSettings.cs, src/Radarr.Http/ClientSchema/SchemaBuilder.cs
NO
Adds Multiselect control to Filelist.io (later to future items)
Fixes #5108 
Fixes #5109 
Fixes #5111 
Fixes #5112
=> New: MultiSelect input control for provider settings

src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs, src/NzbDrone.Core/Datastore/Extensions/BuilderExtensions.cs, src/NzbDrone.Core/Datastore/Extensions/SqlMapperExtensions.cs
=> Log out SQL trace on error

azure-pipelines.yml, src/NzbDrone.Automation.Test/AutomationTest.cs, src/NzbDrone.Automation.Test/MainPagesTest.cs
=> Take Screenshot on Automation tests for build status notifications

azure-pipelines.yml, src/NzbDrone.Automation.Test/Radarr.Automation.Test.csproj
NO
Fixed: Ignore failure of screenshot bundle (it doesn't matter that much)
Fixed: Don't install fpcalc for Radarr
Fixed: We don't use geckodrivers anymore for automation
=> Cleanup build yml

src/NzbDrone.Core/ImportLists/RadarrList2/IMDb/IMDbListParser.cs
NO
Fixed: Fix issue with IMDb lists (some not all) not parsing properly causing an issue when trying to add them
=> Fix issue with IMDb lists (some not all) not parsing properly causing an issue when trying to add them

frontend/src/Components/Form/FormInputGroup.js, frontend/src/Components/Form/IndexerFlagsSelectInputConnector.js, frontend/src/Components/Page/PageConnector.js, frontend/src/Helpers/Props/inputTypes.js, frontend/src/MovieFile/Edit/FileEditModal.js, frontend/src/MovieFile/Edit/FileEditModalContent.js, frontend/src/MovieFile/Edit/FileEditModalContentConnector.js, frontend/src/MovieFile/Editor/MovieFileEditorRow.js, frontend/src/Store/Actions/Settings/indexerFlags.js, frontend/src/Store/Actions/movieFileActions.js, frontend/src/Store/Actions/settingsActions.js, src/NzbDrone.Core/Localization/Core/en.json, src/Radarr.Api.V3/Indexers/IndexerFlagModule.cs, src/Radarr.Api.V3/Indexers/IndexerFlagResource.cs, src/Radarr.Api.V3/MovieFiles/MovieFileListResource.cs, src/Radarr.Api.V3/MovieFiles/MovieFileModule.cs, src/Radarr.Api.V3/MovieFiles/MovieFileResource.cs, yarn.lock
NO
Edit Edition and Release Group for Movie Files
Fixes #4633 
Fixes #3664
=> New: Edit RlsGroup, Flags, and Edition for Movie Files

frontend/src/Utilities/Date/getRelativeDate.js, frontend/src/Utilities/Date/isToday.js, frontend/src/Utilities/Date/isTomorrow.js, frontend/src/Utilities/Date/isYesterday.js, src/NzbDrone.Core/Localization/Core/en.json
NO
Remove some instances of moment that are not needed on the index to reduce the load
=> Remove some instances of moment that are not needed on the index to reduce the load

src/NzbDrone.Core.Test/Datastore/Migration/186_fix_tmdb_duplicatesFixture.cs, src/NzbDrone.Core/Datastore/Migration/186_fix_tmdb_duplicates.cs
YES
Clean duplicate movies in DB and add unique constraint to TMDbId
Fixes #5189
=> Fixed: Clean DB dupes and add unique constrain

azure-pipelines.yml, package.json, src/NzbDrone.Common/Radarr.Common.csproj, src/NzbDrone.Host/Radarr.Host.csproj, src/NzbDrone.Integration.Test/Radarr.Integration.Test.csproj, src/Radarr.Api.V3/swagger.json, yarn.lock
NO
Title - Last bump for 3.0 release
* #
=> Bump to dotnet core 3.1.10

src/NzbDrone/Radarr.csproj
NO
follow up to: https://github.com/Radarr/Radarr/commit/3a8ca21a17eab7fb36b9872deaadb94ddcd0b9e5
=> Add NeutralLanguage to Radarr.csproj to appease VS 16.8

frontend/src/DiscoverMovie/Overview/DiscoverMovieOverview.js, frontend/src/DiscoverMovie/Table/DiscoverMovieRow.js, src/NzbDrone.Core/Localization/Core/en.json
NO
- Adds tool tip to Recommended on discover
- Fixes a missed translation on Discover Overview
* Fixes #5317 
First Draft and done without coffee
=> Add Discover Recommended tooltip

frontend/src/AddMovie/AddNewMovie/AddNewMovieModalContent.js, frontend/src/Store/Actions/addMovieActions.js, frontend/src/Utilities/Movie/getNewMovie.js, src/NzbDrone.Core/Localization/Core/en.json
NO
~~Change monitor true/false to yes/no~~
Change Add Movie Monitor From Dropdown to Checkbox
Fixes #5263
=> New: Change Add Movie Monitor Selection from Dropdown to Checkbox

azure-pipelines.yml, build.sh, setup/radarr.iss, src/Directory.Build.props, src/NzbDrone/Radarr.csproj
NO
Build x86 version of windows package and installer
Bump Windows MI to 20.09
=> Build Win x86 zip and installer

frontend/src/Settings/Metadata/Options/MetadataOptions.js, src/NzbDrone.Core/MetadataSource/SkyHook/Resource/TMDbCountryCode.cs
NO
Add Spain to list of Certifications based on https://github.com/Radarr/Radarr/commit/6beb8c8b05847e08eb775032048e37350dd350f3
* Fixes #5374
=> New: Add Spain to list of Certifications

src/NzbDrone.Core/Update/InstallUpdateService.cs
=> Fixed: Set correct permissions on Radarr.Update before starting

CONTRIBUTING.md
=> use lidarr's contributing as a new template for radarr [skip ci]

src/NzbDrone.Core.Test/Datastore/Migration/188_mediainfo_channel_propertiesFixture.cs, src/NzbDrone.Core/Datastore/Migration/188_mediainfo_channels.cs, src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
YES (188)
Migrates mediainfo props in db that were changed in f9733eea7
=> Fixed: Migrate Mediainfo properties that changed names

src/NzbDrone.Core.Test/Datastore/SortKeyValidationFixture.cs, src/NzbDrone.Core/Datastore/TableMapper.cs, src/Radarr.Http/REST/RestModule.cs
NO
Validate sortKey passed by API
=> Fixed: Add SortKey validation

README.md
=> add API Doc Link to ReadMe [skip ci]

frontend/src/InteractiveSearch/InteractiveSearchRow.css
NO
Adjust CSS so titles are wrap instead of truncate
Fixes #5350
Fixes #3926
=> Adjust CSS so titles are wrap instead of truncate

src/NzbDrone.Core/HealthCheck/Checks/MonoNotNetCoreCheck.cs
NO
Don't nag linux x86 users to swap to net core
=> Don't nag linux x86 users to switch to net core

README.md
NO
fix feature requests link
NA
NA
NA
=> fix feature requests link

frontend/src/Store/Middleware/createSentryMiddleware.js
NO
Quit sending these to sentry, they are benign.
=> Ignore ResizeObserver loop limit errors

README.md
=> fix readme wiki badge [skip ci]

src/NzbDrone.Core.Test/Languages/LanguageFixture.cs, src/NzbDrone.Core.Test/Localization/LocalizationServiceFixture.cs, src/NzbDrone.Core.Test/ParserTests/IsoLanguagesFixture.cs, src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs, src/NzbDrone.Core/Languages/Language.cs, src/NzbDrone.Core/Localization/LocalizationService.cs, src/NzbDrone.Core/Parser/IsoLanguages.cs, src/NzbDrone.Core/Parser/LanguageParser.cs
NO
Add support for Pt-Br
* Fixes #1626
=> New: Portuguese (Brazil) Language Support

frontend/src/Components/Link/Link.js, frontend/src/Components/Page/Header/PageHeader.js
NO
tested...works
* Fixes #5603
* Fixes #5555
=> Fixed: '/movie' URL Base breaking UI navigation

CONTRIBUTING.md
=> fix contributing port [skip ci]

src/NzbDrone.Common.Test/DiskTests/DiskProviderFixtureBase.cs, src/NzbDrone.Common/Disk/DiskProviderBase.cs
NO
Same fix with some flushing.
* Fixes
=> Fixed: FolderWritable check for CIFS shares mounted in Unix v2

src/NzbDrone.Core/Localization/Core/en.json
NO
see diff
-  Tests-N/A
-  Translation Keys-N/A
-  Wiki Updates-N/A
* Fixes #5651
=> reword library import do not use for downloads text

frontend/src/AddMovie/ImportMovie/Import/ImportMovieHeader.js, frontend/src/AddMovie/ImportMovie/Import/ImportMovieRow.js
NO
Move the **Movie** column next to the **Folder** column for easier matching
Fixes: #5075
=> Move the Movie column next to the Folder column for easier matching

README.md
=> it's 2021 now [skip ci]

src/NzbDrone.Core.Test/ParserTests/EditionParserFixture.cs, src/NzbDrone.Core/Parser/Parser.cs
Closes #5716
NO
- [] Translation Keys-N/A
- [] Wiki Updates-N/A
* Fixes #5716
=> Fixed: Parse 'Assembly Cut' as an Edition

src/NzbDrone.Core/Validation/RuleBuilderExtensions.cs
Correct an instance of sonarr in one of the validation error output examples
=> Correct an instance of sonarr in one of the validation error output examples

frontend/src/MovieFile/Editor/MovieFileEditorRow.js
=> Add tooltips to the icons in the Files tab

.github/ISSUE_TEMPLATE/bug_report.md, .github/stale.yml, .github/support.yml
git
New Template uses hidden html for the info needed
Edit
Preview
=> .git updates for labels [skip ci]

src/NzbDrone.Core/Localization/Core/en.json
=> New: Renamed Quick Import to Move Automatically

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs, src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs, src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentSettings.cs, src/NzbDrone.Core/MediaFiles/DiskScanService.cs
NO
tidy up some missed sonarr refs
none
=> fix sonarresque references

src/NzbDrone.Core/Localization/Core/en.json
NO
movie -> release
-  Tests
-  Wiki Updates
https://discord.com/channels/264387956343570434/264388019585286144/805216896630521856
=> Fix: Correct wording for Blacklist Help Text

src/NzbDrone.Core/Movies/MovieRepository.cs
NO
Title
90 from current logic + 10 from new logic
=> New Improve Discover Recommendations

frontend/src/AddMovie/AddNewMovie/AddNewMovieSearchResultConnector.js, frontend/src/Store/Actions/addMovieActions.js
Fix status on search to properly show missing instead of a queue status
Fix for monitor not being set to true when adding from search
NO
=> Fix status on search to properly show missing instead of a queue status

src/NzbDrone.Core.Test/Files/Indexers/TorrentRss/AwesomeHD.xml, src/NzbDrone.Core/Datastore/Migration/190_update_awesome_hd_link.cs, src/NzbDrone.Core/Indexers/AwesomeHD/AwesomeHDSettings.cs
Yes 
190
-  Translation Keys-N/A
- Wiki Updates-N/A
https://discord.com/channels/264387956343570434/264387956343570434/804403947900895282
URL updated 2021-01-27
* Fixes #XXXX
=> Fixed: Awesome HD website link updated

.github/ISSUE_TEMPLATE/feature_request.md
=> update FR template [skip ci]

frontend/src/Utilities/createAjaxRequest.js
=> Fixed: Settings fields being altered during save

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs, src/NzbDrone.Core/Parser/QualityParser.cs
NO
See GHI
- Translation Keys-N/A
-  Wiki Updates-N/A
* Fixes #5639
=> Fix 4k detection

azure-pipelines.yml, src/NzbDrone.Host/Radarr.Host.csproj, src/NzbDrone.Integration.Test/Radarr.Integration.Test.csproj
=> Bump to .net to 5.0.3

src/Radarr.Api.V3/swagger.json
=> Fix: added missing movie RootFolderPath in swagger.json

frontend/src/Store/Actions/historyActions.js, frontend/src/Store/Actions/movieHistoryActions.js, src/Radarr.Api.V3/History/HistoryModule.cs
=> Fix mark failed

src/NzbDrone.Core/Localization/Core/en.json
NO
Small grammar mistake correction. I'm sorry to be bothering you haha
_none_
=> Updates typo from it's to its

src/NzbDrone.Core/Notifications/Discord/Discord.cs
NO
No other instances of .com in the backend.
-  Tests-N/A
-  Translation Keys-N/a
-  Wiki Updates-N/a
Fixes: #5975
=> Fixed: TMDB link in discord notifcation from .com to .org

frontend/src/Store/Actions/appActions.js
NO
Fix to linting so frontend build runs
=> Linting Fix

src/NzbDrone.Common.Test/TPLTests/RateLimitServiceFixture.cs, src/NzbDrone.Common/Http/HttpClient.cs, src/NzbDrone.Common/Http/HttpRequest.cs, src/NzbDrone.Common/TPL/RateLimitService.cs, src/NzbDrone.Core/Download/TorrentClientBase.cs, src/NzbDrone.Core/Download/UsenetClientBase.cs, src/NzbDrone.Core/Indexers/HttpIndexerBase.cs
Sonarr Pull
Pull commit:
Generalized RateLimit logic to all indexers based on indexer id
Issues Fixed or Closed by this PR
Fixes #5891
=> Pull Sonarr commit 'Generalized RateLimit logic to all indexers based on indexer id'

src/NzbDrone.Core/ImportLists/TMDb/Company/TMDbCompanyImport.cs, src/NzbDrone.Core/ImportLists/TMDb/Company/TMDbCompanyParser.cs, src/NzbDrone.Core/ImportLists/TMDb/Company/TMDbCompanyRequestGenerator.cs, src/NzbDrone.Core/ImportLists/TMDb/Company/TMDbCompanySettings.cs, src/NzbDrone.Core/ImportLists/TMDb/User/TMDbUserRequestGenerator.cs
NO
Allows for import of films from a TMDB company
* Fixes #6023 
* Fixes #5490
=> New: Import films from TMDb by company & Pagination work on other TMDb lists

src/NzbDrone.Core/ImportLists/TMDb/List/TMDbListParser.cs, src/NzbDrone.Core/ImportLists/TMDb/List/TMDbListRequestGenerator.cs, src/NzbDrone.Core/ImportLists/TMDb/TMDBResources.cs
NO
Users TMDb v4 API for lists and incorporates in pagination
=> New: TMDb Lists using V4 api

src/NzbDrone.Common.Test/Http/HttpClientFixture.cs, src/NzbDrone.Common/Http/HttpClient.cs, src/NzbDrone.Common/Http/HttpRequest.cs, src/NzbDrone.Common/Http/HttpRequestBuilder.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV1.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs
NO
-  Translation Keys-N/A
-  Wiki Updates-N/A
* Fixes #6076
=> Fixed: Qbittorrent api errors when only one of two seed criteria was configured

src/NzbDrone.Core.Test/HealthCheck/Checks/MonoNotNetCoreCheckFixture.cs, src/NzbDrone.Core/HealthCheck/Checks/MonoNotNetCoreCheck.cs
NO
Stop suppressing warning to migrate to .net core on FreeBSD and Synology ARM devices
=> Prompt upgrade to .net version on DSM and FreeBSD

src/Radarr.Api.V3/swagger.json
NO
/rootfolder is missing in the current API docs / swagger file
* Fixes #6087
=> added /rootfolder to swagger.json

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs, src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs
[common]
NO
-  Translation Keys
-  Wiki Updates
* Fixes #XXXX
=> Fixed: Cleanse Notifiarr APIKey from logs

src/NzbDrone.Core.Test/HealthCheck/Checks/DownloadClientRootFolderCheckFixture.cs, src/NzbDrone.Core/HealthCheck/Checks/DownloadClientRootFolderCheck.cs, src/NzbDrone.Core/Localization/Core/en.json
NO
Add a warning health check for downloading to a root path
=> New: Health Check for Downloads to Root Folder [common]

frontend/src/Movie/Delete/DeleteMovieModalContent.js, src/NzbDrone.Core/Localization/Core/en.json
NO
Shows the sizeOnDisk when deleting a movie file. 
* Fixes #5959
=> Fixed: Show size on disk when deleting movies

frontend/src/Store/Actions/Settings/notifications.js
NO
Sonarr Pull "Fixed: Some connection settings being invisibly enabled on creation"
* Fixes #6158
=> Fixed: Some connection settings being invisibly enabled on creation

src/NzbDrone.Common/Instrumentation/GlobalExceptionHandlers.cs, src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs, src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
Pull Commit: 
Sentry logging exceptions and some trace logging
* Fixes #5998
=> Pull Sonarr commit 'Sentry logging exceptions and some trace logging'

azure-pipelines.yml, package.json, src/Directory.Build.props, src/NzbDrone.Host/Radarr.Host.csproj, src/NzbDrone.Integration.Test/Radarr.Integration.Test.csproj, yarn.lock
NO
Bump to dotnet 5.0.5 - hopefully will fix the sporadic build issues
=> bump to Dotnet 5.0.5

frontend/src/AddMovie/AddNewMovie/AddNewMovieSearchResult.css, frontend/src/AddMovie/AddNewMovie/AddNewMovieSearchResult.js
NO
Added to be able to easily see which are shorts or more of a mini series listed as movies (5m, 30m, etc) quickly
=> Add certification and runtime to search results

src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs
closes #6209
(cherrypicked from sonarr 8d2d9078ff8f6daf50aef2dded3f96dae93252cc)
NO
* Fixes #XXXX
=> Update indexer category help text

src/NzbDrone.Core.Test/DecisionEngineTests/UpgradeDiskSpecificationFixture.cs, src/NzbDrone.Core/DecisionEngine/Specifications/UpgradableSpecification.cs
(cherry picked from commit 5114c75cbbe0269a0bbc0a72af592778b18c200c)
NO
Sonarr Pull
* Fixes #6174
=> Pull Sonarr commit 'Fixed: Incorrectly grabbing revision downgrades'

src/NzbDrone.Core/Indexers/RssParser.cs
(cherry picked from commit 8175f19442273e13517b2d507e7a4c33587f1b15)
* Fixes #6212
=> Sonarr pull commit 'Fixed: Parsing RSS with null values'

src/NzbDrone.Core/Notifications/Xbmc/XbmcJsonApiProxy.cs, src/NzbDrone.Core/Notifications/Xbmc/XbmcSettings.cs
(cherry picked from commit 199b126a468b95a4e11e9dbae63dfab9a380147d)
Sonarr commit changes some elements of  'src/NzbDrone.Core/Notifications/Xbmc/HttpApiProvider.cs' - we no longer have this file so changes there have not been migrated over
* Fixes #6208
=> Pull Sonarr Commit 'New: Adds SSL option to Kodi connections'

src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs
=> New: ISO 8601 Date in log files

src/Directory.Build.props, src/NuGet.config
NO
Don't let coverlet copy crappy dependencies
* Fixes random build failures
=> Try to fix flaky tests

frontend/src/InteractiveSearch/InteractiveSearchContent.js, frontend/src/InteractiveSearch/InteractiveSearchRow.js
=> Move the warning icon and download icon next to the release so it is never out of viewport

src/NzbDrone.Api/Queue/QueueActionModule.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/Blackhole/TorrentBlackholeFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/Blackhole/UsenetBlackholeFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/NzbgetTests/NzbgetFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/PneumaticProviderFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/SabnzbdTests/SabnzbdFixture.cs, src/NzbDrone.Core/Download/Clients/Blackhole/TorrentBlackhole.cs, src/NzbDrone.Core/Download/Clients/Blackhole/UsenetBlackhole.cs, src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs, src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs, src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs, src/NzbDrone.Core/Download/Clients/Flood/Flood.cs, src/NzbDrone.Core/Download/Clients/Hadouken/Hadouken.cs, src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortex.cs, src/NzbDrone.Core/Download/Clients/Nzbget/Nzbget.cs, src/NzbDrone.Core/Download/Clients/Pneumatic/Pneumatic.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs, src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs, src/NzbDrone.Core/Download/Clients/Vuze/Vuze.cs, src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs, src/NzbDrone.Core/Download/Clients/uTorrent/UTorrent.cs, src/NzbDrone.Core/Download/DownloadClientBase.cs, src/NzbDrone.Core/Download/DownloadEventHub.cs, src/NzbDrone.Core/Download/IDownloadClient.cs, src/Radarr.Api.V3/Queue/QueueActionModule.cs
NO
Pulls two fixes related to SABnzbd completed download handling from Sonarr
* Fixes #6198 
* Fixes #6207
=> Pull Sonarr Completed Download from SABnzbd

.github/support.yml
=> fix bot discord link [skip ci]

azure-pipelines.yml, src/NzbDrone.Core/Authentication/UserService.cs, src/NzbDrone.Core/Configuration/ConfigFileProvider.cs, src/NzbDrone.Integration.Test/ApiTests/MovieEditorFixture.cs, src/NzbDrone.Integration.Test/IntegrationTest.cs, src/NzbDrone.Integration.Test/IntegrationTestBase.cs
NO
Also re-enable fail on BSD fail
=> Fix more flaky integration tests

src/NzbDrone.Core/HealthCheck/Checks/DownloadClientRootFolderCheck.cs
NO
Updated logic as per Markus want on the pending PR [https://github.com/Sonarr/Sonarr/pull/4438](https://github.com/Sonarr/Sonarr/pull/4438)
=> Improved logic for root folder downloading health check

frontend/src/Settings/Profiles/Delay/EditDelayProfileModalContent.js, src/NzbDrone.Api/Profiles/Delay/DelayProfileResource.cs, src/NzbDrone.Core.Test/DecisionEngineTests/RssSync/DelaySpecificationFixture.cs, src/NzbDrone.Core/Datastore/Migration/194_add_bypass_to_delay_profile.cs, src/NzbDrone.Core/DecisionEngine/Specifications/RssSync/DelaySpecification.cs, src/NzbDrone.Core/Localization/Core/en.json, src/NzbDrone.Core/Profiles/Delay/DelayProfile.cs, src/Radarr.Api.V3/Profiles/Delay/DelayProfileResource.cs
(cherry picked from commit d668e923af83ab7f1589d947fec9f40a3919e0b8)
Database Migration 194
* Fixes #5999
=> Pull Sonarr commit 'New: Allow user to choose whether delay profile should apply to release of the highest enabled quality'

src/NzbDrone.Core/ImportLists/TMDb/Keyword/TMDbKeywordImport.cs, src/NzbDrone.Core/ImportLists/TMDb/Keyword/TMDbKeywordParser.cs, src/NzbDrone.Core/ImportLists/TMDb/Keyword/TMDbKeywordRequestGenerator.cs, src/NzbDrone.Core/ImportLists/TMDb/Keyword/TMDbKeywordSettings.cs
NO
Adds support for TMDb keyword lists
* Fixes #6255
=> New: TMDb Keyword List support

frontend/src/Components/Link/Link.js, frontend/src/Components/Page/Header/PageHeader.js, frontend/src/Components/Table/VirtualTable.js, frontend/src/Components/withScrollPosition.js, frontend/src/Movie/Index/Overview/MovieIndexOverviews.js, frontend/src/Movie/Index/Posters/MovieIndexPosters.js, frontend/src/Movie/Index/Table/MovieIndexTable.js
(cherry picked from commit 1bc52d0138c7bcb94ffce31ec05f675387612a62)
NO
Restores scroll position on back/logo link
* Fixes #6033
=> Fixed: restoring scroll position when going back to index page

src/NzbDrone.Core/Notifications/NotificationBase.cs, src/NzbDrone.Core/Notifications/Telegram/Telegram.cs
NO
New feature. Add Upgraded Movie support to Telegram Notifications
=> New: Telegram Notification - Add Upgrade Movie Support

src/NzbDrone.Core/Notifications/Webhook/Webhook.cs, src/NzbDrone.Core/Notifications/Webhook/WebhookMovie.cs, src/NzbDrone.Core/Notifications/Webhook/WebhookMovieFile.cs
NO
Add missing properties to Connection Webhook like Indexer Flags and Year (already in another connectors)
=> New: Add missing properties to Connection Webhook

frontend/src/System/Tasks/Queued/QueuedTaskRow.js
(cherry picked from commit c3837c9f7b50534e3eafe1d9fbaf360fee4588b7)
###Description
Converts frontend for User Agent on tasks list to Ternary 
####
Fixes: #6334
=> Pull Sonarr Commit "Fix ESLint"

src/NzbDrone.Core/Download/DownloadClientInfo.cs, src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs, src/NzbDrone.Core/Parser/ParsingService.cs
NO
1st commit fixes a null reference exception in the downloading to root folder health check caused by RuTorrent not returning any paths
2nd commit fixes a null reference exception for multi language releases when a movie could not be mapped
* Fixes Null Reference error in DownloadClientRootFolderCheck
* Fixes Null Reference error in Parsing Service caused by unmapped movies and multi language releases
=> Fixes for 3.2.1

src/NzbDrone.Core/Indexers/FileList/FileListSettings.cs, src/NzbDrone.Core/Indexers/HDBits/HDBitsSettings.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs, src/NzbDrone.Core/Indexers/Rarbg/RarbgSettings.cs
NO
Indexer categories are no longer advanced as per Sonarr.
=> New: Indexer Categories no longer an advanced option

src/NzbDrone.Core/Localization/Core/en.json
NO
Text as per sonarr pull 
* Fixes #6343
=> Fixed: Clarify delay profile bypass only applies to preferred protocol

src/NzbDrone.Core/Localization/Core/en.json
NO
Renames TimeLeft column to Time Left as per Sonarr Pull linked below
* Fixes #6406
=> New: Activity Queue: Rename Timeleft column to Time Left

.github/ISSUE_TEMPLATE/bug_report.md
=> add wiki link to bug template [skip ci] [common]

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/stale.yml
- stops stale bot from marking feature requests from label change
- enhances bug report template
-fixes FR label
=> git fixes [skip ci]

src/NzbDrone.Core/Localization/Core/en.json
NO
typo fix
- Tests
- Translation Keys
- Wiki Updates
* Fixes #XXXX
=> Fixed: Bad Translation

src/NzbDrone.Core/Datastore/Migration/196_legacy_mediainfo_hdr.cs
YES - 196
title
-  Tests
-  Translation Keys
-  Wiki Updates
* Closes #4132
=> Fixed: Migrate Legacy MediaInfo HDR token to VideoDynamicRange

frontend/src/Settings/MediaManagement/Naming/NamingModal.js
[common]
NO
- clarify clean title example
- Fix quality example (assumes default name)
- Various other enhancements
* Fixes Discord https://discord.com/channels/264387956343570434/264388019585286144/857824082636046346
Disclaimer: mobile commit
=> Fixed: Corrected Naming Examples

.github/workflows/azuresync.yml
=> fix concurrency so runs don't cancel [skip ci]

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs, src/NzbDrone.Core/Parser/QualityParser.cs
NO
fixes parsing of web releases  & refactors the regex
- N/A Translation Keys
- N/A Wiki Updates
* Fixes #6371
=> Web parsing fixes

src/NzbDrone.Core/Localization/Core/en.json
NO
This bugs me every time I see it, enough to make a PR for it :D
=> Fix grammar mistake in English message

src/NzbDrone.Core/Notifications/Notifiarr/Notifiarr.cs
ref https://github.com/Sonarr/Sonarr/commit/5938c38bc3a76d1f1e105fb54d5d7f59aa207278
NO
Fix the level
- Tests
* Fixes untracked issue
=> Fixed: Notifiarr Health Issue Level [common]

frontend/src/AddMovie/AddNewMovie/AddNewMovie.js, src/NzbDrone.Common/EnsureThat/EnsureStringExtensions.cs
NO
title
-  Tests
* Fixes #XXXX
=> fixed grammar issues

src/Radarr.Api.V3/swagger.json
NO
- Fixes an incorrect variable name (movieFiles -> moveFiles)
- Improves the description of the `/queue/grab` endpoint.
N/A
N/A
N/A
=> Minor swagger docs fixes & improvements

src/Radarr.Api.V3/ProviderResource.cs
NO
Fix Supported-XXXX links
-  Tests
* Fixes #XXXX
=> Fixed: Provider Wiki Links (supported-X => supported#X)

src/Radarr.Api.V3/swagger.json
NO
This will fix the docs to show the correct image response.
N/A
=> Update image swagger docs to represent the API correctly

frontend/src/AddMovie/ImportMovie/SelectFolder/ImportMovieSelectFolder.css, frontend/src/AddMovie/ImportMovie/SelectFolder/ImportMovieSelectFolder.js, src/NzbDrone.Core/Localization/Core/en.json
(cherry picked from commit 6596d0b4dad7be4e3d974f723b1a19d9bbfdff1f)
NO
Shows error on import Movie if adding root folder fails (as per sonarr commit)
* Fixes #6501
=> Fixed: Show error if adding root folder fails

src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs
NO
Fixes misleading help text
- N/A Tests
- N/A Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- N/A [Wiki Updates](https://wiki.servarr.com)
* Fixes #XXXX
=> Fixed: Corrected Indexer Category Help Text

.github/ISSUE_TEMPLATE/bug_report.yml
=> update bug report [skip ci] [common]

src/NzbDrone.Core/Queue/QueueService.cs
(cherry picked from commit 6b84da614bd6d919e04c58babde6911916f99e5b)
NO
Makes download unique per client - Sonarr Pull
* Fixes #6573
=> Fixed: Queue conflicts with the same download in multiple clients

frontend/src/MovieFile/Editor/MovieFileEditorRow.css, frontend/src/MovieFile/Editor/MovieFileEditorRow.js, frontend/src/MovieFile/Editor/MovieFileEditorTableContent.js
(cherry picked from commit 30aa5f9070bc9611bb9459d9d96bf293c971f891)
* Fixes #6662
=> New: Release group column on movie details files tab

src/NzbDrone.Common/Extensions/PathExtensions.cs, src/NzbDrone.Host/Bootstrap.cs, src/NzbDrone.Host/Startup.cs
NO
Explicitly configure persisting keys to disk to ensure forms login works across restarts
* Fixes issue reported on discord re radarr spontaneous logouts
* Will fix https://github.com/Prowlarr/Prowlarr/issues/409 when pulled
=> Fixed: Forms login persists across restarts in docker

src/NzbDrone.Core/Download/Clients/Aria2/Aria2Settings.cs
closes #6709
(cherry picked from commit 44a160fa067940770525312063ce7d749f6fd212)
NO
* Fixes #XXXX
=> Clarified Aria2 RPC Path field.

src/NzbDrone.Core.Test/IndexerSearchTests/ReleaseSearchServiceFixture.cs, src/NzbDrone.Core/IndexerSearch/MoviesSearchService.cs, src/NzbDrone.Core/IndexerSearch/ReleaseSearchService.cs, src/Radarr.Api.V3/Indexers/ReleaseController.cs
NO
Renames NzbSearchService to ReleaseSearchService, pulled from Sonarr.
* Fixes #6640
=> Pull Sonarr Commit 'Rename NzbSearchService to ReleaseSearchService'

src/NzbDrone.Core/Blocklisting/BlocklistService.cs
NO
Fixes missing languages on block for blocklist service. 
* Partially addresses #6730 - the other element has come from upstream and needs further discussion
=> Fixed: Blocklist error on blocklisting release

src/Radarr.Api.V3/Queue/QueueController.cs
(cherry picked from commit d11c691a7389d8984ddcbbd299d3192690719a1a)
NO
- Tests
Fixes #6730
Closes #6732
=> Fixed: Only blocklist pending releases when option is checked

src/NzbDrone.Core/MediaFiles/MovieImport/Specifications/NotMultiPartSpecification.cs
NO
Complete sentence for multi-part release reject reason.
=> Complete reject reason for multi-part

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> Update Bug Report Template [skip ci] 

src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs, src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentProxy.cs, src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentTorrent.cs, src/NzbDrone.Core/Download/DownloadSeedConfigProvider.cs, src/NzbDrone.Core/Indexers/SeedConfigProvider.cs
New: Removing rtorrent downloads when seeding criteria have been met
Fixes: #6320 
Fixes: #5219
=> New: Removing rtorrent downloads when seeding criteria have been met

src/NzbDrone.Core.Test/DecisionEngineTests/PrioritizeDownloadDecisionFixture.cs, src/NzbDrone.Core.Test/Download/DownloadApprovedReportsTests/DownloadApprovedFixture.cs, src/NzbDrone.Core.Test/Download/Pending/PendingReleaseServiceTests/RemovePendingFixture.cs, src/NzbDrone.Core.Test/Download/TrackedDownloads/TrackedDownloadServiceFixture.cs, src/NzbDrone.Core.Test/MediaFiles/MovieImport/ImportDecisionMakerFixture.cs, src/NzbDrone.Core.Test/MovieTests/MovieServiceTests/FindByTitleFixture.cs, src/NzbDrone.Core.Test/ParserTests/HashedReleaseFixture.cs, src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs, src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/AugmentersTests/AugmentMovieInfoFixture.cs, src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/GetMovieFixture.cs, src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/MapFixture.cs, src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs, src/NzbDrone.Core/CustomFormats/CustomFormatCalculationService.cs, src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs, src/NzbDrone.Core/Download/Pending/PendingReleaseService.cs, src/NzbDrone.Core/ImportLists/RSSImport/RSSImportParser.cs, src/NzbDrone.Core/MediaFiles/MovieImport/Manual/ManualImportService.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/Movies/MovieService.cs, src/NzbDrone.Core/Parser/Augmenters/AugmentWithReleaseInfo.cs, src/NzbDrone.Core/Parser/Model/ParsedMovieInfo.cs, src/NzbDrone.Core/Parser/Parser.cs, src/NzbDrone.Core/Parser/ParsingService.cs, src/NzbDrone.Core/Parser/SceneChecker.cs, src/NzbDrone.Core/Qualities/Quality.cs, src/NzbDrone.Integration.Test/ApiTests/ReleaseFixture.cs, src/Radarr.Api.V3/Indexers/ReleaseResource.cs
NO
Support parsing of releases with 'AKA'
Fixes #3748
=> New: Support AKA release titles

README.md
=> readme updates [skip ci]

src/NzbDrone.Core/Localization/Core/pt_BR.json
Translations update from [Servarr Weblate](https://translate.servarr.com/projects/servarr/radarr/)
for Servarr/Radarr.
Current translation status:
=> Translations update from Servarr Weblate

azure-pipelines.yml, build.sh, src/Directory.Build.props, src/NzbDrone.Common/Radarr.Common.csproj, src/NzbDrone.Core.Test/Radarr.Core.Test.csproj, src/NzbDrone.Core/Radarr.Core.csproj, src/NzbDrone.Mono.Test/Radarr.Mono.Test.csproj, src/NzbDrone.Mono/Radarr.Mono.csproj
(cherry picked from commit 4ce405728a3ae32c8d0282e8e2b758084e8e5864)
NO
Add osx-arm64 and linux-musl-arm builds
* Fixes #6754
=> New: Add osx-arm64 and linux-musl-arm builds

frontend/src/Store/Actions/queueActions.js
NO
Title
- Tests
* support issues
=> New: Display Unknown Items in Activity Queue by Default

src/NzbDrone.Mono.Test/Radarr.Mono.Test.csproj, src/NzbDrone.Mono/Radarr.Mono.csproj
(cherry picked from commit 9e7af8369e165c19a2f181071e63bef6961cd64e)
NO
* Fixes #XXXX
=> Fixed: Support older glibc in libMonoPosixHelper

src/NzbDrone.Host/Bootstrap.cs
common commit
NO
* Fixes #XXXX
=> fix erroneous logging for windows service on non-windows

src/NzbDrone.Common.Test/Http/HttpClientFixture.cs, src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs, src/NzbDrone.Core.Test/Framework/CoreTest.cs, src/NzbDrone.Core.Test/UpdateTests/UpdatePackageProviderFixture.cs
NO
Don't buffer file downloads
* Fixes issue on discord
=> Don't buffer file downloads

src/NzbDrone.Core/Localization/Core/en.json
closes #6834
NO
reword
- Tests
* Fixes #XXXX
=> Better wording of MissingFromDisk

src/NzbDrone.Host/Startup.cs
NO
When an API request is recieved that cannot be deserialized to the correct resource we return 400 response, but log no reasons behind it.
```
[Trace] Http: Req: 44 [POST] /api/v3/movie (from ::1)
[Trace] Http: Res: 44 [POST] /api/v3/movie: 400.BadRequest (47 ms)
[Debug] Api: [POST] /api/v3/movie: 400.BadRequest (47 ms)
```
This adds logging for model validation errors
```
[Trace] Http: Req: 44 [POST] /api/v3/movie (from ::1)
[Trace] Http: Req: 54 [POST] /api/v3/movie (from ::1)
[Error] Radarr.Api.V3.Movies.MovieController.AddMovie (Radarr.Api.V3): {
"$.minimumAvailability": [
"The JSON value could not be converted to NzbDrone.Core.Movies.MovieStatusType. Path: $.minimumAvailability | LineNumber: 14 | BytePositionInLine: 34."
]
}
[Trace] Http: Res: 54 [POST] /api/v3/movie: …
```
=> New: Additional logging for InvalidModel BadRequest API calls

src/NzbDrone.Core.Test/HealthCheck/HealthCheckServiceFixture.cs, src/NzbDrone.Core/HealthCheck/HealthCheckService.cs, src/NzbDrone.Core/HealthCheck/ServerSideNotificationService.cs
NO
Add's Server side pushable notifications
(cherry picked from commit f5f0dd6fae5bc9f308506d56be42ac9a4be908e7)
common commit
Closes #5393
=> New: Support server notifications

frontend/src/Components/Form/DownloadClientSelectInputConnector.js, frontend/src/Components/Form/FormInputGroup.js, frontend/src/Helpers/Props/inputTypes.js, frontend/src/Settings/Indexers/Indexers/EditIndexerModalContent.js, src/NzbDrone.Core.Test/Download/DownloadClientProviderFixture.cs, src/NzbDrone.Core.Test/Download/DownloadServiceFixture.cs, src/NzbDrone.Core/Datastore/BasicRepository.cs, src/NzbDrone.Core/Datastore/Migration/205_download_client_per_indexer.cs, src/NzbDrone.Core/Download/DownloadClientProvider.cs, src/NzbDrone.Core/Download/DownloadService.cs, src/NzbDrone.Core/Indexers/IndexerDefinition.cs, src/NzbDrone.Core/Localization/Core/en.json, src/NzbDrone.Core/ThingiProvider/IProviderFactory.cs, src/NzbDrone.Core/ThingiProvider/ProviderFactory.cs, src/Radarr.Api.V3/Indexers/IndexerResource.cs
YES - 205 (DownloadClientId on Indexers)
Allow user to specify a particular client for an indexer
Fixes #2266
Fixes #1350
=> New: Link indexer to specific download client

frontend/src/Settings/Indexers/Options/IndexerOptions.js
NO
Prefer Indexer Flags menu item has a outdated link to documentation. This link has now been updated to what I think would be the right link. If someone can verify the new link, that would be great.
=> Fixed: Updated link to Indexer Flags

src/NzbDrone.Core/Indexers/FileList/FileListSettings.cs, src/NzbDrone.Core/Indexers/HDBits/HDBitsSettings.cs, src/NzbDrone.Core/Indexers/IPTorrents/IPTorrentsSettings.cs, src/NzbDrone.Core/Indexers/Nyaa/NyaaSettings.cs, src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornSettings.cs, src/NzbDrone.Core/Indexers/Rarbg/RarbgSettings.cs, src/NzbDrone.Core/Indexers/TorrentRss/TorrentRssIndexerSettings.cs, src/NzbDrone.Core/Indexers/Torznab/TorznabSettings.cs
=> Fixed: Update indexer flag help link

src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs, src/NzbDrone.Core/Organizer/FileNameBuilder.cs
NO
Will add later
* Fixes #XXXX
=> Fixed: Map DV Blu-ray to HDR10 compatibility

frontend/src/Settings/ImportLists/ImportListExclusions/ImportListExclusions.js
Fix broken headers on List Exclusion table
=> Fix broken headers on List Exclusion table

src/NzbDrone.Core/Notifications/Email/Email.cs, src/NzbDrone.Core/Security/X509CertificateValidationService.cs
NO
Use user defined cert settings for Mailkits cert validation
* Fixes #6916
=> Fixed: Use general settings cert validation for email

src/NzbDrone.Common/Http/BasicNetworkCredential.cs, src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs, src/NzbDrone.Common/Http/HttpRequest.cs, src/NzbDrone.Common/Http/HttpRequestBuilder.cs, src/NzbDrone.Core/Download/Clients/Hadouken/HadoukenProxy.cs, src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetProxy.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV1.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs, src/NzbDrone.Core/Download/Clients/Transmission/TransmissionProxy.cs, src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentProxy.cs, src/NzbDrone.Core/Notifications/PushBullet/PushBulletProxy.cs, src/NzbDrone.Core/Notifications/Webhook/WebhookProxy.cs, src/NzbDrone.Core/Notifications/Xbmc/XbmcJsonApiProxy.cs
(cherry picked from commit 1e2d931f9aa0eeb844632b1f65795db891bd4c3b)
NO
Support for Digest Auth using our Http client
Fixes https://github.com/Radarr/Radarr/issues/4874
=> Support for digest auth with HttpRequests

frontend/src/AddMovie/AddNewMovie/AddNewMovieSearchResult.js
Add a width variable so all posters can be set the same
=> Add a width variable to posters on search page so everything is the same

src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentSettings.cs
NO
title
- Tests
* Fixes #XXXX
=> fixed sonarr ref in UTorrentSettings

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
Fixes RADARR-7HC
Fixes RADARR-V49
(cherry picked from commit 6f97ca9a55471386454457ca52b93733e18e85e4)
NO
- Tests
* Closes #6993
=> Fixed: Handle missing category when getting Qbittorrent download path

src/NzbDrone.Common/Cloud/RadarrCloudRequestBuilder.cs
NO
servarr.com -> radarr.video
* Fixes #XXXX
=> Update API URL

src/NzbDrone.Core/Localization/Core/en.json
(cherry picked from commit c7427f8df828733a81d83ea28393a18d10875769)
NO
Sonarr Pull Fix IPv4 spelling 
Fixes: #7053
=> Fixed: IPv4 instead of IP4

src/NzbDrone.Update/UpdateApp.cs
=> Fix nzbdrone reference

src/Radarr.Api.V3/swagger.json
NO
Updates swagger.json to use inCinemas not inCinema
* Fixes #7021
=> Fix swagger inCinema references

frontend/src/System/Backup/BackupRow.js, frontend/src/System/Backup/Backups.js, src/NzbDrone.Core/Backup/Backup.cs, src/NzbDrone.Core/Backup/BackupService.cs, src/Radarr.Api.V3/System/Backup/BackupController.cs, src/Radarr.Api.V3/System/Backup/BackupResource.cs
(cherry picked from commit 78aeda1a2cc217c367c5c3c6fd281c101b28413c)
NO
Sonarr Pull - Adds backup size to the backups table and API response
* Fixes #7054
=> New: Add backup size information

frontend/src/Settings/Indexers/Options/IndexerOptions.js
NO
Text box label not uniform throughout the indexer settings page. Changed capitalization.
Changed **Availability Delay** text box label from _Days_ to _days_ to match the style of the other labels throughout the page. For example, **RSS sync interval** and **Minimum age** settings both have lowercase labels.
* Fixes #XXXX
=> fixed text box not being uniform to others

src/NzbDrone.Core/Localization/Core/en.json
NO
Fixes translate for Removing items from the queue
=> Fixed: Removing multiple items from the queue wording

src/NzbDrone.Update/UpdateEngine/DetectExistingVersion.cs
NO
Fixes logging "Unknown" as version being upgraded from on non-Windows OS. 
* Fixes #7098
=> Fixed: Updater version number logging

src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrEnvironment.cs, src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrProxy.cs, src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrSettings.cs
Add Environment switch to Notifiarr connect
=> Add error handling to Notifiarr connect to reduce Sentry hits

src/NzbDrone.Common/Radarr.Common.csproj, src/NzbDrone.Core/Configuration/ConfigFileProvider.cs, src/NzbDrone.Core/Instrumentation/ReconfigureLogging.cs
(cherry picked from commit 8d856b2edb8bf46a2b516d5f7644ae3fa1151323)
NO
Support Syslog Support using configuration in config.xml as per implementation in Prowlarr
=> New: Added UDP syslog support

src/NzbDrone.Core/Parser/Parser.cs
NO
fixup 5834afe30b8a0f252d60a17cf71f0f41b17aeecc
* Fixes #XXXX
=> add 576 resolution back to simple title regex

src/NzbDrone.Core/Radarr.Core.csproj
NO
Update ffmpeg to 5.0.1
* Fixes #XXXX
=> FFMpeg 5.0.1

src/NzbDrone.Core/Datastore/PostgresOptions.cs, src/NzbDrone.Host/Bootstrap.cs
=> Make postgres integration tests actually use postgres

frontend/src/InteractiveSearch/InteractiveSearchContent.css, frontend/src/InteractiveSearch/InteractiveSearchContent.js
NO
Added padding to content in the search tab to maintain visual consistancy
=> Added padding to search tab to maintain visual consistancy

azure-pipelines.yml, build.sh, src/NzbDrone.Core.Test/UpdateTests/UpdatePackageProviderFixture.cs, src/NzbDrone.Core/Radarr.Core.csproj, src/NzbDrone.Mono.Test/Radarr.Mono.Test.csproj, src/NzbDrone.Mono/Radarr.Mono.csproj
NO
Add support for 32bit linux
* Fixes #XXXX
=> Add linux-x86 support

src/NzbDrone.Core.Test/Datastore/Migration/207_movie_metadataFixture.cs, src/NzbDrone.Core/Datastore/Migration/207_movie_metadata.cs
NO - fixes existing missed use case
Fixes movie existing in multiple lists for metadata migration
=> Fix metadata migration

src/NzbDrone.Core.Test/Datastore/Migration/207_movie_metadataFixture.cs, src/NzbDrone.Core/Datastore/Migration/207_movie_metadata.cs
NO
Ensures that when ListMovies are added to MovieMetadata we only distinct by TmdbId
=> Fix migration 207 distinct on tmdbid only for list movie insert

src/NzbDrone.Core/Download/CompletedDownloadService.cs
(cherry picked from commit 9183c6b84638e3654c3f90a80e560a06575606bb)
Sonarr pull, fixed importing file from UNC shared folder without job folder
* Fixes #7221
=> Fixed: Importing file from UNC shared folder without job folder

src/NzbDrone.Core.Test/Files/Indexers/Nyaa/Nyaa2021.xml, src/NzbDrone.Core.Test/IndexerTests/NyaaTests/NyaaFixture.cs, src/NzbDrone.Core/Indexers/EzrssTorrentRssParser.cs, src/NzbDrone.Core/Indexers/Nyaa/Nyaa.cs, src/NzbDrone.Core/Indexers/TorrentRssParser.cs
(cherry picked from commit 40ecdbc12de8b320a4d650aea65a36e8edea77d8)
NO
Pulls Bakers Nyaa updates
* Fixes #7189
=> New: Support for new Nyaa RSS Feed format

frontend/src/Activity/History/HistoryRow.js, frontend/src/Store/Actions/historyActions.js
(cherry picked from commit 581fb2cb3d47d62fe16b840081647056ec77043d)
Fixes #7159
NO
* Fixes #XXXX
=> New: Add optional Source Title column to history

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs, src/NzbDrone.Core/Parser/Parser.cs
=> New: Parse QxR Group r00t

src/NzbDrone.Core/CustomFormats/Specifications/ReleaseGroupSpecification.cs
NO
New: Release Group Custom Format
* Closes #7086
=> New: Release Group Custom Format

src/NzbDrone.Core/MediaFiles/MovieImport/Specifications/UpgradeSpecification.cs, src/Radarr.Api.V3/CustomFormats/CustomFormatController.cs
NO
* Fixes #4733
* Fixes #5811
=> Misc CF Improvements

src/NzbDrone.Core/ImportLists/Trakt/TraktSettingsBase.cs
NO
Added to trakt list helptext to clarify that it only applies to Popular Lists.
* Fixes #XXXX
=> Fixed: Clarified genre filtering helptext on Trakt lists

src/NzbDrone.Host/Bootstrap.cs
NO
Use Hostbuilder to build container without running host, and register PostgresOptions as IConfiguration in utility mode. 
Before
```
C:\Users\qstic\source\repos\Radarr\_output\net6.0>radarr.console.exe /u
[Info] Bootstrap: Starting Radarr - C:\Users\qstic\source\repos\Radarr\_output\net6.0\Radarr.Console.exe - Version 10.0.0.40666
[Fatal] ConsoleApp: EPIC FAIL!
[v10.0.0.40669] DryIoc.ContainerException: code: Error.UnableToResolveUnknownService;
message: Unable to resolve Microsoft.Extensions.Options.IOptions<NzbDrone.Core.Datastore.PostgresOptions> as parameter "postgresOptions" (IsSingletonOrDependencyOfSingleton)
```
After
```
C:\Users\qstic\source\repos\Radarr\_output\net6.0>radarr.console.exe /u
[Info] Bootstrap: Starting Radarr - …
```
=> Fixed: Register PostgresOptions when running in utility mode

src/NzbDrone.Common/Instrumentation/Extensions/SentryLoggerExtensions.cs, src/NzbDrone.Common/Instrumentation/NzbDroneFileTarget.cs, src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs, src/NzbDrone.Common/Radarr.Common.csproj, src/NzbDrone.Core/Download/CompletedDownloadService.cs, src/NzbDrone.Core/Instrumentation/ReconfigureLogging.cs, src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs, src/NzbDrone.Core/Radarr.Core.csproj, src/NzbDrone.Test.Common/Radarr.Test.Common.csproj, src/NzbDrone.Update/Radarr.Update.csproj, src/NzbDrone.Windows/Radarr.Windows.csproj, src/Radarr.Api.V3/Radarr.Api.V3.csproj, src/Radarr.Http/Radarr.Http.csproj
NO
Updates NLog Version in an attempt to fix syslog not logging
=> Update NLog Version

frontend/src/AddMovie/ImportMovie/Import/SelectMovie/ImportMovieSearchResult.css, frontend/src/AddMovie/ImportMovie/Import/SelectMovie/ImportMovieSearchResult.js
NO
adding a link to the movie on https://www.themoviedb.org in the import combobox movie search results
=> New: adding a link to the themoviedb in import combobox

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs, src/NzbDrone.Core/Parser/QualityParser.cs
NO
* Fixes Discord Report
* Closes #7355
=> Fixed: Improved parsing WebDL Releases

src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrProxy.cs
NO
- better http error messages
- handle 400 error
- better CF details
- also quiet sentry
- Tests
* Fixes #XXXX
=> Fixed: Notifiarr - Better HTTP Error Handling

src/NzbDrone.Core/Notifications/Discord/Discord.cs, src/NzbDrone.Core/Notifications/Discord/DiscordFieldType.cs
NO
title
- Tests
* Fixes #6733
=> New: (Discord) Include Custom Formats & Score On Grab

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs, src/NzbDrone.Core/Parser/Parser.cs
=> New: Parse Group HONE | Fixed: Parse Group ZØNEHD

src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrEnvironment.cs, src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrProxy.cs, src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrSettings.cs
NO - depreciated setting serves neither use nor harm
Site's proxy now handles environment selection
-  Tests
* Fixes #XXXX
=> Fixed: Remove Notifiarr Environment Option

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs, src/NzbDrone.Core/Languages/Language.cs, src/NzbDrone.Core/Parser/IsoLanguages.cs, src/NzbDrone.Core/Parser/LanguageParser.cs
NO
Added support for Slovak language.
=> New: Add Slovak Language - Lang 35

src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/EditionTagsFixture.cs, src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/IdFixture.cs, src/NzbDrone.Core/Organizer/FileNameBuilder.cs
NO
Make Imdb and Edition tags conditional on value when used in Plex naming format
* Fixes #7483
=> Edition tag

src/NzbDrone.Core/Notifications/Ntfy/Ntfy.cs, src/NzbDrone.Core/Notifications/Ntfy/NtfyException.cs, src/NzbDrone.Core/Notifications/Ntfy/NtfyPriority.cs, src/NzbDrone.Core/Notifications/Ntfy/NtfyProxy.cs, src/NzbDrone.Core/Notifications/Ntfy/NtfySettings.cs
NO
This adds ntfy.sh as a notification provider.
It allows public server or private instance.
* Fixes #7434
=> Added: Ntfy provider for notifications.

src/NzbDrone.Core.Test/Extras/ExtraServiceFixture.cs, src/NzbDrone.Core.Test/Extras/Others/OtherExtraServiceFixture.cs, src/NzbDrone.Core.Test/Extras/Subtitles/SubtitleServiceFixture.cs, src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs, src/NzbDrone.Core/Datastore/Migration/214_add_language_tags_to_subtitle_files.cs, src/NzbDrone.Core/Extras/ExistingExtraFileService.cs, src/NzbDrone.Core/Extras/ExtraService.cs, src/NzbDrone.Core/Extras/Files/ExtraFileManager.cs, src/NzbDrone.Core/Extras/Metadata/MetadataService.cs, src/NzbDrone.Core/Extras/Others/OtherExtraService.cs, src/NzbDrone.Core/Extras/Subtitles/SubtitleFile.cs, src/NzbDrone.Core/Extras/Subtitles/SubtitleService.cs, src/NzbDrone.Core/Parser/LanguageParser.cs
NO
Better sub import logic 
* Fixes #7092 
* Fixes #7116 
* Fixes #7215 
* Fixes #7459 
* Fixes #4267
=> New: Import subtitles from sub folders

src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs, src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadataSettings.cs
NO
Adds option for NFO files to include the collection name within the NFO file
* Fixes #7571
=> New: Setting to add Collection to NFO files

src/NzbDrone.Core/CustomFormats/Specifications/RegexSpecificationBase.cs
=> New: (UI) Indicate Custom Formats are Case Insensitive

.github/ISSUE_TEMPLATE/bug_report.yml
=> Update Bug Report Template [skip ci] [common]

.github/ISSUE_TEMPLATE/bug_report.yml
[skip ci] [common]
NO
Adds a field for database in case there is a PG/Sqlite specific issue
=> Update Bug Report Template

src/NzbDrone.Core.Test/Languages/LanguageFixture.cs, src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs, src/NzbDrone.Core/Languages/Language.cs, src/NzbDrone.Core/Parser/IsoLanguages.cs, src/NzbDrone.Core/Parser/LanguageParser.cs
NO
This PR adds Latvian language movie support to Radarr.
* Fixes #XXXX
=> New: Add Latvian language

src/NzbDrone.Core/Localization/Core/en.json
=> Fixed: Improve Quality Profile in-use helptext

frontend/src/Collection/Edit/EditCollectionModalContent.js, frontend/src/Settings/ImportLists/ImportLists/EditImportListModalContent.js
=> Fixed: Clarify Folder as Root Folder

src/NzbDrone.Core.Test/DecisionEngineTests/RepackSpecificationFixture.cs, src/NzbDrone.Core/DecisionEngine/Specifications/RepackSpecification.cs
(cherry picked from commit 04447d9d4db8cc3d54baf0a721f4430cf77908c4)
NO
see commit msg
* Fixes #6595
* Closes #7621
=> Fixed: Repack Preference Ignored

src/NzbDrone.Core/Indexers/Rarbg/RarbgParser.cs
based on Prowlarr 06a26b5c871b6d27105aa510d1431c941b695116
NO
- Tests
* Fixes #7625
=> Fixed: Improve RarBG Error Handling

.github/ISSUE_TEMPLATE/feature_request.yml
NO
Title
- Tests
* Fixes #XXXX
=> update feature request template

.github/ISSUE_TEMPLATE/bug_report.yml
Only OS had one
NO
Just adding trailing spaces to easy entry of environment on the bug template
=> Add trailing spaces to issue template

src/NzbDrone.Core/Datastore/DbFactory.cs
(cherry picked from commit 3e700b63c26b247fcac83428ba79e53c88f797ff)
NO
If Postgres is not up on startup then it will pause for 5 seconds and retry up to 3 times as per https://github.com/Prowlarr/Prowlarr/commit/3e700b63c26b247fcac83428ba79e53c88f797ff
* Fixes #7671
=> New: Retry Postgres connection 3 times (with 5 second sleep) on Startup

frontend/src/Calendar/Events/CalendarEvent.css, frontend/src/Calendar/Events/CalendarEvent.js, frontend/src/Calendar/Legend/Legend.js, frontend/src/Calendar/Legend/LegendConnector.js, frontend/src/Calendar/Legend/LegendIconItem.js, frontend/src/Calendar/Legend/LegendItem.css, frontend/src/Calendar/Legend/LegendItem.js, frontend/src/Calendar/Options/CalendarOptionsModalContent.js, frontend/src/Components/Icon.css, frontend/src/Components/Icon.js, frontend/src/Components/Label.css, frontend/src/Settings/Indexers/Restrictions/Restrictions.css, frontend/src/Settings/MediaManagement/Naming/NamingModal.css, frontend/src/Settings/Profiles/Quality/QualityProfileFormatItem.css, frontend/src/Store/Actions/calendarActions.js, frontend/src/Styles/Themes/dark.js, frontend/src/Styles/Themes/light.js, src/NzbDrone.Core/Localization/Core/en.json
NO
Fixup some UI Flashbangs, Color Impaired mode on Calendar and disabled label text
N/A
Fixes #6129
=> Zeus UI fix

src/NzbDrone.Core/Radarr.Core.csproj
=> Bump FFprobe

src/NzbDrone.Core/Instrumentation/DatabaseTarget.cs, src/NzbDrone.Test.Common/ExceptionVerification.cs
NO
Fixes 3/4 currently failing tests.
=> fixup: some tests for log files

src/NzbDrone.Host/Startup.cs
(cherry picked from commit 5400bce1295bdc4198d2cfe0b9258bbb7ccf0852)
NO
Reinstates the AppStartingEvent
* Fixes #7765
=> Publish ApplicationStartingEvent during startup

src/NzbDrone.Common/Instrumentation/Sentry/SentryCleanser.cs, src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs, src/NzbDrone.Common/Radarr.Common.csproj
Co-authored-by: Bruno Garcia <bruno@Brunos-MacBook-Pro.local>
(cherry picked from commit de3cb07c57d762084c983336aa01b761a8e4b74a)
NO
* Fixes #7790 
The following lines have been removed in Sonarr from "\src\NzbDrone.Common\Instrumentation\Sentry\SentryTarget.cs"; personally I am not sure about removing them so thoughts on this one would be good
```
o.SendDefaultPii = false;
o.Debug = false;
o.DiagnosticLevel = SentryLevel.Debug;
````
edit:
- SendDefaultPii defaults to false. 
- Debug being set to false (which is default) means DiagnosticLevel does nothing
=> Sentry SDK v3.23.1

src/NzbDrone.Core/Localization/Core/en.json, src/NzbDrone.Core/Parser/QualityParser.cs
=> Properly parse H.265 4k as 4k quality

src/NzbDrone.Core.Test/ParserTests/EditionParserFixture.cs, src/NzbDrone.Core/Parser/Parser.cs
NO
To make James Cameron happy.
* Fixes https://github.com/Radarr/Radarr/issues/1414#issuecomment-489077620
=> New: Parse Open Matte as Edition

frontend/src/Settings/Indexers/Indexers/EditIndexerModalContent.js, src/NzbDrone.Core/Localization/Core/en.json
(cherry picked from commit 396406b2174c4876057175e7537a4718eee2abca)
* Fixes #7953
=> New: Description for indexer RSS setting

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs, src/NzbDrone.Core/Parser/QualityParser.cs
NO
yet another cam name
* Fixes https://discord.com/channels/264387956343570434/264388019585286144/1062063297165271142
=> Fixed: Parse HDCAMRip as CAM

src/NzbDrone.Core.Test/DecisionEngineTests/UpgradeAllowedSpecificationFixture.cs, src/NzbDrone.Core.Test/Housekeeping/Housekeepers/CleanupQualityProfileFormatItemsFixture.cs, src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupQualityProfileFormatItems.cs, src/NzbDrone.Core/Profiles/ProfileFormatItem.cs, src/NzbDrone.Core/Profiles/ProfileRepository.cs, src/NzbDrone.Core/Profiles/ProfileService.cs
NO
Manually cherry picked from Sonarr commits:
- [2c004e1f9665763111fcd964b81338bdbe735865](https://github.com/Sonarr/Sonarr/commit/2c004e1f9665763111fcd964b81338bdbe735865)
- [4b4301a076488c595969921697d7002ca427c955](https://github.com/Sonarr/Sonarr/commit/4b4301a076488c595969921697d7002ca427c955)
- Closes #7975 
- Closes #7980 
- Closes #7981
=> Fixed: Unable to load UI if Quality Profiles contain removed Custom Format items

frontend/src/Components/Menu/FilterMenu.js, frontend/src/Components/Menu/ToolbarMenuButton.js
No
Fix the Filter button indicator. 
Indicator on Search Page:
Indicator on Collections page:
Indicator on History page:
Indicator on Movies page
Indicator on Discover page
- N/A
* Fixes #8024
=> Fix Filter Button being squished #8024

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs, src/NzbDrone.Core/Parser/Parser.cs
(cherry picked from commit 5ce8ea8985f880d4e68db852f04558a59461ae3d)
Sonarr Pull 
Fixes: #7898
=> New: Parse release group from VARYG releases with junk at the end

package.json, yarn.lock
=> Updated some JS dependencies

src/NzbDrone.Core/MediaFiles/MovieImport/Specifications/AlreadyImportedSpecification.cs
(cherry picked from commit 3f598ffa6fbec90ecdbb266de4b0fe7558fbbc30)
Sonarr Pull
* Fixes #7992
=> Fixed: UTC time sent to UI for already imported message

frontend/src/Settings/MediaManagement/Naming/NamingModal.css, frontend/src/Settings/MediaManagement/Naming/NamingOption.css, frontend/src/Styles/Themes/light.js
NO
Fixup of File Name Tokens view
- N/A
* Fixes #8001
=> fixup! File Name Tokens

frontend/src/Settings/Metadata/Options/MetadataOptions.js, src/NzbDrone.Core/MetadataSource/SkyHook/Resource/TMDbCountryCode.cs
NO
Adding Ireland as a valid certification country.
Same as https://github.com/Radarr/Radarr/pull/6651
Didn't create an issue, just made the PR
=> Add Ireland as a Certification Country

src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabFixture.cs, src/NzbDrone.Core.Test/IndexerTests/TorznabTests/TorznabFixture.cs, src/NzbDrone.Core/Indexers/Newznab/Newznab.cs, src/NzbDrone.Core/Indexers/Torznab/Torznab.cs
NO
Max of Default or Max and no more than 100
* Fixes #8096
=> New: Use Best PageSize for Newznab/Torznab

src/NzbDrone.Core/Notifications/Discord/Discord.cs
=> Implemented OnMovieAdded for Discord

src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs, src/NzbDrone.Core/ImportLists/HttpImportListBase.cs, src/NzbDrone.Core/ImportLists/Radarr/RadarrV3Proxy.cs, src/NzbDrone.Core/Indexers/HttpIndexerBase.cs, src/NzbDrone.Core/Indexers/Newznab/Newznab.cs, src/NzbDrone.Core/Indexers/Torznab/Torznab.cs
(cherry picked from commit e968919e63616e30cc401964bd51db8e9e0e26de)
Fixes #8152
Closes #8169 
NO
- Tests
* Fixes #XXXX
=> Fixed: Improve some request failure messaging

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs, src/NzbDrone.Core/Parser/LanguageParser.cs
=> Fixed: Parsing of RoDubbed releases as Romanian

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs, src/NzbDrone.Core/Notifications/Webhook/WebhookMovie.cs
NO
Adds Movie Overview to Custom Script and Webhook notifications
=> Add Overview to CustomScript and Webhook Notifications

frontend/src/DiscoverMovie/Overview/DiscoverMovieOverviewInfo.js
NO
Locks ratings for TMDB at 1 decimal place
- [x ] Tests
- [x ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [x ] [Wiki Updates](https://wiki.servarr.com)
* Fixes #8278
=> Locks to 1 decimal place instead of infinite

src/NzbDrone.Core/Parser/ParsingService.cs
NO
fix makes mapping by MovieTitles collection instead of PrimaryMovieTitle
movie search [Avatar (2009)](https://www.themoviedb.org/movie/19995-avatar)
Title retrieved from the indexer:
`Аватар (AKA Avatar)(2009)[США, Великобритания, фантастика, боевик, драма, приключения, BDRip 1080p] [Special Edition Re-release Cut] Dub (CEE)[Subs(Rus, Eng)][multi(Rus,Eng)][Original(Eng)]`
the movie is not mapped with an error:
`Failed to map movie, found title(s) Аватар (AKA Avatar), Аватар, Avatar, expected one of: Avatar, Avatar Edicion Coleccionista, Project 880465wtgsdtg, Avatar - Edição Estendida de Colecionador, Avatar - Collector's Extended Edition, Avatar: Extended Version, Avatar: An IMAX 3D Experience, Avatar 3D, James Cameron's Avatar, Avatar: Special Edition, 아바타, Аватар 3D, Avatar - Wersja …
=> fix: mapping by MovieTitles collection instead of PrimaryMovieTitle

src/NzbDrone.Core/Localization/Core/en.json
(cherry picked from commit 83a9d15ff8721c8effdc2c8055e37bfb757022d4)
NO
- Tests
* Closes #8327
=> New: More information on on why hardlinks should be used over copying

src/NzbDrone.Core/Movies/MovieMetadata.cs
NO
title
- [] Tests
* Fixes https://discord.com/channels/264387956343570434/633193129515810816/1095461201472921640
=> Fixed: Include Digital Only Releases for Recent Movie determination

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
NO
remove extra call outside of the try/catch
identified when differing Radarr and Sonarr Qbit
- [] Tests
* Fixes #XXXX
=> cleanup qbit share limit add

src/NzbDrone.Core.Test/NotificationTests/EmailTests/EmailSettingsValidatorFixture.cs, src/NzbDrone.Core/Notifications/Email/Email.cs, src/NzbDrone.Core/Notifications/Email/EmailSettings.cs
=> Rename `CC` to `Cc`

src/Radarr.Http/Frontend/Mappers/StaticResourceMapperBase.cs
=> Serve plain text files (eg. logs) as UTF-8

src/NzbDrone.Core/Notifications/Apprise/Apprise.cs, src/NzbDrone.Core/Notifications/Apprise/AppriseError.cs, src/NzbDrone.Core/Notifications/Apprise/AppriseException.cs, src/NzbDrone.Core/Notifications/Apprise/AppriseNotificationType.cs, src/NzbDrone.Core/Notifications/Apprise/ApprisePayload.cs, src/NzbDrone.Core/Notifications/Apprise/AppriseProxy.cs, src/NzbDrone.Core/Notifications/Apprise/AppriseSettings.cs
=> New: (Notifications) Add Apprise

src/NzbDrone.Core/Indexers/FileList/FileListSettings.cs
=> Fixed: (FileList) Use labels for category options

src/NzbDrone.Core/Notifications/Boxcar/Boxcar.cs, src/NzbDrone.Core/Notifications/Ntfy/Ntfy.cs, src/NzbDrone.Core/Notifications/PushBullet/PushBullet.cs
=> Fixed: (Notifications) Consistency in notification titles

src/NzbDrone.Common/Http/HttpRequestBuilder.cs, src/NzbDrone.Common/Http/TooManyRequestsException.cs, src/NzbDrone.Core.Test/IndexerTests/RarbgTests/RarbgFixture.cs, src/NzbDrone.Core/HealthCheck/Checks/RecyclingBinCheck.cs, src/NzbDrone.Core/Indexers/Exceptions/RequestLimitReachedException.cs, src/NzbDrone.Core/Indexers/HttpIndexerBase.cs, src/NzbDrone.Core/Indexers/Rarbg/Rarbg.cs, src/NzbDrone.Core/Indexers/Rarbg/RarbgParser.cs, src/NzbDrone.Core/Indexers/Rarbg/RarbgRequestGenerator.cs, src/NzbDrone.Core/Indexers/Rarbg/RarbgResponse.cs, src/NzbDrone.Core/Indexers/Rarbg/RarbgTokenProvider.cs, src/NzbDrone.Core/Localization/Core/en.json, src/NzbDrone.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs, src/NzbDrone.Core/MediaFiles/MovieImport/RecycleBinException.cs, src/NzbDrone.Core/MediaFiles/RecycleBinProvider.cs
NO
New: Report health error if Recycling Bin folder is not writable
(cherry picked from commit 8c50cd061e691914d9fcce119b9f838f1276950c)
New: Updated Rarbg request limits
(cherry picked from commit 47cf8e6430b7f7704ce2f1524fa9e3c8e6f9b47a)
Use BuildInfo.AppName for RARBG appId instead of hardcoded value
(cherry picked from commit 99c4f5b746bff6809c988f8b816e5135f5959ed7)
* Closes #8387
* Closes #8337
* Fixes #7700
* Fixes #8388
* Closes #8389
=> Sonarr Pulls

src/NzbDrone.Core/Download/FailedDownloadService.cs
(cherry picked from commit cf48bf304122bacc597de1d4d4429065d2358fa8)
NO
title
- Tests
* Fixes #8086
* Closes #8369
=> Fixed: Ensure first history item when marked as failed is the selected item

src/NzbDrone.Core/HealthCheck/Checks/DownloadClientRootFolderCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/ImportListRootFolderCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/ImportListStatusCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/MovieCollectionRootFolderCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs
=> Misc HealthCheck Cleanup and Sonarr Alignment

src/NzbDrone.Core/Datastore/Database.cs
NO
prowlarr cherrypicks to shutup show_version in console output
- [] Tests
* Fixes #XXXX
=> Fixed: (Database) Improve Version detection

frontend/src/Movie/Index/Overview/MovieIndexOverview.tsx, frontend/src/Movie/Index/Posters/MovieIndexPoster.tsx, frontend/src/Movie/Index/Table/MovieIndexRow.tsx
NO
various UI fixes regressed from https://github.com/Radarr/Radarr/commit/e0b91c6406f1587ac6e8aef6522b2fc495561245
- Fixed: Unable to search individual movies from Movie Index
- Fixed: Refresh on movie list refreshing all movies
- Fixed: Search Button Display on Movie Index
- [] Tests
* Fixes #8434
=> Various UI Regression Fixes

frontend/src/Movie/Index/Table/MovieIndexRow.tsx
NO
title
- [] Tests
* Fixes #8442
* Fixes regression from https://github.com/Radarr/Radarr/commit/e0b91c6406f1587ac6e8aef6522b2fc495561245
=> Fixed: Movie Status in Table View

src/NzbDrone.Core.Test/Languages/LanguageFixture.cs, src/NzbDrone.Core.Test/ParserTests/IsoLanguagesFixture.cs, src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs, src/NzbDrone.Core/Languages/Language.cs, src/NzbDrone.Core/Parser/IsoLanguages.cs, src/NzbDrone.Core/Parser/LanguageParser.cs
NO
Added a new language "Telugu" to filter releases.
Added a couple testcases.
* Fixes #8588
=> added new language "Telugu" for filtering releases and testcases.

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs, src/NzbDrone.Core/Parser/QualityParser.cs
NO
Added: Parsing MDVDR  --> https://predb.me/?search=MDVDR
Added: Parsing Multi Disk DVD releases
* Fixes https://github.com/Radarr/Radarr/issues/6928
=> Parse Multi Disk DVDs & MDVDR

frontend/src/Collection/CollectionItemConnector.js, frontend/src/Collection/Menus/CollectionSortMenu.js, frontend/src/Store/Actions/movieCollectionActions.js, src/NzbDrone.Core/Movies/MovieRepository.cs, src/NzbDrone.Core/Movies/MovieService.cs, src/Radarr.Api.V3/Collections/CollectionController.cs, src/Radarr.Api.V3/Collections/CollectionResource.cs
NO
Added 2 new filter options to filter by missing or complete collections, and a sort option to sort by missing movies in collections.
* Closes #7338
=> New: Added filter and sort options to Collections

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs, src/NzbDrone.Core/Parser/QualityParser.cs
NO
- Fixed: BluRay Parsing Improvements
- Fixed: Cleanup WebDL Parsing
- Fixed: Parse Blu.Ray as Bluray
* Fixes #8657
=> Fixed: Quality Parsing Regex Improvements

frontend/src/Movie/Delete/DeleteMovieModalContentConnector.js, frontend/src/Store/Actions/addMovieActions.js, frontend/src/Store/Actions/movieActions.js, frontend/src/Store/Actions/movieCollectionActions.js
NO
Handled proper updating of missing movies client state when:
- A movie is deleted.
- A movie is added from AddNewCollectionMovieModal.
- A movie is added from AddNewModal.
* Fixes missing movies client state forgotten to handle in PR https://github.com/Radarr/Radarr/pull/8731
=> Fixed: Handle client state of collection missingMovies

src/NzbDrone.Core/ImportLists/FetchAndParseImportListService.cs
=> More Import List Logging Improvements

src/NzbDrone.Core/Notifications/Xbmc/XbmcService.cs
NO
Clarify path is from kodi not radarr
* Fixes #XXXX
=> Fixed: Improve Kodi Library Update logging

src/NzbDrone.Core/Notifications/Pushsafer/Pushsafer.cs, src/NzbDrone.Core/Notifications/Pushsafer/PushsaferPriority.cs, src/NzbDrone.Core/Notifications/Pushsafer/PushsaferProxy.cs, src/NzbDrone.Core/Notifications/Pushsafer/PushsaferSettings.cs, src/NzbDrone.Core/Validation/RuleBuilderExtensions.cs
NO
Added support for [pushsafer](https://www.pushsafer.com/en/pushapi).
* Closes #8329
=> New: Add pushsafer notification service

src/NzbDrone.Automation.Test/PageModel/PageBase.cs
=> Fix flaky automation tests

src/NzbDrone.Core.Test/Configuration/ConfigServiceFixture.cs, src/NzbDrone.Core/Configuration/ConfigService.cs
NO
- Default RSS to ~~15min~~ 30min from 60min for new installs
- Improve user experience
- aligns with upstream
* Fixes missed RSS grabs for new users
=> New: Default RSS Sync Interval to 30 minutes

src/NzbDrone.Core/ImportLists/FetchAndParseImportListService.cs, src/NzbDrone.Core/MediaCover/ImageResizer.cs
NO
Attempt to improve on #8482
=> Switch to Parallel.ForEach for list processing with MaxParallelism

frontend/src/Movie/MovieImage.js, src/NzbDrone.Core/Datastore/Migration/231_update_images_remote_url.cs, src/NzbDrone.Core/Extras/Metadata/Consumers/Roksbox/RoksboxMetadata.cs, src/NzbDrone.Core/Extras/Metadata/Consumers/Wdtv/WdtvMetadata.cs, src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs, src/NzbDrone.Core/ImportLists/Radarr/RadarrImport.cs, src/NzbDrone.Core/ImportLists/Radarr/RadarrV3Proxy.cs, src/NzbDrone.Core/MediaCover/MediaCover.cs, src/NzbDrone.Core/MediaCover/MediaCoverService.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/Notifications/Discord/Discord.cs, src/NzbDrone.Core/Notifications/Gotify/Gotify.cs, src/Radarr.Api.V3/ImportLists/ImportListMoviesController.cs, src/Radarr.Api.V3/Movies/MovieController.cs, src/Radarr.Api.V3/Movies/MovieResource.cs
YES - 231
Pull #8006, add excludeLocalCovers as query parameter to `/movies` endpoint
* Fixes #8006
=> Media cover tweaks

src/NzbDrone.Core/MediaFiles/MovieImport/Specifications/UpgradeSpecification.cs
NO
- add better debug logging for file import
- improves on https://github.com/Radarr/Radarr/commit/4bcde25e2916ef7727a2f2d7e481501653acc856
- upstream https://github.com/Sonarr/Sonarr/pull/6254
- Tests
* Fixes UX & DX
* Closes #9516
=> Improve Import Custom Format Compare Logging

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs, src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs
YES - NO
Fixes issues with Telegram token being left in the log file
* Fixes #10476
=> Fixed: Telegram Log Message

README.md
N/A
Fix typo in readme
N/A
* N/A
=> fix README typo [skip ci]

azure-pipelines.yml, frontend/src/Components/Modal/Modal.css, frontend/src/Helpers/Hooks/useTheme.ts, package.json, src/NuGet.config, src/NzbDrone.Common/EnvironmentInfo/AppFolderFactory.cs, src/NzbDrone.Common/Radarr.Common.csproj, src/NzbDrone.Core.Test/Http/HttpProxySettingsProviderFixture.cs, src/NzbDrone.Core.Test/Radarr.Core.Test.csproj, src/NzbDrone.Core/Datastore/BasicRepository.cs, src/NzbDrone.Core/Datastore/Migration/000_database_engine_version_check.cs, src/NzbDrone.Core/Datastore/Migration/137_add_import_exclusions_table.cs, src/NzbDrone.Core/Datastore/Migration/Framework/MigrationController.cs, src/NzbDrone.Core/Datastore/Migration/Framework/MigrationExtension.cs, src/NzbDrone.Core/Datastore/Migration/Framework/NzbDroneSQLiteProcessor.cs, src/NzbDrone.Core/Datastore/Migration/Framework/NzbDroneSQLiteTypeMap.cs, src/NzbDrone.Core/Download/TorrentClientBase.cs, src/NzbDrone.Core/Indexers/TorrentRssParser.cs, src/NzbDrone.Core/MediaFiles/TorrentInfo/TorrentFileInfoReader.cs, src/NzbDrone.Core/Radarr.Core.csproj, src/NzbDrone.Test.Common/Radarr.Test.Common.csproj, yarn.lock
- Bump to 6.0.2
- Sonarr Pulls 
- Fork Pulls
=> Bump to 6.0.2

CONTRIBUTING.md
NO
https://github.com/Servarr/Wiki/pull/410
* Fixes #XXXX
=> chore: sync CONTRIBUTING.md from Servarr/wiki
