Radarr/Radarr

- src/NzbDrone.Core/Organizer/FileNameBuilder.cs
NO
Windows doesn't support `:` in paths.
This changes `Transformers: Age Of Extinction` to `Transformers - Age Of Extinction`.
* https://github.com/galli-leo/Radarr/issues/20
> Replace colon in movie path.

- src/NzbDrone.Core/Indexers/Newznab/Newznab.cs
NO
Update to the pre-defined category for the Nzbs.org indexer -- updated for movies
Nzbs.org now useable for movies
*
> changed nzbs.org category for movies

- src/NzbDrone.Common/Cloud/SonarrCloudRequestBuilder.cs
NO
This PR breaks the api calls to:
- http://services.sonarr.tv/v1/scenemapping
- http://services.sonarr.tv/v1/dailyseries
But that's not a problem as those are only required for tv shows.
The following issue's must be fixed before going live with this PR.
- https://github.com/galli-leo/Radarr/issues/39
- https://github.com/galli-leo/Radarr/issues/35
* https://github.com/galli-leo/Radarr/issues/13
> Update services url to fix auto-updater.

- readme.md
Nope
Adding aarch64 docker container information.
Nothing
Further to: https://github.com/Radarr/Radarr/issues/116
Thanks guys, sorry this one took a bit longer.
> aarch64 docker container added to readme.

- src/NzbDrone.Core/Download/CompletedDownloadService.cs
NO
Fix for
```
System.NullReferenceException: Object reference not set to an instance of an object
at NzbDrone.Core.Download.CompletedDownloadService.Process (NzbDrone.Core.Download.TrackedDownloads.TrackedDownload trackedDownload, System.Boolean ignoreWarnings) [0x0020f] in <1d557e64627d470ea0b64c34030b31a3>:0 
at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientItems (NzbDrone.Core.Download.IDownloadClient downloadClient, NzbDrone.Core.Download.DownloadClientItem downloadItem) [0x00042] in <1d557e64627d470ea0b64c34030b31a3>:0```
> Simplify completed download service

- .travis.yml
NO
By modifying the way apt packages work in `.travis.yml` (remove the need to directly require sudo), the builds can now run on container-based infrastructure. 
Information on migrating from legacy to container-based infrastructure can be found [here](https://docs.travis-ci.com/user/migrating-from-legacy/).
> Move Travis builds to container-based infrastructure

- src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
NO
'Couldn't refresh info for [tt3708886][War on Everyone]: Object r…eference not set to an instance of an object'
> Fix for SkyHook ToUrlSlug

- src/NzbDrone.Core.Test/Configuration/ConfigServiceFixture.cs
- src/NzbDrone.Core/Configuration/ConfigService.cs
- src/NzbDrone.Core/Jobs/TaskManager.cs
- src/UI/Settings/Indexers/Options/IndexerOptionsViewTemplate.hbs
Update RSS Sync interval default to 60 minutes, and don't allow values below 10 or higher than 720 minutes (12 hours)
NO
#292
> #292 - Allow longer threshold for RSS Sync

- src/NzbDrone.Api/ClientSchema/SchemaBuilder.cs
- src/NzbDrone.Core/Download/Clients/Deluge/DelugeSettings.cs
- src/NzbDrone.Core/Download/Clients/Hadouken/HadoukenSettings.cs
- src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexSettings.cs
- src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetSettings.cs
- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs
- src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdSettings.cs
- src/NzbDrone.Core/Download/Clients/Transmission/TransmissionSettings.cs
- src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs
- src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentSettings.cs
- src/NzbDrone.Core/Notifications/Email/EmailSettings.cs
- src/NzbDrone.Core/Notifications/Growl/GrowlSettings.cs
- src/NzbDrone.Core/Notifications/Plex/PlexClientSettings.cs
- src/NzbDrone.Core/Notifications/Plex/PlexServerSettings.cs
NO
Proper port validation for download clients and connections.
Reference:
https://github.com/Sonarr/Sonarr/commit/ef03e9e9a7e8170d8166240d827e942362831c72
Fixes issue as described in the Sonarr repository (https://github.com/Sonarr/Sonarr/issues/1642):
When configuring the rTorrent downloader and specifying the port I'm guessing it's a required field. It just kept failing on me while trying to leave it empty, while assuming that empty would default to port 80. It should either provide some feedback that it is a required field, or upon pressing save/test, when empty, fall back to the default (8080 in this instance).
> Fixed: Proper port validation for download clients and connections

- src/NzbDrone.Core/Configuration/ConfigService.cs
Fixes #447
NO
Set the default interval to 0 for the Drone Factory folder so that it doesn't run and fail by default
* 447
> Set Drone Factory Interval default to 0

- src/NzbDrone.Core/Organizer/FileNameBuilder.cs
NO
This expands the DTS audio codec based on the format profile provided by MediaInfo. I have also fixed up Atmos TrueHD to remove the ` /` so you don't end up with `Atmos.+.TrueHD` in the output filename.
> Add expanded DTS audio codecs to FileNameBuilder and fix up Atmos TrueHD audioCodec string.

- src/NzbDrone.Core/Organizer/FileNameBuilder.cs
NO
In my local setup where I was detecting the strings, I forgot they need to only contain the left portion of the string.
> Use shorter format Profile string for DTS profiles.

- src/UI/Calendar/CalendarFeedView.js
- src/UI/index.html
NO
Version (nightly)  0.2.0.285 still points to Nzbdrone.ics when you click Get iCal Link in Calender view.
> Fix ical ics feed file

- src/UI/Wanted/Missing/MissingLayout.js
NO
Unless there is a reason not to make Movie Title and Status sortable on Wanted tab this commit should enable it.
* https://github.com/Radarr/Radarr/issues/481
> Make Movie Title and Status sortable on Wanted tab

- src/NzbDrone.Api/Wanted/MovieMissingModule.cs
NO
.. : Object reference not set to an instance of an object
* https://github.com/Radarr/Radarr/issues/676
> Fixes - MovieMissingModule failed while processing [MovieDownloadedEvent]

- src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs
NO
As per https://github.com/Sonarr/Sonarr/issues/1665, it looks like 2x100ms isn't enough in some cases, up it to 5x200ms instead.
Reference:
https://github.com/Sonarr/Sonarr/commit/0255eb3aca0a2ab97086c8be1e3cc3bbe7774256
> Increase timeout when waiting for rTorrent to finish adding torrent

- src/NzbDrone.Core/Download/Clients/DownloadStation/DownloadStation.cs
- src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationProxy.cs
NO
Manually remove torrent data when completed because api doesn't support it when removing torrent.
> Handle download data diskstation

- src/NzbDrone.Api/Wanted/MovieMissingModule.cs
- src/NzbDrone.Core/IndexerSearch/MissingMoviesSearchCommand.cs
- src/NzbDrone.Core/IndexerSearch/MoviesSearchService.cs
- src/NzbDrone.Core/Tv/MovieService.cs
- src/UI/Wanted/Missing/MissingCollection.js
- src/UI/Wanted/Missing/MissingLayout.js
was searching all missing and monitored only
though the dialog that popped up was informing the user it was
going to search for x movies, where x corresponded to the number
of movies filtered on the page.
I changed this button, so now it will search all the items as they are
filtered on the page.
For example, if you want to search all missing (regardless of
monitor/unmonitor) click the all filter and click the button.
If you want to search only monitored/missing, click the monitored button
and then click the search all button...
this included the old functionality, but allows the user alot more
flexibility...
i also added the all filter, and refactored the code,
so that builds the expression for the LINQ.. since this needed to be
used in two places.. just implement it once and use it in …
> the Search All Missing button

- src/UI/Movies/movies.less
NO
Follow up on the previous PR, poster placeholder was still too small on mobile screen sizes.
> Fix poster placeholder height on small screens

- src/NzbDrone.Api/Config/NetImportConfigResource.cs
- src/NzbDrone.Api/Series/MovieLookupModule.cs
- src/NzbDrone.Api/Series/MovieModule.cs
- src/NzbDrone.Core/Configuration/ConfigService.cs
- src/NzbDrone.Core/Configuration/IConfigService.cs
- src/NzbDrone.Core/MediaFiles/DeleteMediaFileReason.cs
- src/NzbDrone.Core/MediaFiles/MediaFileService.cs
- src/NzbDrone.Core/NetImport/NetImportSearchService.cs
- src/NzbDrone.Core/Tv/MovieService.cs
- src/UI/Movies/Delete/DeleteMovieTemplate.hbs
- src/UI/Movies/Delete/DeleteMovieView.js
- src/UI/Settings/NetImport/Options/NetImportOptionsView.js
- src/UI/Settings/NetImport/Options/NetImportOptionsViewTemplate.hbs
NO
One of the features on featHub was one I opened.. regarding having items in your library, that dont exists on your trakt watchlist be removed from your library (on options, and with varying degree)...
I ended up trying to implement that. and while I was at it, I implemented a feature requested by somebody else regarding the ability to specify movies to exclude from importing even if they are found on your net import lists...
Everything should be fully functional.... except, the option to delete the files along with the movie does not delete the files.
RemoveAndDelete does the same thing as removeAndKeep.. 
i need to look more into why DeleteMovie(movieId,true) is not deleting the files. It appears to do the same thing as DeleteMovie(movieId,false)
http://feathub.com/Radarr/Radarr/+59 …
> List sync with removal

- src/NzbDrone.Core/Notifications/Webhook/Webhook.cs
- src/NzbDrone.Core/Notifications/Webhook/WebhookMovie.cs
- src/NzbDrone.Core/Notifications/Webhook/WebhookPayload.cs
- src/NzbDrone.Core/Notifications/Webhook/WebhookRemoteMovie.cs
- src/NzbDrone.Core/Notifications/Webhook/WebhookService.cs
- src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Implement/fix webhook notifications that were previously using Sonarr format payloads causing a `NullReferenceException`.
- Review/add any other fields to the payload
```
17-2-25 16:36:08.8|Error|NotificationService|Unable to send OnGrab notification to: Test Webhook
[v0.2.0.375] System.NullReferenceException: Object reference not set to an instance of an object
at NzbDrone.Core.Notifications.Webhook.WebhookSeries..ctor (NzbDrone.Core.Tv.Series series) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\Webhook\WebhookSeries.cs:14 
at NzbDrone.Core.Notifications.Webhook.WebhookService.OnGrab (NzbDrone.Core.Tv.Series series, NzbDrone.Core.Parser.Model.RemoteEpisode episode, NzbDrone.Core.Qualities.QualityModel quality, …
```
> Fix/implement Webhook notifications

- src/UI/AddMovies/BulkImport/BulkImportSelectAllCell.js
- src/UI/AddMovies/SearchResultCollectionView.js
- src/UI/AddMovies/SearchResultView.js
- src/UI/Movies/Editor/MovieEditorFooterView.js
- src/UI/Movies/Editor/MovieEditorLayout.js
- src/UI/Movies/FullMovieCollection.js
- src/UI/Movies/Index/MoviesIndexLayout.js
- src/UI/Movies/MoviesCollectionClient.js
- src/UI/Movies/MoviesController.js
- src/UI/Navbar/Search.js
NO
this reverts some changes from previous merge.... fixes the filters in the movieEditor Index... 
"So two issues with this now!
in the movieEditor... saving across pages: no problem.... save across filters... well, the save will work... everything selected will be saved... but, only entries corresponding to movies in the currently visible filter will be reflected in the table.... of course on a refresh.. they will be visible....
There are two solutions to this problem. The obvious one --> when we save, fetch the collection.. but since this is in client mode it has to fetch the entire collection.. so, this could mean that old values will be visible in the table for quite some time until they are fetched...... (this is only for items that were selected, but at the time of saving, were not …
> revert some changes -- use FullCollection (maybe just for now)

- src/UI/Movies/MoviesCollection.js
the recent change to include filterType hits this when model is undefined..
commenting out these lines fixes the problem
NO
released, announced and incinemas filtering was not working on the main MovieIndex
* #
> i believe these are old code that is not needed since pagination..

- src/UI/Movies/Index/MoviesIndexLayout.js
when collection is empty.. not when current filter is empty but collectionis not
NO
* #
> use clone so that we only detect empty collection

- src/UI/Settings/Profile/Delay/DelayProfileLayoutTemplate.hbs
NO
Move delay profiles from advanced settings. I agree it should be more visible on the UI and not hidden behind advanced settings.
> Delay profiles are no longer hidden under advanced settings

- src/UI/Movies/MoviesCollection.js
the change fixed sorting titles of newly added movies without a refresh
however, people have noticed it broke sorting of "In Cinemas" column in general.
i commented out the change; but also added a special case in the comment, that would fix the case in question, without
breaking the others; however, more investigating is needed because there is an issue with sorting newly added movies in general and the
fix this reverts was never good enough anyway.
NO
* #
> reverting a change made yesterday regarding sorting

- README.md
NO
This adds Hotio's nightly docker image and moves the two download badges to a single line like everything else.
> Add hotio's nightly docker image.

- src/NzbDrone.Api/Series/MovieModule.cs
- src/NzbDrone.Core/Tv/MovieService.cs
- src/UI/Movies/MoviesCollection.js
- src/UI/Wanted/Cutoff/CutoffUnmetCollection.js
- src/UI/Wanted/Missing/MissingCollection.js
less code duplication, easier to manage moving forward
NO
this should not change anythnig functionally. Now there is only one place to maintain filtering Expressions.
Previous code was duplicated.. now its in one place - easier to maintain and keep up to date.
* #
> refactor so that filteringExpressions are constructed in one place

- src/NzbDrone.Common.Test/Http/HttpHeaderFixture.cs
- src/NzbDrone.Common/Http/HttpHeader.cs
NO
Fixes parsing headers that have a trailing semi-colon.
Reference:
https://github.com/Sonarr/Sonarr/commit/ebcce05588f7be7b0ed56a45b9758f9d960eb617
> Fixed: Parsing headers that have a trailing semi-colon

- src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotatoSettings.cs
NO
When using Jackett, the TorrentPotato settings Passkey field should set to Jackett's API key (not the user's tracker password). The helptext was updated to be clearer.
- N/A (small UI change)
N/A
> Add helptext for Jackett API key

- src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoLib.cs
NO
Reference:
https://github.com/Sonarr/Sonarr/commit/2e08f195e45966387f5b5d5e76ef8a8d7cf7a8e3
> Fixed: Zero length file causes MediaInfo hanging in 100% cpu load.

- src/NzbDrone.Api/Indexers/ReleaseResource.cs
- src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornParser.cs
- src/NzbDrone.Core/Indexers/Rarbg/RarbgParser.cs
- src/NzbDrone.Core/Parser/Model/ReleaseInfo.cs
- src/UI/Release/ReleaseLayout.js
- src/UI/Release/ReleaseTitleCell.js
@onedr0p So this is how I would (and did) implement different additional infos for the releases of different indexers. With this, we could for example to something like this in a IndexerFlagsSpecification:
```
if (!release.IndexerFlags.HasFlag(PTP_Golden) && release.indexer.RequireGolden)
{
return Decision.Reject("Requires Golden");
}
//Or in prioritization service
if (release1.indexer.PreferGolden)
{
return release1.HasFlag(PTP_Golden) - release2.HasFlag(PTP_Golden); //If both have flag, 0 -> neutral, if release1, 1 -> prefer release 1, etc.
}
```
> Indexer flags implementation.

- src/NzbDrone.Core/Notifications/Email/EmailSettings.cs
NO
Rename smtp.google.com to smtp.gmail.com
* Issue #1392
> Change smtp.google.com to smtp.gmail.com

- src/NzbDrone.Api/Authentication/EnableAuthInNancy.cs
NO
Cookies are all set to / which makes them collide with other apps that use the same cookie names on the same server. Plus it makes cookies bleed into other apps.
One of the maintainers can confirm, if this pull request still makes sense on top of https://github.com/Radarr/Radarr/commit/12e74aa38b4fd98b7048df42cffae5203fa56e1e
https://github.com/Sonarr/Sonarr/commit/d726a7acb21e8cbbcb331e928c419d00969ac3ed
> Fixed: Radarr UI Authentication cookie should be placed on path (UrlBase) instead of domain alone.

- src/NzbDrone.Core.Test/Download/DownloadClientTests/VuzeTests/VuzeFixture.cs
- src/NzbDrone.Core/Download/Clients/Vuze/Vuze.cs
NO
Vuze version 5.7.5.0
Single torrent download with file E:\Downloaded\Completed\Release Name.mp4
Vuze reported E:\Downloaded\Completed as output, although in previous versions it supposedly included the torrent Name.
This caused Radarr to import the entire completed folder and files.
https://github.com/Sonarr/Sonarr/commit/35fca89dad914265658a694426e57ec22714888c
> Fixed: Incorrect imports with Vuze when torrent contains a single file.

- src/NzbDrone.Core.Test/Download/DownloadClientTests/TransmissionTests/TransmissionFixture.cs
- src/NzbDrone.Core.Test/Download/DownloadClientTests/VuzeTests/VuzeFixture.cs
- src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs
NO
Sonarr not importing torrents in Vuze if the torrent already finished seeding and was stopped.
https://github.com/Sonarr/Sonarr/commit/a003a89b14165c5ed7513b3117e27a603a457a2b
> Fixed: Radarr not importing torrents in Vuze if the torrent already finished seeding and was stopped

- src/UI/Movies/Editor/MovieEditorFooterView.js
- src/UI/Wanted/Missing/MissingLayout.js
NO
I updated both backbone.backgrid.js and backbone.backgrid.selectall.js.
I also sorted the returned collection from  getSelectedModels()
before:
after:
let me know if you thinking any tests are necesarry to this change. The only thing I see that is testable is the sort I perform, which I would be happy to test if you think its necessary.
* # The organize modal under movie editor was pulling undefined items for items that weren't on the current page.
* # The organize modal was not showing items by their sortTitle
> Fix: A small bug fix for items loading as undefined in organize modal

- src/UI/AddMovies/BulkImport/BulkImportSelectAllCell.js
NO
The IsDuplicate state of the import checkboxes was not refreshed when the tmdbId was changed by the user, making it impossible to import the fixed movies. I fixed this by rechecking IsDuplicate when the checkbox got the 'change' event.
- Tests - not needed
* #850
> Fix being unable bulk import manually fixed duplicate movies

- src/NzbDrone.Api/ClientSchema/SchemaBuilder.cs
- src/NzbDrone.Core/Indexers/HDBits/HDBitsRequestGenerator.cs
- src/NzbDrone.Core/Indexers/HDBits/HDBitsSettings.cs
- src/UI/Form/TagTemplate.hbs
- src/UI/Handlebars/Helpers/String.js
- src/UI/Mixins/TagInput.js
- src/UI/Settings/Indexers/Edit/IndexerEditView.js
Added advanced configuration options to support filtering Categories, Codecs, and Medium to the HDBits indexer.
NO
Adds support for hdbits category, codec, and medium api filter. The UI for these options is a little ugly and could be made prettier in the future once some sort of multiselect UI control is created. Instead of saving 17 different booleans and presenting the user with 17 different toggles, 3 comma delimited lists was used. Not the most end user friendly way, so it was hidden as an advanced configuration option.
The default behavior, if nothing is entered, is to work as it did before the change. Defaulting the categories might be a good thing to do in the future.
https://github.com/Radarr/Radarr/issues/1419
* #
> Added HDBits Category, Codec, and Medium Filtering Capability

- src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
NO
Ensure an API Key is set when starting Sonarr
https://github.com/Sonarr/Sonarr/commit/6bbe4ce066bbcda46ded450ac450aa641d483bc1
> Fixed: Ensure an API Key is set when starting Radarr

- src/NzbDrone.Core/Download/TorrentClientBase.cs
NO
Currently only 302 and 303 redirects are followed, but certain RSS feeds uses 301 redirects and they aren't followed.
Closes #1564.
https://github.com/Sonarr/Sonarr/commit/755575d107ecd0bf0bd70cde074f18113c573d99
> Follow 301 redirects when fetching torrents

- src/UI/index.html
- src/UI/login.html
NO
Since we already use the recommended way of sending down the `X-UA-Compatible` http header we don't need the meta tag as well.
https://github.com/Sonarr/Sonarr/commit/2ae41a3404cf04a0b4bfbab964befa25e7f56c20
> Remove redundant IE meta tag as we use http header instead

- src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs
- src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs
NO
Fixes the following error:
https://github.com/Radarr/Radarr/blob/9fbe06ad683a4556afa55128b8b8a888a6223198/src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs#L89
https://github.com/Radarr/Radarr/blob/9fbe06ad683a4556afa55128b8b8a888a6223198/src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs#L155
May return a null item, which in turn causes the API resource mapper to crash.
Looks like it happens when the user points manualimport at a file that can't be identified at all.
If that's the case then the workaround would be to point it at a folder instead.
https://github.com/Sonarr/Sonarr/commit/285288db1a49fde28f9b997b06f16c36293ebb48
https://github.com/Sonarr/Sonarr/commit/baf83b4c710100dd04a1f0ed951fbc0141693952
> Fixed error when processing manual import decisions 

- src/NzbDrone.Api/Extensions/Pipelines/UrlBasePipeline.cs
- src/NzbDrone.Api/Frontend/StaticResourceModule.cs
- src/NzbDrone.Api/NzbDrone.Api.csproj
NO
Currently if a user has set a URL Base of `/radarr` and then hits `localhost:7878` they're redirected to the login page at `localhost:7878/radarr/login?returnUrl=/` and when they login they get redirected back to the login page because the cookie is stored on `/radarr` not `/`. This hook needs to execute before the forms auth login hook.
https://github.com/Sonarr/Sonarr/commit/de5ce239893e0698e85228cb5648351f18bfbbbd
> Redirect calls missing URL Base

- src/NzbDrone.Core/Notifications/Plex/PlexServerService.cs
**NO**
Fixes a really confusing error message I ran into when there isn't a film library in Plex. My guess is this is an old message from when you forked Sonarr.
* Rewords an out of date ValidationFailure exception message that is thrown when there isn't a film library in Plex
> Fix old Plex ValidationFailure message

- osx/Radarr.app/Contents/Info.plist
NO
This fixes the issue with Radarr not being able to start for some users from the Finder.
According to Apple:
> CFBundleIdentifier (String - iOS, macOS) uniquely identifies the bundle. **Each distinct app or bundle on the system must have a unique bundle ID**. The system uses this string to identify your app in many ways. For example, the preferences system uses this string to identify the app for which a given preference applies; Launch Services uses the bundle identifier to locate an app capable of opening a particular file, using the first app it finds with the given identifier; in iOS, the bundle identifier is used in validating the app’s signature.
Because the same Identifier was used on Sonarr, the OS was getting confused on which settings to use when starting the App from the …
> Update Info.plist to avoid conflict with Sonarr

- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxy.cs
NO
This is ported from Sonarr to fix a [recent upstream change](https://github.com/qbittorrent/qBittorrent/commit/7cf1d844b05a275a51472fc93de3ce33aa750f0b) to the qBitTorrent 3.3.14 API where the return value is different. In addition, a logging change has also been ported over.
As a bonus, some inconsistent naming references to "qBittorrent" have been fixed for when exceptions or log events occur. 
* #1842
> Port fix from Sonarr for qBitTorrent 3.3.14 API change

- src/NzbDrone.Core.Test/Profiles/ProfileServiceFixture.cs
- src/NzbDrone.Core/Profiles/ProfileService.cs
Fix Check for Used Profile before Delete
NO
Checks Movie repository for a used profile prior to deleting.
> Fix: Check for a Used Quality Profile before Deleting

- src/NzbDrone.Api/System/Tasks/TaskModule.cs
NO
Currently the label of the PreDB Sync task in `/system/tasks` appears as "Pre D B Sync" due to the way the regex pattern matches the taskName string to be replaced. This modification allows the label to be displayed as "PreDB Sync" which is nicer.
> Fix task name of PreDB Sync task

- src/UI/Settings/MediaManagement/Naming/Basic/BasicNamingViewTemplate.hbs
NO
Looks like when these Sonarr related fields were commented out, the `form-group` div from one of the commented out fields was left in the code still. This will probably cause weird layout results as its a hanging div as far as I can tell.
> Fix hanging form-group div in Basic Naming Viewing Template

- src/NzbDrone.Core.Test/HealthCheck/HealthCheckFixture.cs
- src/NzbDrone.Core/Datastore/DbFactory.cs
- src/NzbDrone.Core/HealthCheck/HealthCheck.cs
- src/NzbDrone.Core/Notifications/Twitter/TwitterSettings.cs
- src/NzbDrone.Core/Notifications/Webhook/Webhook.cs
NO
This replaces any GitHub wiki references currently pointing at Sonarr to Radarr.
Pages have been created in Radarr's wiki and modified in a basic sense. Wiki content may need more work. I have left the webhook wiki entry blank for know as its structure differs from Sonarr in terms of Episode vs Movie etc.
> Replace GitHub wiki references to Radarr's wiki paths

- src/NzbDrone.Core/Parser/IsoLanguages.cs
NO
Hebrew ISO will not find any movies. This had to be removed. 
Tested it manually also. It works great now.
> removed hebrew ISO, since english movies are still in english.

- src/UI/Content/FontAwesome/variables.less
NO
Apologies. Recent update to FontAwesome nuked the original set font path in `variables.less` this corrects it!
> Fix FontAwesome font path

- src/NzbDrone.Api/Frontend/Mappers/IndexHtmlMapper.cs
NO
Rather trivial thing, but mask-icon path is broken when UrlBase is in use. In addition, other paths are not rewritten when UrlBase is in use, so I've added further rules in addition to the Sonarr fix.
> Fix mask-icon and other resources when UrlBase is in use

- src/UI/Settings/DownloadClient/DroneFactory/DroneFactoryViewTemplate.hbs
NO
@weirdcrap raised a good point in the linked issue about Drone Factory. Sonarr is deprecating it, therefore at minimum we should be also displaying the message on the front end as well.
In addition there is the HealthCheck for Drone Factory, but looking through the commits, getting it merged in will require a bit more work as a fair bit of rework was done on HealthChecks and associated code and will likely have merge conflicts with Radarr changes.
For now, this just adds the message to the front end.
#1936
> Add deprecation warning about Drone Factory to front end

- src/UI/jQuery/jquery.validation.js
(cherry picked from commit 3749f3e2e5e80de0637188fca949fd90b2a95ceb) from Sonarr.
NO
The icon for extended error info for various error messages on fields are not appearing, here's the current output on an example error with extended detail info.
This fixed output, where the icon should appear
> Fix missing icon preventing detailed info for validation errors from appearing

- src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
NO
Hotfix for parser regex error on folder name using `(year) name`
* #[1951](https://github.com/Radarr/Radarr/issues/1951)
> Hotfix for parser error when using `(year) name` folder

- src/UI/Content/Overrides/bootstrap.less
- src/UI/Navbar/NavbarLayoutTemplate.hbs
NO
* Allows for larger logo to be displayed in the medium breakpoint, because it can fit.
* Remove empty unordered list element and added the margin with CSS
* Added `aria-hidden` to nav icons because of the text label already present
Existing logo appearance in medium breakpoint:
Logo appearance with modifications in medium breakpoint:
> Tweak NavbarLayoutTemplate.hbs

- src/UI/Activity/Blacklist/BlacklistLayout.js
- src/UI/Content/theme.less
- src/UI/Movies/Editor/MovieEditorLayout.js
- src/UI/System/Backup/BackupLayout.js
- src/UI/Wanted/Cutoff/CutoffUnmetLayout.js
NO
So this is something that's always bothered me, but currently the toolbar buttons layout don't really scale on mobile, a lot of wasted space on larger devices in the small breakpoint.
Currently:
With some changes:
It is a little hacky override the classes, but I don't think there is any simpler way to do it, outside of implementing it JS but having to detect the breakpoint size and adding classes conditionally like `.btn-block` etc.
Its a fairly simply override, I've specifically targeted `x-toolbar-left-1` because it looks to be the single class used on these button toolbars only i.e. they always appear first on the page.
This modifies the look and feel of the buttons on:
* Movies
* Index
* Movie editor
* Activity
* Blacklist
* Wanted section
* Missing
* Cutoff unmet
* System
* Backup …
> Allow toolbar buttons to be full width on x-small and small breakpoints

- src/UI/AddMovies/AddMoviesLayoutTemplate.hbs
NO
Currently in X-Small, the Discover New Movies button still has its icon showing when the other buttons have them hidden, causing a bit of inconsistency, this fixes that and also improves the accessibility with `aria-hidden`.
> Fix icon not being hidden on Discover New Movies button in X-Small

- package.sh
NO
To be consistent, I replaced backticks with `$()`. It is generally noted as the more favourable method with shell.
> Convert backticks in package.sh

- src/UI/Settings/NetImport/Options/NetImportOptionsViewTemplate.hbs
NO
* Increase label size so text can fit on one line
* Fix alignment to the options section above (increase label col size)
* Ensure buttons are contained within col layout
* Add a space for the "Log Only" field option (value unchanged)
* Make Trakt buttons appear inline on the token input field
* Fix indents and HTML markup
* Stop commented out field appearing in the HTML output
* Encoded & as `&amp;`
New appearance in the settings section with these changes.
> Fix alignment and buttons position of Trakt Auth

- src/NzbDrone.Api/Calendar/CalendarFeedModule.cs
NO
This sets a default name when the ics file is added to a calendar that supports iCal. It appears for compatibility, both the `NAME` and `X-WR-CALNAME` should be set.
Thought it might be better than using the rather long URL string for the default!
> Set a default name for Radarr.ics

- src/UI/Settings/UI/UiViewTemplate.hbs
(cherry picked from commit 00c307421666b55a6d08ff1c69c1871ccb541314)
NO
Adjusts the example labels for setting the date in the UI. I'm inclined to agree with original author @franga2000 of the PR on Sonarr, that its not obvious and can be ambiguous here.
https://github.com/Sonarr/Sonarr/commit/00c307421666b55a6d08ff1c69c1871ccb541314
> Adjust ambiguous date options

- src/UI/AddMovies/SearchResultViewTemplate.hbs
- src/UI/AddSeries/MonitoringTooltipTemplate.hbs
- src/UI/AddSeries/SearchResultViewTemplate.hbs
- src/UI/Navbar/NavbarLayoutTemplate.hbs
- src/UI/Series/Details/InfoViewTemplate.hbs
- src/UI/Wanted/WantedLayoutTemplate.hbs
NO
We can use the `{{!-- --}}` comments in hbs files to comment out the code but not have it outputted in the HTML. Just a small optimisation but will cut the request size down slightly.
I've done a regex find for `<!--` in any .hbs file and this was picked up, others have been picked off in recent changes.
> Stop commented out code appearing in HTML source in various places

- src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
- src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs
(cherry picked from commit 35f911286f76ada5226c439dad416fcdde9d6236)
NO
When using Jackett as an indexer, cleanse the API key from logs.
Ported from Sonarr.
> Add Jackett apikey to log cleanser

- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxy.cs
- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs
- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentState.cs
- src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Port initial state when adding torrents for qBittorent, implemented in Sonarr in September.
https://github.com/Sonarr/Sonarr/commit/ef8b882258786ed99cc04f81e9414d039bfb0357
> Initial state option for torrents added to qBittorrent

- src/UI/AddMovies/addMovies.less
- src/UI/AddSeries/addSeries.less
- src/UI/Calendar/calendar.less
- src/UI/Cells/cells.less
- src/UI/Content/Backgrid/paginator.less
- src/UI/Content/Overrides/bootstrap.less
- src/UI/Content/Overrides/bootstrap.tagsinput.less
- src/UI/Content/Overrides/fullcalendar.less
- src/UI/Content/Overrides/messenger.less
- src/UI/Content/bootstrap.tagsinput.less
- src/UI/Content/form.less
- src/UI/Content/navbar.less
- src/UI/Content/spinner.less
- src/UI/Content/theme.less
- src/UI/Hotkeys/hotkeys.less
- src/UI/Movies/movies.less
- src/UI/SeasonPass/seasonpass.less
- src/UI/Series/series.less
- src/UI/Settings/Metadata/metadata.less
- src/UI/Settings/Profile/profile.less
- src/UI/Settings/Quality/quality.less
- src/UI/Settings/settings.less
- src/UI/Settings/thingy.less
- src/UI/Shared/Styles/card.less
NO
A fair few LESS CSS rules have `0px` defined, which is redundant, as you don't need to declare a unit on a zero value.
> Remove redundant unit declaration on zero values

- src/UI/Hotkeys/hotkeys.less
> Fix typo on margin-bottom property hotkeys.less

- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs
NO
New installs of qBittorrent set `8080` as the default port, so this sets the default indexer config with that port.
> Change default port of qBittorrent download client config

- src/NzbDrone.Core.Test/Download/DownloadClientTests/UTorrentTests/UTorrentFixture.cs
- src/NzbDrone.Core/Download/Clients/uTorrent/UTorrent.cs
- src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentProxy.cs
- src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentSettings.cs
- src/NzbDrone.Core/Download/Clients/uTorrent/UtorrentState.cs
- src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Ports over the initial state feature from Sonarr. Also renamed references to `TvCategory` to `MovieCategory` and also changed the default port for the client config to `8080` which is the default alternative port value on newer installs.
> uTorrent initial state feature

- src/UI/System/Logs/Table/LogsTableLayoutTemplate.hbs
NO
Looks like the `/api/log` request gets flagged by the EasyPrivacy list as a regex rule to block. This adds a dismissable alert on the page to inform the user of this.
Short term fix for now. Potentially the `/api/log` route could be renamed to something like `/api/syslog` to avoid the filter as a more long term fix.
* #2209
> Add message about adblockers preventing the log table from loading

- src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedMovie.cs
- src/NzbDrone.Core/MediaFiles/Events/MovieDownloadedEvent.cs
- src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
- src/NzbDrone.Core/Notifications/DownloadMessage.cs
- src/NzbDrone.Core/Notifications/NotificationService.cs
Feature based on equivalent Sonarr feature. Add an additional enviornment variable for the download id from the torrent client for the custom post processing script feature. The variable name is 'Radarr_Download_Id' with the description 'The hash of the torrent/NZB file downloaded (used to uniquely identify the download in the download client).
* #
> Add Download_Id to On Download/On Upgrade

- src/NzbDrone.Core/Notifications/Slack/Payloads/SlackPayload.cs
- src/NzbDrone.Core/Notifications/Slack/Slack.cs
- src/NzbDrone.Core/Notifications/Slack/SlackSettings.cs
Adds ability to specify Slack channel for incoming webhook.
NO
Adds the ability to specify a channel for Slack incoming webhook. Reference [commit](https://github.com/Sonarr/Sonarr/commit/e11e8ad2722f848f034f7768fbb6227b5af065de) in Sonnar code solving the same issue.
* #2298
> Customize Slack Channel

- src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
- src/NzbDrone.Core/Parser/LanguageParser.cs
Added support for VF2 french tag.
Added new test with VF2 example
NO
VF2 tag is commonly used by french uploaders to designate the fusion of VFF and VFQ release in one file. Not supporting this means all releases with this tag fall into the english category instead of french.
* #2290
> Added support for VF2 french tag.

- src/NzbDrone.Core/Organizer/FileNameBuilder.cs
- src/UI/Settings/MediaManagement/Naming/Partials/MediaInfoNamingPartial.hbs
NO
Add separate MediaInfo naming tags for AudioLanguage and SubtitleLanguage with the same behavior as in {MediaInfo Full}
AudioLanguageAll will include English even if it is the only language.
* #2257
> Add separate naming tags for AudioLanguage and SubtitleLanguage

- src/NzbDrone.Core/NetImport/TMDb/TMDbSettings.cs
YES | NO
This request changes the REGEX used to allow the pipe character to be used in Included and excluded Genre IDs.  The help popup has also been changed to include the change in function as well as a couple of spelling mistakes of the word certification. 
https://github.com/Radarr/Radarr/issues/2278
* #
> Update TMDbSettings.cs to allow OR separated Genre IDs Issue #2278

- appveyor.yml
NO
Tells appveyor not to use build cache if you have made changes to package.json
We spent a while chasing a build issue that turned out to be cache, figured you guys could benefit here as well.
> Look for changes to package.json before using old build cache

- src/NzbDrone.Core/MediaFiles/UpdateMovieFileService.cs
NO
Parses in last modified date for file as a UTC date and ignores the time during the parse. This creates a DateTime object with 12:00AM UTC which is the format Radarr uses for the release DateTime. 
fixes #1741
* #
> Fixed: Radarr Changes every file due to timezones

- src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/Specifications/SameFileSpecificationFixture.cs
- src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
- src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/SameFileSpecification.cs
- src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Adds same file size import specifications (files of same file size as the existing file for a given movie are rejected for import)
#2482 
* #
> New: Same File Size MediaFile Specification

- src/UI/AddMovies/BulkImport/BulkImportView.js
Remove sorting on Monitor/Profile columns to prevent unexpected results until sorting can properly be handled. Quick Fix for #2540
> Bulk Impoprt - Remove sorting on Monitor/Profile

- src/NzbDrone.Core.Test/DecisionEngineTests/HistorySpecificationFixture.cs
- src/NzbDrone.Core.Test/HistoryTests/HistoryRepositoryFixture.cs
- src/NzbDrone.Core.Test/HistoryTests/HistoryServiceFixture.cs
- src/NzbDrone.Core/DecisionEngine/Specifications/RssSync/HistorySpecification.cs
- src/NzbDrone.Core/History/HistoryRepository.cs
- src/NzbDrone.Core/History/HistoryService.cs
- src/UI/Activity/History/Details/HistoryDetailsLayoutTemplate.hbs
- src/UI/Activity/History/Details/HistoryDetailsViewTemplate.hbs
NO
Fixes multiple issues with history classes as well as some cleanup:
- Correctly show tooltip for movieFileDeleted events in UI
- Add EventHandler definition for MovieDeletedEvent in HistoryService (was not hooked up)
- Cleanup TV Events in History Service
- Update `FindDownloadHistory` method so that it looks for movie history instead of series history when searching for downloaded items.
- Update `GetBestQualityInHistory` method to work for movies.
This does not remove the series fields from the history model as that would also require a DB migration and it may be best to do one migration for the entire series cleanup from all tables after more of the core is cleaned up. 
Not sure if this fixes any current github issues?
* #
> Fixed: Multiple History Issues

- src/UI/Movies/Index/Posters/SeriesPostersItemView.js
- src/UI/Movies/Index/Posters/SeriesPostersItemViewTemplate.hbs
- src/UI/Movies/movies.less
NO
Fixes poster items reference to `series-controls` that had previously been changed to `movie-controls` in movies.less, but was hidden by existence of `series.less`.
Fixes #2568
> Fixed: Poster sliding issues

- .gitignore
- build-appveyor.cake
- build-appveyor.ps1
- tools/packages.config
NO
Workaround Appveyor builds failing due to Cake version/verification checks (Cake.npm doesn't reference latest version 0.26)
Option two is we change our reference to cake packages.config to `https://raw.githubusercontent.com/cake-build/example/9fb63124abc90e5e9cf925355353a877c9dc9d54/tools/packages.config` which is package.config for v0.25.0. This would pin us to that version instead of always getting the latest (which may or may not play well with our cake packages (cake.npm, cake.compression). 
Option 2 appears to be recommendation by devs: https://github.com/cake-contrib/Cake.Npm/issues/70
> Fixed: Pin Cake and Addin Versions

- src/NzbDrone.Core/MediaFiles/DiskScanService.cs
NO
The previously committed fix to the listed issues didn't appear to work, at least for me, so I did some digging and comparisons with Sonarr's behaviour and think this fix should work. It sends the movie through the same route as it does when just the file is deleted - MediaFileTableCleanupService -> MediaFileService -> MovieService, which ends up doing the unmonitor config option check.
* #1191 and #1590
> Fixed: Movies not getting unmonitored when folder gets deleted

- src/UI/AddMovies/AddMoviesView.js
Searching for a movie by name copy-pasted from somewhere looks like common scenario, and search is not triggered when text got pasted into input.
'Input' event works better then 'keyup' as it got triggered upon _any_ change of input's value (keypress, paste, text drag-n-drop).
> changed: which event handler triggers movie search

- src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
NO
Set Kodi date format to "yyyy-MM-dd" for premiered date in nfo file.
Fixes #2582
> Fixed: Incorrect Kodi nfo date format

- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxy.cs
NO
This incorporates [a change from Sonarr](https://github.com/Sonarr/Sonarr/commit/bcf45bb68a72e73df57ac1ccf3ca2a8da4a4d78b) that attempts to fix a bug with adding categories to torrents sent to qBittorrent.
* #2200
> Set category when adding torrent to qBittorrent

- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxy.cs
NO
https://github.com/Sonarr/Sonarr/commit/ac379e3b84a68b5a895bcaeb24056be4c8918887
Fixes #2655 
* #
> Fixed: Don't add category when removing torrent from qBittorrent

- src/NzbDrone.Core.Test/Profiles/ProfileServiceFixture.cs
- src/NzbDrone.Core/Profiles/ProfileService.cs
- src/UI/Settings/Profile/Edit/EditProfileLayout.js
NO
- Fix UI so that Delete button cannot be pressed when disabled.
- Disable delete in UI if List exists using profile.
- Block profile deletion in backend if list uses profile.
Fixes #1540
> Fixed: Don’t allow profile delete list

- src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
NO
When `Bitrate` property cannot be parsed from movie file mediainfo, fallback to look for `Bitrate_Nominal` when available.
Fixes #2860
> Added: Fallback to Bitrate_Nominal for MediaInfo

- src/UI/Movies/movies.less
NO
I made a small mistake on my previous pull request and I'm here fixing it. The idea is to have the `pointer` cursor for labels which are links (like links to Trakt, IMDb, Trailer, etc...) and the `default` cursor for non-link labels (which are just informational).
Hopefully this finally fixes that for the poster view.
> Use proper cursor for text and linked labels

- osx/Radarr
NO
Lots of macOS users use Homebrew to manage things like Mono and other libraries. This ensures Radarr is compatible out-of-the-box, and does not require installing multiple copies of Mono.
Mirrors Sonarr/Sonarr#2728
None
> Add support for Homebrew-installed mono

- src/NzbDrone.Core/Notifications/Xbmc/JsonApiProvider.cs
NO
This fix trims the filename from the Kodi movie path before sending the library scan JSONRPC call.
This doesn't completely resolve the problem in the case where the folder structure the movie is in changes. To resolve this the call would need to have both the original and new path (which the code doesn't have at the point of the call).
Issue #2771 partially fixed
* #
> Trim filename from Kodi movie path before sending library scan request.

- src/NzbDrone.Core/IndexerSearch/MoviesSearchService.cs
NO
When movies are added to Radarr through Net Import Sync (Lists) - not sure if this happens when added through other methods - with the option "Add Movies Monitored" set to `NO` (movies will be added as `unmonitored`), movies are still searched (Indexers APIs are still invoked) when they shouldn't. This fixes that.
> Skip movie search if movie was added as "unmonitored"

- src/NzbDrone.Common/Extensions/StringExtensions.cs
- src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatAudioChannelsFixture.cs
- src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatAudioCodecFixture.cs
- src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatVideoCodecFixture.cs
- src/NzbDrone.Core.Test/MediaFiles/MediaInfo/UpdateMediaInfoServiceFixture.cs
- src/NzbDrone.Core.Test/MediaFiles/MediaInfo/VideoFileInfoReaderFixture.cs
- src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
- src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs
- src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoModel.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/UpdateMediaInfoService.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
- src/NzbDrone.Core/MediaFiles/MovieFile.cs
- src/NzbDrone.Core/NzbDrone.Core.csproj
- src/NzbDrone.Core/Organizer/FileNameBuilder.cs
- src/NzbDrone.Core/Organizer/FileNameSampleService.cs
- src/UI/Cells/MediaInfoCell.js
NO
In a nutshell, this attempts to fix some issues with MediaInfo tokens and adds new interesting tokens:
- Updated MediaInfo to 18.08.1 (Windows/macOS);
- Fixes issue with VideoCodec not being properly used;
- Adds proper detection for most kinds of DTS and TrueHD streams (including DTS:X and Atmos);
- Adds support for `{MediaInfo 3D}` and `{MediaInfo HDR}` tokens;
- Fixed all related tests and added a couple more.
> Refactor MediaInfo tokens (fixes old tokens adds new stuff)

- src/UI/AddMovies/BulkImport/MoviePathTemplate.hbs
- src/UI/AddMovies/addMovies.less
NO
Small style improvements to the movie path template on the "bulk import movies" screen:
- Fixed overflow ellipsis (different color, not italicized as the text).
- Added small character to better indicate the file is inside the respective folder.
* Fixes #3106.
> Tweak style of movie path template on "bulk import movies" screen

- src/NzbDrone.Core.Test/DiskSpace/DiskSpaceServiceFixture.cs
- src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
- src/NzbDrone.Core/DiskSpace/DiskSpaceService.cs
- src/NzbDrone.Mono/Disk/DiskProvider.cs
- src/NzbDrone.Mono/Disk/ProcMountProvider.cs
NO
Filters "special drives" from being displayed in `System » Disk Space`. Code borrowed from Sonarr's [DiskSpaceService.cs](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/DiskSpace/DiskSpaceService.cs).
Fixes #3045 & #3122.
> Ignore "special drives" from System » Disk Space

- src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
NO
Restore functionality from #2886 as requested on #3058.
> Read video 'BitRate_Nominal' if 'BitRate' is empty

- src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatVideoCodecFixture.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoModel.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
- src/UI/Cells/MediaInfoCell.js
NO
Fallback to `VideoCodec` property if `VideoFormat` is not found. Should solve issues with existing installations and already imported movies with MediaInfo data written with the legacy `VideoCodec`.
> Fallback to 'VideoCodec' if 'VideoFormat' is unavailable

- src/NzbDrone.Core.Test/MediaFiles/MediaInfo/VideoFileInfoReaderFixture.cs
NO
Fixes unit tests failing due to "LC" being read from AudioAdditionalFeatures
* #
> Fixed: MediaInfo Unit Test Failing due to AudioAdditionalFeatures after MediaInfo update

- src/Common/CommonVersionInfo.cs
- src/NzbDrone.Common/Properties/SharedAssemblyInfo.cs
NO
This sets default assembly version back to 10.0.0.build. When default version is less than or equal to current release version Radarr tries to update to latest release when running from source. This should not affect building as assembly version is set by Appveyor during build. 
* #
> Fixed: Bump default version to prevent update running from source

- src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
- src/NzbDrone.Core/Parser/QualityParser.cs
This tag is used by the scene to indicate it's a Music BluRay release, meaning it's a video from a concert/festival (not that it's music w/o audio).
Check pre for "1080p mbluray" examples.
Mention of mbluray in the bible: https://scenerules.org/t.html?id=2014_BLURAY.nfo
NO
> Match MBluray releases

- src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
- src/NzbDrone.Core/Parser/LanguageParser.cs
NO
After the changes from PR #2948, the regex was too eager to match any substring contain "SK", such as in "MASK" or "GASMASK". Fix by requiring word separation around it, as was already the case with the "CZ" token.
> Fix mis-classification of releases as being Czech

- src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
NO
Adds word boundaries on edition parsing regex so as not to grab false positives.
Fixes #3355 
Fixes #2846 
* #
> Fixed: Word Boundary on Edition

- src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
- src/NzbDrone.Core/Parser/LanguageParser.cs
NO
Allow SubtitleLanguageRegex to recognize `forced` subs
#2908 
* #
> Fixed: Forced Subs not parsed by SubtitleLanguageRegex

- src/NzbDrone.Core.Test/CustomFormat/QualityTagFixture.cs
- src/NzbDrone.Core/Parser/LanguageParser.cs
NO
Modify language parser regex so that it will match on beginning of string as well, fixes custom format cases (ex. `italian` or `ita` match now). 
#3253 
* #
> Fixed: Cannot Add ITA or ITALIAN custom format

- src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
NO
Added remote poster and fanart references to the output of Kodi metadata files. Including these tags allows Kodi to properly differentiate video thumbnails from posters and fixes the issue that some skins would show a video thumbnail instead of the poster because of the empty `<thumb>` tag. Fanart entries were included as an extra for completeness.
The metadata file now refers to the remote images from TheMovieDB. Therefore, this solution will not provide the intended result (i.e., using the local image files), but does fix the issue that no posters or fanart are shown in Kodi. 
* Fixes #2837
> Added: Remote poster and fanart references to Kodi metadata file (#2837)

- src/UI/Settings/MediaManagement/FileManagement/FileManagementViewTemplate.hbs
NO
The previous title: "Ignore Deleted Movies" is ambiguous. It can be interpreted as either:
-> If a movie is deleted, do nothing and ignore it.
-> If a movie is deleted, unmonitor the movie (and ignore future changes).
With this naming change, I hope to solve that issue, and it's more clear as to what the setting actually does.
> Solve ambiguous naming

- src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
- src/NzbDrone.Core/Notifications/GrabMessage.cs
- src/NzbDrone.Core/Notifications/NotificationService.cs
NO
Added Radarr_Download_Id and Radarr_Download_Client to the environment
variables passed to custom post-processing 'On Grab' scripts. In order to
do this, two new fields were introduced to the GrabMessage object
(DownloadClient and DownloadId). This reflects Sonarr's implementation.
(tested successfully in my development environment)
* #3232
> New: Add Radarr_Download_Id and Radarr_Download_Client to PP scripts

- src/NzbDrone.Api/NetImport/NetImportModule.cs
- src/NzbDrone.Api/NetImport/NetImportResource.cs
- src/NzbDrone.Core/Datastore/Migration/151_add_tags_to_net_import.cs
- src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupUnusedTags.cs
- src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
- src/NzbDrone.Core/NetImport/HttpNetImportBase.cs
- src/NzbDrone.Core/NetImport/NetImportDefinition.cs
- src/NzbDrone.Core/NzbDrone.Core.csproj
- src/UI/Settings/NetImport/Edit/NetImportEditView.js
- src/UI/Settings/NetImport/Edit/NetImportEditViewTemplate.hbs
YES
Adds a `Tags` field to lists configuration so that one can associate tags with imported movies from network lists.
If anyone's interested in helping me solving the two issues above, I'd really appreciate it. Without them, especially the last one, this feature is not finished.
> Add tags support to NetImport (Lists)

- src/UI/Movies/Index/MoviesIndexLayout.js
- src/UI/Movies/MoviesCollection.js
NO
Only show the empty page view, when the unfiltered movies collection is actually empty.
When there are movies that are currently filtered out, show the filter toolbars so users can change the view.
[Screenshot](https://i.imgur.com/F4OfSPu.png)
* #3514
> #3514 fix library shown as empty after filter returns no movies and page is refreshed

- src/NzbDrone.Core.Test/MovieTests/AlternativeTitleServiceTests/AlternativeTitleFixture.cs
- src/NzbDrone.Core.Test/MovieTests/AlternativeTitleServiceTests/AlternativeTitleServiceFixture.cs
- src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
- src/NzbDrone.Core/Movies/AlternativeTitles/AlternativeTitle.cs
- src/NzbDrone.Core/Movies/AlternativeTitles/AlternativeTitleRepository.cs
- src/NzbDrone.Core/Movies/AlternativeTitles/AlternativeTitleService.cs
- src/NzbDrone.Core/Movies/RefreshMovieService.cs
Not sure if we should add more tests, I think they should cover most of it.
Fixes #3542
NO
* #3542
> Fixed: When refreshing info about a movie, the alt titles should now correctly be deleted / updated, even from TMDB.

- src/NzbDrone.Core/Indexers/Rarbg/RarbgRequestGenerator.cs
- src/NzbDrone.Core/Indexers/Rarbg/RarbgSettings.cs
Movie in category "Movs/x265/4k/HDR" were not returned
NO
Movies in category "Movs/x265/4k/HDR" were not returned - certainly because it is named differently (all other categories but this one care called "Movies/..."). I tried to use movs as a criteria (category=movs) but it is not working - this is why I had no choice but to expand the list. 
This is exactly how Jackett does it.
Values are stored in a Dict for readability. The name of the category is never used. I could change that to an array of int with the name in comment if you feel more like it.
* https://github.com/Radarr/Radarr/issues/3543
> Fix search for RARBG

- src/NzbDrone.Api/Wanted/MovieCutoffModule.cs
- src/NzbDrone.Api/Wanted/MovieMissingModule.cs
- src/NzbDrone.Integration.Test/ApiTests/WantedTests/CutoffUnmetFixture.cs
- src/NzbDrone.Integration.Test/ApiTests/WantedTests/MissingFixture.cs
NO
FilterExpression is set in MovieService by method above added lines, remove lines to un-break filtering on these pages. Need to update integration tests to suit.
#3605 
* #
> Fixed: Wanted Cutoff Page filters

- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
NO
Added names of groups who repost releases, and add their names to the end, into CleanReleaseGroupRegex.
Similar groups were added into [Sonarr](https://github.com/Sonarr/Sonarr/commit/fa8b8cebf9c142348124e57342913c6ff3873fd2#diff-23ff1526865b238134cc108b0cf2acd3) as well. 
Tried to find movie releases with these scenarios as test examples. For the ones I couldnt find, I used TV releases (this was also done previously on tests/inclusions made by others).
* n/a
> New: Added reposting groups as exclusions into CleanReleaseGroupRegex

- src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
- src/NzbDrone.Core/Parser/QualityParser.cs
NO
HDCity names 2160p Remux releases as UHDRemux, which currently Radarr parses as WEB-DL instead of Remux
- [ X] Tests
Fixes #3694
> Fixed: Parse UHDRemux as Remux and not as WEB-DL

- src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
- src/NzbDrone.Core/Extras/ExtraService.cs
- src/NzbDrone.Core/Extras/Subtitles/SubtitleService.cs
- src/NzbDrone.Core/Parser/LanguageParser.cs
NO
Currently extra file service only searches extra files in the top-level directory with filename identical to the movie file. This update allows searching of extra files in sub-folders and even if extra file names are different . This also fixes subtitle language parser us the current regex string doesn't match RARBG format. SRT files will be added as multiple copies with lower suffixes for subs with higher detail (ie. subs for HI) so that media player selects those as default.
Here are sample output:
3_Eng.srt --> movie.1.en.srt
2_Eng.srt --> movie.2.en.srt
movie.idx --> movie.idx
movie.sub --> movie.sub
* #1958
> Fixed: .srt files in subfolders are not being imported

- src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
NO
Seems our friends at tmdb have changed something, and the rate limit headers are not always returned. This will check for header in response instead of assuming it will be there
* #
> Fixed: TMDB Failing due to missing response header

- src/NzbDrone.Core/MediaFiles/MovieImport/Specifications/UpgradeSpecification.cs
NO
A string has been bugging me. A simple change of replacing the word episode with movie in the UpgradeSpecification
- [ x ] Tests
None should be needed 
* #
> Fixed: Replaced episode with movie in UpgradeSpecification

- src/Directory.Build.props
- src/NzbDrone.Common.Test/ProcessProviderTests.cs
- src/NzbDrone.Common/Composition/ContainerBuilderBase.cs
- src/NzbDrone.Common/Disk/DiskProviderBase.cs
- src/NzbDrone.Core/MediaCover/CoverAlreadyExistsSpecification.cs
- src/NzbDrone.Test.Common/AutoMoq/AutoMoqer.cs
NO
Assorted fixes to .NET core aphrodite:
- Remove accidental dependency of `Radarr.Update` on `Radarr.Core.dll` (from the `NativeDependencyResolver`)
- Don't publish tests self contained - you need the SDK to run them anyway
- Make process provider tests more reliable
- Remove some old references to System.Drawing
* Fixes #3822
> Aphrodite fix update

- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
NO
The state 'moving' wasn't being recording in Radarr, so it would show up as a warning.
> Fixed: Added qBittorent state 'moving'

- src/NzbDrone.Host/WebHost/WebHostController.cs
NO
Fixes cert import using X509Certificate2 constructor [(MSDN)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.-ctor?view=netframework-4.8#System_Security_Cryptography_X509Certificates_X509Certificate2__ctor_System_String_System_String_System_Security_Cryptography_X509Certificates_X509KeyStorageFlags_).
(Info to same issue: [Link 1](https://stackoverflow.com/questions/47756451/load-x509-certificate-from-disk-net-core) and [Link 2](https://www.cloudnotes.io/x509certificate-is-immutable-on-this-platform-use-the-equivalent-constructor-instead/))
Error message before: `Unable to start Kestrel.: X509Certificate is immutable on this platform. Use the equivalent constructor instead.`
with Exception: 
``` …
```
> Fixed: SSL certificate import

- src/NzbDrone.Core/NetImport/NetImportSearchService.cs
having this code there shouldnt reintroduce the problem
however it will allow us to substantially reduce the amount of time netimport takes when running
NO
I think having this code in there vastly improves performance but doesnt reintroduce the bug regarding duplicates.
It just means we chop a ton of movies off the list from the begining, if there were some that we didnt catch they will be caught in the subsequent code that was introduced when this was removed.
* #
> add this code back since it can vastly improve netimport performance

- frontend/src/Settings/UI/UISettings.js
The time format was incorrectly showing the D/M format as DD/MM (25/03 instead of 25/3).
NO
The time format was incorrectly showing the D/M format as DD/MM (25/03 instead of 25/3).
Nothing needed
Not aware of any issues for this
> Fix: Typo in UI dropdown for time format

- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs
- src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs
- src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentSettings.cs
NO
Changes a few strings in download client settings to match "movies/released" rather than "episodes/aired"
- Nothing
* Nothing
> download client settings: change strings to match Radarr

- src/LogentriesCore/LogentriesCore.csproj
Linux could not find ConfigurationManager due to case-sensitivity,
failing to build
NO
Linux could not find ConfigurationManager due to case-sensitivity, failing to build
* #
> Fix typo in LogentriesCore.csproj

- src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatAudioCodecFixture.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
Added a second if statement under "if (audioFormat.ContainsIgnoreCase("E-AC-3"))" to look for "JOC" in splitAdditionalFeatures to be able to identify EAC3 tracks that contain atmos. I used the audioFormat "MLP FBA" with "TrueHD Atmos" as a reference.
* #
> Added a EAC3 Atmos option

- frontend/gulp/webpack.js
- frontend/src/index.js
- frontend/src/preload.js
NO
Correctly set `__webpack_public_path__` so workers are loaded from correct path.
Since ES6 hoists imports to the top of the files, as currently set up all imports happen before `__webpack_public_path__` gets set.
> Fixed: Webpack worker loading with UrlBase

- src/NzbDrone.Console/ConsoleApp.cs
NO
Just sit there if console redirected, don't look for a key since that throws an error an makes Sentry go wild.  Can still be killed with ctrl-c.
Fixes Sentry Radarr-3AK
> Fixed: Error in epic fail handler if console input redirected

- src/NzbDrone.Common.Test/DiskTests/DiskProviderFixtureBase.cs
- src/NzbDrone.Common/Disk/DiskProviderBase.cs
- src/NzbDrone.Mono/Disk/DiskProvider.cs
NO
File.Move in .NET Core was falling back to copy/delete too eagerly.  To workaround, check if destination exists and if not call move with overwrite true, to prompt a move and not copy/delete.
> Fixed: File move uses rename not copy/delete in more cases

- azure-pipelines.yml
NO
Check for back end changes at start of build and skip stages if none.
- Reduces build time from ~27-30min to ~13-14min if only front-end changes were made. 
- Adds ~25-30sec  for full back-end builds with testing.
- Maintains front-end linting/sonar analysis
- Reduces worker usage when multiple builds are in pipeline
View this build for proof of concept.
> New: Don't Run Unit/Integration/Analyze Back if no back end changes

- src/NzbDrone.Core/Datastore/Migration/036_update_with_quality_converters.cs
- src/NzbDrone.Core/Datastore/Migration/154_add_language_to_file_history_blacklist.cs
NO
Actually add the parameters to the command.  They were created but not added, so if any movies were actually in the database the migrations would fail.
EnorMOZ confirmed fix works on discord.
* Fixes sentry RADARR3-5W
> Fixed: Correctly add parameters to migrations 36 and 154

- src/NzbDrone.Core.Test/NetImport/NetImportSearchServiceFixture.cs
- src/NzbDrone.Core/NetImport/NetImportSearchService.cs
NO
- Fixes issue with lists where items are cleaned from library if IMDB received from list, but no TMDB (Steven Lu)
- Don't map TMDB if it came from list already
- Add Fixture for NetImportSync
Fixes #4014 
* #
> Fixed: Don't Clean list movies if IMDB Match

- src/NzbDrone.Core.Test/CustomFormats/CustomFormatsFixture.cs
- src/NzbDrone.Core.Test/CustomFormats/QualityTagFixture.cs
- src/NzbDrone.Core.Test/DecisionEngineTests/CustomFormatAllowedByProfileSpecificationFixture.cs
- src/NzbDrone.Core.Test/DecisionEngineTests/CutoffSpecificationFixture.cs
- src/NzbDrone.Core.Test/DecisionEngineTests/PrioritizeDownloadDecisionFixture.cs
- src/NzbDrone.Core.Test/MediaFiles/MovieImport/Aggregation/Aggregators/AggregateQualityFixture.cs
- src/NzbDrone.Core.Test/MediaFiles/UpdateMovieFileQualityServiceFixture.cs
- src/NzbDrone.Core.Test/MovieTests/MovieRepositoryTests/MovieRepositoryFixture.cs
- src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/AugmentersTests/AugmentWithParsedMovieInfo.cs
- src/NzbDrone.Core.Test/Profiles/ProfileRepositoryFixture.cs
- src/NzbDrone.Core.Test/Profiles/ProfileServiceFixture.cs
- src/NzbDrone.Core.Test/Qualities/QualityModelComparerFixture.cs
- src/NzbDrone.Core/Qualities/QualityModelComparer.cs
NO
- If formats are not used mutually exclusive, but instead more as preferred words its possible to upgrade if cutoff is already met. Cutoff status is currently calculated by summing the compare values from the different formats to the cutoff. So if one format is over cutoff, but two are below you can have a negative compare value despite being over cutoff, thus allowing a new download to grab.
> Treat any CF over FormatCutoff as being Cutoff met

- azure-pipelines.yml
NO
No that logic is correct on backed builds on main branch always build light because there are no changes when comparing head to itself (origin/Aphrodite). This will force all branch builds to be full builds
> Fixed: Always full build on branch builds

- src/NzbDrone.Core/Indexers/Newznab/Newznab.cs
This works for Sonarr, can Radarr also add custom categories like this?
NO
Added existing and future UHD, X265, WEB-DL categories to NZB Finder indexer.
* #Radarr not finding releases in the proper categories
> Added UHD, X265, WEB-DL etc. to NZB Finder

- src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs
NO
Changes log years to 4 digits... I can't think of any reason against this (other than size, which is negligible)
Fixes #4053
> Fixed: 4 digit year for log lines

- azure-pipelines.yml
- build.sh
- src/Directory.Build.props
- src/Directory.Build.targets
- test.sh
NO
The windows build was generating old-style PDB for net core output which don't produce line numbers in stack traces on linux.  Only force `full` pdb for the `net462` build.
> Fixed: Use portable pdb on net core

- src/NzbDrone.Core.Test/Datastore/WhereBuilderFixture.cs
- src/NzbDrone.Core/Datastore/WhereBuilder.cs
- src/NzbDrone.Core/Movies/MovieRepository.cs
NO
Fix NRE in where builder if you pass in a string variable that's null to the query.  Also prevent such a query from being attempted in the first place.
* Fixes Sentry RADARR3-6V
* Fixes Sentry RADARR3-B4
> Fixed: WhereBuilder exception when string variable null

- frontend/src/Movie/MoveMovie/MoveMovieModal.js
- src/NzbDrone.Api/Config/MediaManagementConfigResource.cs
- src/NzbDrone.Api/Movies/MovieEditorModule.cs
- src/NzbDrone.Api/Movies/MovieResource.cs
- src/NzbDrone.Core.Test/Datastore/WhereBuilderFixture.cs
- src/NzbDrone.Core.Test/MediaFiles/ImportApprovedMoviesFixture.cs
- src/NzbDrone.Core.Test/MovieTests/MovieFolderPathBuilderFixture.cs
- src/NzbDrone.Core.Test/MovieTests/MovieServiceTests/UpdateMultipleMoviesFixture.cs
- src/NzbDrone.Core.Test/NetImport/NetImportSearchServiceFixture.cs
- src/NzbDrone.Core/Configuration/ConfigService.cs
- src/NzbDrone.Core/Configuration/IConfigService.cs
- src/NzbDrone.Core/Datastore/Migration/167_remove_movie_pathstate.cs
- src/NzbDrone.Core/MediaFiles/MovieFile.cs
- src/NzbDrone.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs
- src/NzbDrone.Core/MediaFiles/RenameMovieFileService.cs
- src/NzbDrone.Core/Movies/Commands/MoveMovieCommand.cs
- src/NzbDrone.Core/Movies/Movie.cs
- src/NzbDrone.Core/Movies/MoviePathBuilder.cs
- src/NzbDrone.Core/Movies/MovieService.cs
- src/NzbDrone.Core/Movies/RefreshMovieService.cs
- src/NzbDrone.Core/NetImport/NetImportSearchService.cs
- src/NzbDrone.Core/Organizer/FileNameBuilder.cs
- src/Radarr.Api.V3/Config/MediaManagementConfigResource.cs
- src/Radarr.Api.V3/MovieFiles/MovieFileResource.cs
- src/Radarr.Api.V3/Movies/MovieEditorModule.cs
- src/Radarr.Api.V3/Movies/MovieModule.cs
- src/Radarr.Api.V3/Movies/MovieResource.cs
YES [167 - Remove Static/Dynamic Config Values and PathState]
Remove Static/Dynamic config values per movie and in media management, Allow folder name change during movie move in editor or edit. 
Fixes #3969 
Fixes #1787
> Fixed: Remove Static/Dynamic Settings, Allow Folder Move from Editor

- src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
NO
If movie exists on movie/lookup api call, return that movie object instead of the search result from TMDB.
Fixes issue found by @v0idp, pulled from Sonarr V3
> Fixed: Populate Info in Lookup Results if Existing Movie

- src/NzbDrone.Core/Indexers/Torznab/TorznabRssParser.cs
After looking through the [Jackett source code](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Models/ReleaseInfo.cs#L25) and raw XML responses from it, as well as reading through the [Torznab "specification" over at Sonarr](https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer#torznab-results), I'm rather certain that IMDb IDs are returned in their integer form. This means that the current IMDb handling in Radarr's Torznab indexer is quite broken since it assumes that IMDb IDs are in their string form (aka. prefixed with `tt`) and substrings them.
Taking a closer look at the indexer code, it actually seems to substring the IMDb IDs twice - so even if the IMDb IDs returned from the Torznab indexer were in their string form, it would still turn the IDs …
> Fix IMDb ID handling for Torznab indexers

- src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
NO
Added `Radarr_Movie_Year` to the environment variables passed to custom post-processing 'On Grab' scripts.
Did not give it a default empty string value because I believe that every movie entry in the DB has a `Year`, like it has a `TmdbId`.
N/A
> New: Add Year to Custom Script

- src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
NO
Added `Radarr_Movie_Year` to the environment variables passed to custom scripts.
Did not give it a default empty string value because I believe that every movie entry in the DB has a `Year`, like it has a `TmdbId`.
N/A
> New: Add Year to Custom Script (aphrodite)

- src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
NO
Uses the release date from TMDB to set year instead of looping thru all release dates for earliest. (This can grab limited premiers, etc..) and creates year differences at time between cinema date and year.
Fixes #4074 
Fixes #4161
> Fixed: Use TMDB ReleaseDate Year for Year (Match Cinema Date)

- azure-pipelines.yml
- build.sh
- src/NzbDrone.Core.Test/Framework/DbTest.cs
- src/NzbDrone.Core.Test/Framework/DbTestCleanup.cs
- src/NzbDrone.Core/Datastore/Migration/166_fix_tmdb_list_config.cs
- src/NzbDrone.Integration.Test/IntegrationTestCleanup.cs
- src/NzbDrone.Test.Common/NzbDroneRunner.cs
NO
- Cache database to avoid repeatedly re-initializing
- Pull over Lidarr `build.sh` fixes to only build one RID for Sonar
> Fixed: Speed up azure build/test

- src/NzbDrone.Core.Test/HealthCheck/Checks/ImportMechanismCheckFixture.cs
- src/NzbDrone.Core/HealthCheck/Checks/ImportMechanismCheck.cs
NO
This check was put into place during the Sonarr implementation of completed download handling, if the config value is not defined the health issue throws despite the default value for enabled being true. This change modifies the health check to only look to see if the value is true, not that the config value is explicitly defined in the db. 
Currently new users get false warnings given we no longer write the `enabledCompletedHandling` config value explicitly in a migration. This is easily mitigated by toggling the option in settings.
> Fixed: Check for EnableCompletedDownloadHandling Enabled, Not Defined

- src/Radarr.Api.V3/Profiles/Quality/QualityProfileModule.cs
NO
Validator was preventing saving with a legitimate min cutoff score.
Either sum of positive scores must be greater than cutoff, or (only applicable when all scores are negative) the maximum score must be greater than the cutoff.
> Fixed: Allow saving profiles with large negative CF scores

- frontend/src/Settings/Quality/Definition/QualityDefinition.css
- frontend/src/Settings/Quality/Definition/QualityDefinition.js
- frontend/src/Settings/Quality/Definition/QualityDefinitionConnector.js
- package.json
- src/NzbDrone.Core.Test/DecisionEngineTests/PrioritizeDownloadDecisionFixture.cs
- src/NzbDrone.Core/Datastore/Migration/171_quality_definition_preferred_size.cs
- src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs
- src/NzbDrone.Core/DecisionEngine/DownloadDecisionPriorizationService.cs
- src/NzbDrone.Core/Qualities/Quality.cs
- src/NzbDrone.Core/Qualities/QualityDefinition.cs
- src/Radarr.Api.V3/Qualities/QualityDefinitionResource.cs
- yarn.lock
YES (171 PreferredSize Column to Quality Definitions)
Adds third slider to quality definitions, prioritize downloads based on closest to preferred size. This allows user to spec if they want smallest, largest, or someone in between for a given quality
Fixes #4118 
Fixes #3659 ? I thought it already worked like this...
> New: Quality Preferred Setting

- src/NzbDrone.Core.Test/Download/Pending/PendingReleaseRepositoryFixture.cs
- src/NzbDrone.Core.Test/Extras/SubtitleFileRepositoryFixture.cs
- src/NzbDrone.Core.Test/Housekeeping/Housekeepers/CleanupOrphanedExtraFilesFixture.cs
- src/NzbDrone.Core.Test/Housekeeping/Housekeepers/CleanupOrphanedSubtitleFilesFixture.cs
- src/NzbDrone.Core/Download/Pending/PendingReleaseRepository.cs
- src/NzbDrone.Core/Extras/Files/ExtraFileRepository.cs
- src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedExtraFiles.cs
- src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedSubtitleFiles.cs
NO
When deleting `ExtraFiles` and `PendingReleases` by `MovieId`, the record with `Id`= to `MovieId` was being deleted instead of any records with that `MovieId`. 
Corrected deletion, added housekeepers for other extra and subtitle files. Housekeeper already exists for `PendingReleases`
> Fixed: ExtraFiles and PendingReleases not deleted correctly

- frontend/src/Settings/MediaManagement/Naming/Naming.js
NO
See https://github.com/Sonarr/Sonarr/pull/3703
Goal is to clarify the help text to indicate that the setting explicitly is for replacing illegal characters, and not enabling it will cause Radarr to remove them instead.
* #
> Clarify Replace Illegal Characters setting

- src/NzbDrone.Core/Jobs/TaskManager.cs
- src/NzbDrone.Core/Update/Commands/ApplicationCheckUpdateCommand.cs
- src/NzbDrone.Core/Update/InstallUpdateService.cs
NO
Split ApplicationUpdateCommand to two commands so that we don't lock up command queue if we know we are not going to update (docker, external, update disabled, etc)
* #
> Fixed: Don't lock command queue if updating is disabled

- .gitignore
- src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/AugmentersTests/AugmentWithHistoryFixture.cs
- src/NzbDrone.Core/Parser/Augmenters/AugmentWithHistory.cs
NO
Backport a19bcf968 to 0.2: prevent multiple duplicates being grabbed due to size custom formats being incorrectly calculated from history
* Fixes #4262
> Fix queue dupe develop

- src/NzbDrone.Common.Test/DiskTests/DiskProviderFixtureBase.cs
- src/NzbDrone.Common/Disk/DiskProviderBase.cs
- src/NzbDrone.Mono/Disk/DiskProvider.cs
NO
This reverts commit 10fc0b071fae9807fa456144b0708d95574d17ff.  Use the
mono fix from 43a35c84477fd194eaa816f1b3e4ade6cb4af42a in NET Core also
> Fixed: NET Core not deleting source when moving across drives

- src/NzbDrone.Core.Test/HealthCheck/Checks/MonoNotNetCoreCheckFixture.cs
- src/NzbDrone.Core/HealthCheck/Checks/MonoNotNetCoreCheck.cs
NO
Nudge people to move to net core if they upgraded a native linux install to the mono aphrodite build.
Disabled on ARM Synology (where I think docker is not supported) and BSD.
> New: HealthCheck to warn if running legacy mono version

- frontend/src/Movie/MovieFileStatus.js
- frontend/src/Store/Actions/movieActions.js
this is a follow-up to commit:
https://github.com/Radarr/Radarr/commit/64e9e48217002604c36a778d485c23b32352f72e
NO
I had actually already made this change in the branch: https://github.com/geogolem/Radarr/tree/MovieStatusFix
and PR: https://github.com/Radarr/Radarr/pull/4012
however, this change is really separate and since the issue came up recently with the commit, it seems prudent to separate this change out from the simple colour change in the branch MovieStatusFix.
> Fixed: "Not Available" instead of "?" when no InCinemas date (Follow-up)

- src/NzbDrone.Core/NetImport/Trakt/TraktImportBase.cs
- src/NzbDrone.Core/NetImport/Trakt/TraktSettingsBase.cs
NO
Switch to `https://auth.servarr.com` for handling trakt auth.  Once users token's expire (3 months after last renew) they'll need to manually re-auth with the new server.
> Swap to servarr trakt auth

- src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
Sorry for the double pull request, I hadn't realized I was previously working on V3. 
Added Dolby Digital Plus with Atmos by checking the codec additional features for JOC, which stands for Joint Object Coding and is the technique used for adding Atmos metadata to Dolby Digital Plus audio streams. This is similar to the 16-ch additional feature used to distinguish Atmos in a TrueHD audio stream.
> Added Dolby Digital Plus with Atmos

- src/UI/index.html
- src/UI/login.html
NO
When serving Radarr behind an authentication proxy (ex. https://github.com/pusher/oauth2_proxy) the manifest request will fail because cookies are not sent with the manifest request.
See https://developer.mozilla.org/en-US/docs/Web/Manifest:
> Note: If the manifest requires credentials to fetch - the `crossorigin` attribute must be set to `"use-credentials"`, even if the manifest file is in the same origin as the current page.
This PR adds the necessary attribute so that cookies will be sent with manifest requests.
None
None
> Add crossorigin use-credentials attribute to manifest tag

- src/NzbDrone.Core.Test/HealthCheck/Checks/NetImportStatusCheckFixture.cs
- src/NzbDrone.Core.Test/NetImport/NetImportStatusServiceFixture.cs
- src/NzbDrone.Core/Datastore/Migration/173_net_import_status.cs
- src/NzbDrone.Core/Datastore/TableMapping.cs
- src/NzbDrone.Core/HealthCheck/Checks/NetImportStatusCheck.cs
- src/NzbDrone.Core/NetImport/CouchPotato/CouchPotatoImport.cs
- src/NzbDrone.Core/NetImport/HttpNetImportBase.cs
- src/NzbDrone.Core/NetImport/NetImportBase.cs
- src/NzbDrone.Core/NetImport/NetImportStatus.cs
- src/NzbDrone.Core/NetImport/NetImportStatusRepository.cs
- src/NzbDrone.Core/NetImport/NetImportStatusService.cs
- src/NzbDrone.Core/NetImport/RSSImport/RSSImport.cs
- src/NzbDrone.Core/NetImport/Radarr/RadarrImport.cs
- src/NzbDrone.Core/NetImport/RadarrList/RadarrListImport.cs
- src/NzbDrone.Core/NetImport/StevenLu/StevenLuImport.cs
- src/NzbDrone.Core/NetImport/TMDb/Collection/TMDbCollectionImport.cs
- src/NzbDrone.Core/NetImport/TMDb/List/TMDbListImport.cs
- src/NzbDrone.Core/NetImport/TMDb/Person/TMDbPersonImport.cs
- src/NzbDrone.Core/NetImport/TMDb/Popular/TMDbPopularImport.cs
- src/NzbDrone.Core/NetImport/TMDb/TMDbImportBase.cs
- src/NzbDrone.Core/NetImport/TMDb/User/TMDbUserImport.cs
- src/NzbDrone.Core/NetImport/Trakt/List/TraktListImport.cs
- src/NzbDrone.Core/NetImport/Trakt/Popular/TraktPopularImport.cs
- src/NzbDrone.Core/NetImport/Trakt/TraktImportBase.cs
- src/NzbDrone.Core/NetImport/Trakt/User/TraktUserImport.cs
YES (NetImportStatus Table)
Adds Status checks for lists similar to indexers and clients. If a list fails backoff on how often we call to that list until it comes back online. Warn users of failures via health check.
> New: List Status Checks/Backoffs

- src/NzbDrone.Api/Config/IndexerConfigResource.cs
- src/NzbDrone.Core.Test/Framework/CoreTest.cs
- src/NzbDrone.Core.Test/MediaFiles/ImportApprovedMoviesFixture.cs
- src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs
- src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/GetMovieFixture.cs
- src/NzbDrone.Core.Test/ParserTests/SceneCheckerFixture.cs
- src/NzbDrone.Core/Configuration/ConfigService.cs
- src/NzbDrone.Core/Configuration/IConfigService.cs
- src/NzbDrone.Core/Datastore/Migration/117_update_movie_file.cs
- src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs
- src/NzbDrone.Core/DecisionEngine/DownloadDecisionPriorizationService.cs
- src/NzbDrone.Core/Extras/Metadata/Consumers/Roksbox/RoksboxMetadata.cs
- src/NzbDrone.Core/Extras/Metadata/Consumers/Wdtv/WdtvMetadata.cs
- src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
- src/NzbDrone.Core/MediaFiles/DownloadedMovieImportService.cs
- src/NzbDrone.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs
- src/NzbDrone.Core/MediaFiles/MovieImport/ImportDecisionMaker.cs
- src/NzbDrone.Core/MediaFiles/MovieImport/Manual/ManualImportService.cs
- src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
- src/NzbDrone.Core/NetImport/RSSImport/RSSImportParser.cs
- src/NzbDrone.Core/Organizer/FileNameValidationService.cs
- src/NzbDrone.Core/Parser/Model/ParsedMovieInfo.cs
- src/NzbDrone.Core/Parser/Parser.cs
- src/NzbDrone.Core/Parser/ParsingLeniency.cs
- src/NzbDrone.Core/Parser/ParsingService.cs
- src/NzbDrone.Core/Parser/SceneChecker.cs
- src/Radarr.Api.V3/Config/IndexerConfigResource.cs
NO
The Regex for German and french tracker formats (ReportMovieTitleLenientRegexBefore) has been updated to support the same editions as the English versions, but the regex is only used if ParsingLeniency is set to Lenient. Should resolve a lot of cases for German releases where the movieTitle wasn't parsed correctly before. Also some fixes for movieTitles with dots in the name. Also fixed langauge and edition parsing if a language or edition name is present in the movie title.
* Closes #2129, closes #4394 and closes #4140
Discuss how we are going to continue with the lenient parsing option
After upgrade to v3, if you enabled lenient parsing before, it is still set to true, but you don't notice it because there is no UI.
I would consider the following options:
1. Make a migration and …
> Lenient parsing and German regex updates

- src/NzbDrone.Core.Test/MediaFiles/MovieImport/DetectSampleFixture.cs
- src/NzbDrone.Core/MediaFiles/MediaFileExtensions.cs
- src/NzbDrone.Core/MediaFiles/MovieImport/DetectSample.cs
NO
Fix file scan ignoring DVD image files (iso, img, vob, m2ts)
Always allow DVD and BR file types without analysis, instead of detecting as 0 runtime.
Bonus bug fix: Add support for video files with non-lowercase extensions.
* #809
> Fix file scan ignoring DVD image files (iso, img, m2ts)

- src/NzbDrone.Core/CustomFormats/CustomFormatCalculationService.cs
NO
Since the lenient parser removal, checking for scene name has become much more strict so it is often missing. If missing, try matching custom formats against original filename as well as the current filename.
* Fixes #4529
> Fixed: Use originalFilePath in CF if scene name missing

- src/NzbDrone.Core/Datastore/Converters/StringConverter.cs
- src/NzbDrone.Core/Datastore/Migration/166_fix_tmdb_list_config.cs
NO
Add int to string converter to migration 166. There are cases where minVotes is stored in the v0.2 db as a int. This causes migration to blow up from v0.2 to v3. Workaround this by converting int values to string when string is typed. 
MinVotes was a int until this change <https://github.com/Radarr/Radarr/commit/4d745d360013e6be0cc588664f6ba746a0a404d2> in 2017
Any list created before that would hold an Int value instead of the string value it is today.
> Fixed: In some cases MinVotes is int from v0.2, causes migration failure

- src/NzbDrone.Common.Test/ServiceProviderTests.cs
- src/NzbDrone.Core.Test/Datastore/Migration/178_new_list_serverFixture.cs
- src/NzbDrone.Core/Datastore/Migration/178_new_list_server.cs
- src/NzbDrone.Core/NetImport/NetImportType.cs
- src/NzbDrone.Core/NetImport/RSSImport/RSSImport.cs
- src/NzbDrone.Core/NetImport/RadarrList/RadarrListImport.cs
- src/NzbDrone.Core/NetImport/RadarrList/RadarrListSettings.cs
- src/NzbDrone.Core/NetImport/RadarrList2/IMDb/IMDbListImport.cs
- src/NzbDrone.Core/NetImport/RadarrList2/IMDb/IMDbListRequestGenerator.cs
- src/NzbDrone.Core/NetImport/RadarrList2/IMDb/IMDbListSettings.cs
- src/NzbDrone.Core/NetImport/RadarrList2/RadarrList2Parser.cs
- src/NzbDrone.Core/NetImport/RadarrList2/RadarrList2RequestGenerator.cs
- src/NzbDrone.Core/NetImport/RadarrList2/StevenLu/StevenLu2Import.cs
- src/NzbDrone.Core/NetImport/RadarrList2/StevenLu/StevenLu2RequestGenerator.cs
- src/NzbDrone.Core/NetImport/RadarrList2/StevenLu/StevenLu2Settings.cs
- src/NzbDrone.Core/NetImport/StevenLu/StevenLuImport.cs
YES (178)
Use new metadata server for IMDB lists.
Should fix the missing items on existing server (stale as of September 2019).  Items are returned with metadata already mapped.
Existing RadarrLists are migrated to IMDB lists if they have the correct URL form [see here](https://github.com/Radarr/Radarr/wiki/Supported-NetImports#currently-supported-endpoints).
Ones that don't match this form have the settings combined: `BaseURL + Path -> Url`
Existing standard StevenLu lists are migrated to `StevenLu2Import` with easier settings.  Existing type is untouched for alternative urls, eg https://aapjeisbaas.nl/api/v1/popular-movies/imdb?fresh=True&max=20&rating=6&votes=50000
The existing old style `RadarrList` and `StevenLu` lists are moved into an `Advanced` section at the bottom of the List …
> New: Use new metadata server for imdb/stevenlu lists

- src/NzbDrone.Core.Test/Datastore/SqliteSchemaDumperTests/SqliteSchemaDumperFixture.cs
- src/NzbDrone.Core/Datastore/Migration/Framework/SqliteSyntaxReader.cs
NO
Fix sqlite schema dumper for tables like
```
CREATE TABLE IF NOT EXISTS "NamingConfig" (
"Id"    INTEGER NOT NULL,
"MultiEpisodeStyle"     INTEGER NOT NULL,
"RenameEpisodes"        INTEGER,
"ReplaceIllegalCharacters"      INTEGER NOT NULL,
"StandardMovieFormat"   TEXT,
"MovieFolderFormat"     TEXT,
"ColonReplacementFormat"        INTEGER NOT NULL DEFAULT 0,
PRIMARY KEY("Id" AUTOINCREMENT)
);
```
The old code wasn't correctly delimiting the end of a string token.
* #
> Fixed: SqliteSchemaDumper with separate Primary Key clause

- src/NzbDrone.Core.Test/Datastore/Migration/154_add_language_to_files_history_blacklistFixture.cs
- src/NzbDrone.Core/Datastore/Migration/154_add_language_to_file_history_blacklist.cs
YES (Modified)
This is a bit atrocious now, but seems to work..
For MediaFiles this changes behavior to the following. First if MediaInfo `AudioLanguages` field is populated in DB, use that for languages as it will be the most accurate. Fallback to a `LanguageParser.ParseLanguages` by the `SceneTitle`. If `SceneTitle` doesn't exist it will fall back to the profile language (but `Any` is mapped to English). 
During the MediaFiles loop, a release dictionary will be created by the `SceneTitle` field with the Language values parsed above assigned as a value to the release key. Next we assign languages to history. First we look to see if the `History.SourceTitle` is in the release dictionary created above, if so use those languages. If not fallback to a `LanguageParser.ParseLanguages` on the …
> Fixed: Language Migration Assigning 'Any' to MovieFiles and History

- src/NzbDrone.Core.Test/MediaFiles/MovieImport/Specifications/NotMultiDiscSpecificationFixture.cs
- src/NzbDrone.Core/MediaFiles/MovieImport/Specifications/NotMultiDiscSpecification.cs
NO
Instead of trying to import and only getting part, reject movie if they look like multi-part until we add support
Relates to #145
* #
> New: Reject Files at Import if they are Multi-Part for now

- src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
NO
Use our endpoint instead of hitting TMDB. Should we round off the date time to nearest 10/15 minutes or so to help with caching, or is this endpoint not cached? Currently it will send like this:
`https://radarrapi.servarr.com/v1/movie/changed?since=2020-07-20T12:48:05.4355917Z`
15 minutes would take us to 96 possible cache points daily from infinite as it is now
> Use Radarr API change feed for changed movies

- src/NzbDrone.Core.Test/MediaFiles/DiskScanServiceTests/ScanFixture.cs
- src/NzbDrone.Core.Test/MetadataSource/SkyHook/SkyHookProxyFixture.cs
- src/NzbDrone.Core.Test/ParserTests/NormalizeTitleFixture.cs
- src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs
- src/NzbDrone.Core/Datastore/Migration/179_movie_translation_indexes.cs
- src/NzbDrone.Core/MediaFiles/DiskScanService.cs
- src/NzbDrone.Core/MediaFiles/MovieImport/Manual/ManualImportService.cs
- src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
- src/NzbDrone.Core/Movies/AddMovieService.cs
- src/NzbDrone.Core/Movies/AlternativeTitles/AlternativeTitle.cs
- src/NzbDrone.Core/Movies/MovieRepository.cs
- src/NzbDrone.Core/Movies/MovieService.cs
- src/NzbDrone.Core/Parser/Parser.cs
- src/NzbDrone.Core/Parser/ParsingService.cs
NO
A few improvements to parsing and scanning
- Filter inline extra files so they don't get imported over movies
- Include `Sample` subdirectory in extra folders filter
- Use Translations for Movie Mapping
Fixes #4630 
Fixes #4587
* #
> Parsing improvements

- src/NzbDrone.Core.Test/Datastore/Migration/178_new_list_serverFixture.cs
- src/NzbDrone.Core/Datastore/Migration/178_new_list_server.cs
NO
Fix migration 178 to deal with trailing slash in list id and API URL
> Fix migration 178 to cope with leading/trailing slashes

- src/NzbDrone.Core.Test/MediaFiles/MovieImport/Specifications/NotMultiPartSpecificationFixture.cs
- src/NzbDrone.Core/MediaFiles/MovieImport/Specifications/NotMultiPartSpecification.cs
NO
Multi-Part Rejections Take 2
This time we check file for multi-part identifier then look for other files in the folder that look like multi-part and that match naming of the file in question for import
Fixes #4642 
* #
> New: Reject Multi-Part Files from Import - Take 2

- src/NzbDrone.Core/Indexers/Torznab/Torznab.cs
NO
Updated the default Jackett link to use the new api.
**Fixed version of PR #4790**
> Fix: Update default Jackett torznab link to api v2.0

- src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/MapFixture.cs
- src/NzbDrone.Core/Extras/ExtraService.cs
- src/NzbDrone.Core/Extras/Files/ExtraFileManager.cs
- src/NzbDrone.Core/Extras/Others/OtherExtraService.cs
- src/NzbDrone.Core/IndexerSearch/NzbSearchService.cs
- src/NzbDrone.Core/Parser/ParsingService.cs
NO
Use translations when parsing by search criteria so we don't miss anything. Also, ensure that we don't accept a movie if it is a year mismatch in some cases. 
Ex. Wrath of God 1968 vs The Wrath of God 1972
`The.Wrath.Of.God.1968.DVDRIP.XVID-CG` gets matched to the 1972 version and imported despite the year mismatch.
Fixes #4794 
Fixes #3006
Fixes #4824 
* #
> Parser improvements 2

- src/NzbDrone.Core.Test/Datastore/Migration/180_fix_invalid_profile_referencesFixture.cs
- src/NzbDrone.Core/Datastore/Migration/180_fix_invalid_profile_references.cs
YES
This solves the issue where a movie or list is attached to a profile that does not exists... however this will fail if there are movies and lists that have a profile, but there are no profiles in the db at all. (probably pretty rare)
Fixes #4662 
Fixes #4396
> Fixed: Fix Movies, Lists with Invalid Profile on Migration

- src/NzbDrone.Core.Test/Housekeeping/Housekeepers/CleanupOrphanedMovieMovieFileIdsFixture.cs
- src/NzbDrone.Core.Test/ProviderTests/RecycleBinProviderTests/DeleteFileFixture.cs
- src/NzbDrone.Core/Extras/Files/ExtraFileService.cs
- src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedMovieMovieFileIds.cs
- src/NzbDrone.Core/MediaFiles/UpgradeMediaFileService.cs
NO
- Housekeeper to Fix issues with MovieFileId in Movie Table
- Actually make sub folders in recycling bin when deleting something on update or extra files
- Cleanup leftovers from old folder naming
> Fixed: Fix Instances where DB MovieFileId Relationship is Screwy

- src/NzbDrone.Core.Test/MediaFiles/ImportApprovedMoviesFixture.cs
- src/NzbDrone.Core/MediaFiles/MovieImport/ImportApprovedMovie.cs
NO
Add some older commits to fix case where an API call is made to trigger import of a tracked download from a directory that's not a child of the tracked download output folder I.e. where a post processing script has moved things around
> Sonarr import processing pulls

- frontend/src/Settings/Notifications/Notifications/Notification.js
- frontend/src/Settings/Notifications/Notifications/NotificationEventItems.js
- src/NzbDrone.Api/Notifications/NotificationModule.cs
- src/NzbDrone.Api/Notifications/NotificationResource.cs
- src/NzbDrone.Core.Test/NotificationTests/NotificationBaseFixture.cs
- src/NzbDrone.Core/Datastore/Migration/182_on_delete_notification.cs
- src/NzbDrone.Core/Datastore/TableMapping.cs
- src/NzbDrone.Core/Notifications/DeleteMessage.cs
- src/NzbDrone.Core/Notifications/INotification.cs
- src/NzbDrone.Core/Notifications/NotificationBase.cs
- src/NzbDrone.Core/Notifications/NotificationDefinition.cs
- src/NzbDrone.Core/Notifications/NotificationFactory.cs
- src/NzbDrone.Core/Notifications/NotificationService.cs
- src/NzbDrone.Core/Notifications/Trakt/Trakt.cs
- src/NzbDrone.Core/Notifications/Trakt/TraktProxy.cs
- src/NzbDrone.Core/Notifications/Trakt/TraktService.cs
- src/Radarr.Api.V3/Notifications/NotificationResource.cs
YES - needed to add migration 182 --> on_delete_notification
This will notify Trakt to remove an item from Collection when a movie file is deleted. On delete must be selected and enabled for the Trakt Connection
https://github.com/Radarr/Radarr/issues/4521
Another feature still needs to be implemented. A button to manually trigger a full sync should be added still - that will be handled in a different PR in the future.
* #
> Add OnDelete Notification to TraktConnection 

- src/NzbDrone.Core.Test/MovieTests/MovieIsAvailableFixture.cs
- src/NzbDrone.Core/Movies/Movie.cs
NO
if minimumAvailability is set to InCinemas,
InCinemas has no value but physical/digital release dates
are known and passed, movie would be marked as Not Available
When it should be Missing.
Fixes https://github.com/Radarr/Radarr/issues/4920
* #
> Fixed: IsAvailable not Right for minAvailability = InCinemas

- frontend/src/DiscoverMovie/DiscoverMovie.js
NO
Fix issue where options button gets into a state of disabled with no way to re-enable it unless you add a list with movies in it
If you have no lists or a list with no movies in it & disable the use recommendations option the Options button becomes disabled with no way to turn the recommendations back on. Would be forced to add a list and a movie to it just to re-enable the button.
No side effects from simply leaving the button enabled.
> Fix issue where options button on discover becomes un-usable

- frontend/src/Calendar/CalendarConnector.js
- frontend/src/Components/Label.css
- frontend/src/Components/ProgressBar.css
- frontend/src/Helpers/Props/kinds.js
- frontend/src/Movie/Details/MovieDetails.js
- frontend/src/Movie/Details/MovieDetailsConnector.js
- frontend/src/Movie/Details/MovieStatusLabel.css
- frontend/src/Movie/Details/MovieStatusLabel.js
- frontend/src/Movie/Index/MovieIndexConnector.js
- frontend/src/Movie/Index/MovieIndexFooter.css
- frontend/src/Movie/Index/MovieIndexFooter.js
- frontend/src/Movie/Index/MovieIndexItemConnector.js
- frontend/src/Movie/Index/Overview/MovieIndexOverview.css
- frontend/src/Movie/Index/Overview/MovieIndexOverview.js
- frontend/src/Movie/Index/Posters/MovieIndexPoster.js
- frontend/src/Movie/Index/ProgressBar/MovieIndexProgressBar.js
- frontend/src/Movie/Index/Table/MovieIndexRow.js
- frontend/src/Movie/MovieFileStatus.js
- frontend/src/Movie/MovieFileStatusConnector.js
- frontend/src/Store/Actions/queueActions.js
- frontend/src/Styles/Variables/colors.js
- frontend/src/Utilities/Movie/getProgressBarKind.js
- frontend/src/Utilities/Movie/getQueueStatusText.js
- src/NzbDrone.Core/Localization/Core/en.json
NO
Fixed: Address issues with the status being wrong color on the index and movie details (not tracking anything queued/downloading)
Fixed: Updated fetchQueueDetails() to not pass movie ids since the store doesn't use them anyways
New: Added text to index poster (poster & overview views) progress bar showing status
Fixes #4525
Fixes #4526
Fixes #4982
> Fix issues with status color on movies index & details

- src/NzbDrone.Core/MediaCover/ImageResizer.cs
- src/NzbDrone.Core/Radarr.Core.csproj
NO
Bumps ImageSharp to 1.0 final instead of using beta package
> Bump ImageSharp to stable package 1.0.1 [Common]

- src/NzbDrone.Core/ImportLists/RadarrList2/IMDb/IMDbListImport.cs
- src/NzbDrone.Core/ImportLists/RadarrList2/IMDb/IMDbListParser.cs
- src/NzbDrone.Core/ImportLists/RadarrList2/IMDb/IMDbListRequestGenerator.cs
- src/NzbDrone.Core/ImportLists/RadarrList2/RadarrList2Parser.cs
- src/NzbDrone.Core/ImportLists/RadarrList2/RadarrList2RequestGenerator.cs
NO
Use IMDB /export tsv for user lists to avoid our 12 hour cache
> New: Avoid cache on IMDb user lists

- src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabCapabilitiesProviderFixture.cs
- src/NzbDrone.Core/Indexers/HttpIndexerBase.cs
- src/NzbDrone.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs
- src/NzbDrone.Core/Indexers/Newznab/NewznabRssParser.cs
NO
Handle ratelimit api response for newznab caps endpoint on certain newznab indexers that have caps behind the apikey
PS: I dont think this one cherry-picked right but im not gonna mess with it so, sorry Taloth! Def not trying to take credit :)
Fixes: #5054
> Handle ratelimit api response for newznab caps endpoint on certain newznab indexers that have caps behind the apikey

- src/NzbDrone.Core.Test/RootFolderTests/RootFolderServiceFixture.cs
- src/NzbDrone.Core/RootFolders/RootFolderService.cs
NO
- Avoid calling to All() Movies when fetching root folders, use AllMoviePaths() isntead
- Avoid calling to All() on every root folder when getting all root folders (quite slow on 10+ folders)
Performance results: 27 Root Folders (each letter), 450 Movies (rather small)
```
Before
[Debug] Api: [GET] /api/v3/rootFolder: 200.OK (8040 ms)
After
[Debug] Api: [GET] /api/v3/rootFolder: 200.OK (195 ms)
```
Likely Fixes #4905
> Fixed: Speed up Unmapped Folder fetch for large number of root folders

- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
NO
Fixed: Various DTS audio formats and Blu-Ray causing being incorrectly detected as -Group
Fixes: #5088 
Fixes: #5084
> Fixed: Parser Detecting DTS-Audio formats and Blu-Ray as groups

- frontend/src/InteractiveImport/Language/SelectLanguageModalContentConnector.js
- frontend/src/MovieFile/Language/SelectLanguageModalContentConnector.js
- frontend/src/Settings/UI/UISettings.js
- src/NzbDrone.Core.Test/DecisionEngineTests/LanguageSpecificationFixture.cs
- src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
- src/NzbDrone.Core/DecisionEngine/Specifications/LanguageSpecification.cs
- src/NzbDrone.Core/Languages/Language.cs
- src/NzbDrone.Core/Parser/IsoLanguages.cs
- src/NzbDrone.Core/Parser/LanguageParser.cs
- src/Radarr.Api.V3/Calendar/CalendarModule.cs
- src/Radarr.Api.V3/MovieFiles/MovieFileModule.cs
- src/Radarr.Api.V3/Movies/MovieModule.cs
NO
Allow user to select original movie language as wanted language in profile.
Fixes #568
Fixes #3081 
Fixes #5069 
Fixes #3597 
Fixes #4111
> New: Allow Selection Original Movie Languge in Profile

- src/NzbDrone.Common.Test/DiskTests/DiskTransferServiceFixture.cs
- src/NzbDrone.Common/Disk/DiskProviderBase.cs
- src/NzbDrone.Common/Disk/IDiskProvider.cs
- src/NzbDrone.Core.Test/MediaCoverTests/MediaCoverServiceFixture.cs
- src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/GetMovieFixture.cs
- src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/MapFixture.cs
- src/NzbDrone.Core/Datastore/Migration/185_add_alternative_title_indices.cs
- src/NzbDrone.Core/MediaCover/MediaCoverService.cs
- src/NzbDrone.Core/Movies/MovieRepository.cs
- src/NzbDrone.Core/Movies/MovieService.cs
- src/NzbDrone.Core/Parser/ParsingService.cs
- src/Radarr.Api.V3/Movies/MovieModule.cs
YES (185, add CleanTitle indices to Alternative Titles and Translations)
- Fix language mapping
- Grab mediacover fileinfos in one go instead of one at a time
- Get the movies and other components of the response in parallel
- Fix FindByTitle so it doesn't repeat queries to DB
- Fix FindByTitle so it uses the index instead of a table scan
* #
> Fixed: Speed up load and RSS

- src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
- src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadataSettings.cs
- src/NzbDrone.Core/Languages/RealLanguageFieldConverter.cs
NO
Added an option in XBMC Metadata settings to localize the Title and Overview metadata written in the .nfo file if available. If not, it takes the movie Title and Overview like before.
* #5051
> Add Option to localize metadata written in .nfo if available

- src/NzbDrone.Core/Notifications/Discord/Discord.cs
NO
Updated Discord.OnDownload to use Success Colour (green) as per PR [4037](https://github.com/Sonarr/Sonarr/pull/4037) for Sonarr 
* Fixes #5270 
* Fixes #5269
> FIXED: Updated Import for Discord Notifications to use 'Success' Colour

- src/NzbDrone.Common.Test/DiskTests/DiskTransferServiceFixture.cs
- src/NzbDrone.Common/Disk/DiskProviderBase.cs
- src/NzbDrone.Common/Disk/DiskTransferService.cs
- src/NzbDrone.Update/UpdateEngine/InstallUpdateService.cs
NO
Fix: Fixes an issue where paths somehow got stored in the db as lowercase paths which causes a folder to be completely deleted in a case of trying to move the root folder to the same path (used for folder renaming)
Note: This is going to also be an issue in v0.2 but as it is an edge case it isn't being addressed at this time
Fixes #5184 
Fixes #5190
> Fix an issue where lowercase paths can cause media deletion

- src/NzbDrone.Core.Test/HealthCheck/Checks/RemotePathMappingCheckFixture.cs
- src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs
- src/NzbDrone.Core/Download/Clients/Deluge/DelugeLabel.cs
- src/NzbDrone.Core/Download/Clients/Deluge/DelugeProxy.cs
- src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs
NO
- Only run remote path checks when completed download handling is enabled
- Check deluge label for path before falling back to global path for remote mapping checks
Fixes #4803 
Fixes #5251
> Fixed: False Positives for RemotePath check with Deluge

- src/NzbDrone.Core.Test/MediaFiles/MovieFileMovingServiceTests/MoveMovieFileFixture.cs
- src/NzbDrone.Core/MediaFiles/MovieFileMovingService.cs
NO
EnsureFolder in MoveMovieService made assumption that the parent was always the root, thus would fail thinking the root didn't exist when there is nesting in MovieFolder naming. This change calls to the GetBestRootFolderPath to find the root folder instead of assuming the parent.
* Fixes #5247
> Fixed: Nested Folder in MovieFolder Naming not created automatically

- src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
NO
On windows, qbittorrent uses `/` as a path separator in its `files` API.  This causes issues if the torrent only has one file in a subfolder - in this case we just take the full file path with the bad separator.
To workaround, only take the first subfolder just like a multi-file torrent.
* Fixes #5362
* Fixes #5364
> Fixed: Import single file torrents with a folder from QBittorrent

- src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatAudioChannelsFixture.cs
- src/NzbDrone.Core.Test/MediaFiles/MediaInfo/VideoFileInfoReaderFixture.cs
- src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs
- src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoModel.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
- src/NzbDrone.Core/Notifications/Trakt/TraktService.cs
- src/NzbDrone.Core/Organizer/FileNameSampleService.cs
NO
Use _original property for audioChannels as it seems to be more accurate when it exists.
Also fixes cases where DTS-X channel positions are not parsed correctly due to
<https://github.com/MediaArea/MediaInfo/issues/299>
* Fixes #4852
> Fixed: Use audioChannels_Original if it exists in MI

- src/Radarr.Api.V3/Blacklist/BlacklistResource.cs
- src/Radarr.Api.V3/Calendar/CalendarModule.cs
- src/Radarr.Api.V3/History/HistoryModule.cs
- src/Radarr.Api.V3/ManualImport/ManualImportModule.cs
- src/Radarr.Api.V3/ManualImport/ManualImportResource.cs
- src/Radarr.Api.V3/MovieFiles/MovieFileResource.cs
- src/Radarr.Api.V3/Movies/MovieEditorModule.cs
- src/Radarr.Api.V3/Movies/MovieImportModule.cs
- src/Radarr.Api.V3/Movies/MovieLookupModule.cs
- src/Radarr.Api.V3/Movies/MovieModule.cs
- src/Radarr.Api.V3/Movies/MovieResource.cs
- src/Radarr.Api.V3/Queue/QueueResource.cs
NO
When using availability delay setting in Indexer Settings, movies showing in UI as missing vs not-available were not considering the delay setting value. Thus if a movie was releasing in 15 days and delay was set to (-30) Radarr would consider it available and begin looking for it, however this was not reflected in the UI due to IsAvailable not being set correctly when resource mapping.
This changes passes the setting to IsAvailable when its set in the resource mapper to fix UI availability based on the setting used.
~~Tests~~
~~Translation Keys~~
~~Wiki Updates~~
> Fixed: Availability shows incorrect for movies

- src/NzbDrone.Core.Test/HealthCheck/Checks/ReleaseBranchCheckFixture.cs
- src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
- src/NzbDrone.Core/Configuration/DeploymentInfoProvider.cs
- src/NzbDrone.Core/Datastore/Migration/177_language_improvements.cs
- src/NzbDrone.Core/HealthCheck/Checks/ReleaseBranchCheck.cs
- src/NzbDrone.Core/Localization/Core/en.json
YES 
Add a migration to force library refresh to migration 177. Should result in library refresh for future libraries migrated from v0.2 to grab all new metadata
> Add refresh all to migration 177 for v0.2 migrations

- src/NzbDrone.Core/Datastore/Migration/153_indexer_client_status_search_changes.cs
YES (Fix 153)
Migration fails if Sonarr and Radarr have been crossed at some point
* Fixes #5441
> Fixed: Migrate fails for Sonarr contaminated DBs

- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
NO
Fix false positives for remote path health check for qbittorrent - make sure to use category save path if set.
* Fixes #5457
> Fixed: Use QBittorrent category savepath for healthcheck

- src/NzbDrone.Common/Extensions/PathExtensions.cs
- src/NzbDrone.Update/UpdateEngine/BackupAppData.cs
No
On migration we fail to make a backup (but continue with update) if we cannot find radarr.db, this also throws error and pings sentry. We should look for nzbdrone.db if it exists as well
> Fixed: If v0.2 DB Exists back it up during update

- src/NzbDrone.Core.Test/DiskSpace/DiskSpaceServiceFixture.cs
- src/NzbDrone.Core.Test/HealthCheck/Checks/RootFolderCheckFixture.cs
- src/NzbDrone.Core.Test/MovieTests/MovieTitleSlugValidatorFixture.cs
- src/NzbDrone.Core.Test/RootFolderTests/RootFolderServiceFixture.cs
- src/NzbDrone.Core/DiskSpace/DiskSpaceService.cs
- src/NzbDrone.Core/HealthCheck/Checks/MountCheck.cs
- src/NzbDrone.Core/HealthCheck/Checks/RootFolderCheck.cs
- src/NzbDrone.Core/Movies/MovieRepository.cs
- src/NzbDrone.Core/Movies/MovieService.cs
- src/NzbDrone.Core/Movies/MovieTitleSlugValidator.cs
- src/NzbDrone.Core/RootFolders/RootFolderService.cs
- src/NzbDrone.Core/Validation/Paths/MovieAncestorValidator.cs
- src/NzbDrone.Core/Validation/Paths/MoviePathValidation.cs
NO
MovieTitleSlugValidator and MoviePathValidator in AddMovieService both used AllMovies() call to fetch movies and then use one property for validation. This PR changes that by doing the following:
- Change AllMoviePaths() to Dictionary<id, path> so that uses are id aware
- Create AllTitleSlugs() to query the db for just title slugs and avoid the full move deserialization
- Use these functions for validation in lieu of the AllMovie() call
> Don't call AllMovies twice for each AddMovie validation

- src/NzbDrone.Api/Config/MediaManagementConfigModule.cs
- src/NzbDrone.Api/Movies/MovieModule.cs
- src/NzbDrone.Api/RootFolders/RootFolderModule.cs
- src/NzbDrone.Core/Movies/AddMovieValidator.cs
- src/NzbDrone.Core/Validation/Paths/MoviePathValidation.cs
- src/NzbDrone.Core/Validation/Paths/RecycleBinValidator.cs
- src/NzbDrone.Core/Validation/Paths/RootFolderAncestorValidator.cs
- src/Radarr.Api.V3/Config/MediaManagementConfigModule.cs
- src/Radarr.Api.V3/Movies/MovieModule.cs
- src/Radarr.Api.V3/RootFolders/RootFolderModule.cs
NO
Adds additional validation when setting recycle bin to ensure its not a 
- RootFolder
- RootFolder Ancestor
- Movie Folder
- System Folder
- Startup Folder
Also ensure the new recycle bin folder is writable by the user.
Additionally, this adds validation the other way to ensure we are not adding a root folder or movie that is the recycle bin folder
There is probably 100 other ways for a user to screw this up, but this should take care of some obvious ones that could wipe a library.
* Fixes #5447
> New: Add Validations for Recycle Bin Folder [common]

- src/NzbDrone.Host/WebHost/WebHostController.cs
NO
Remove Kestrel's default 28.6MB upload limit
* Fixes #5593
> Fixed: Restoring large database backups

- src/NzbDrone.Core/Movies/MovieRepository.cs
- src/NzbDrone.Core/Movies/MovieService.cs
New: Movies existing in Library no longer show as a Discover Recommendation
New: Improved Discover recommendations
NO
Improved Discover Recommendations so that it returns the 100 most frequently recommended movies from the user's library. This is much better than grabbing the literal `top` 100 recommendations from the table. This will also exclude existing movies in the library from being recommended...that was kinda dumb.
967 Movies
0 Lists
Baseline SQL: 5ms
UI Load (no cache):  2.68s
New SQL: 24ms
UI Load (no cache) : 2.33s
* Fixes #5590
> New: Improved Discover recommendations

- src/NzbDrone.Common/Disk/DiskProviderBase.cs
NO
Workaround net core bug checking folder writable for CIFS shares on linux
* Fixes #5554
> Fixed: FolderWritable check for CIFS shares mounted in Unix

- src/NzbDrone.Core.Test/Datastore/BasicRepositoryFixture.cs
NO
Convert values to UTC during the equivalency assertion so that these tests don't fail when not on UTC
> Fix BasicRepository Tests when not on UTC

- src/Radarr.Http/ByteArrayResponse.cs
- src/Radarr.Http/Frontend/Mappers/HtmlMapperBase.cs
- src/Radarr.Http/Frontend/Mappers/IMapHttpRequestsToDisk.cs
- src/Radarr.Http/Frontend/Mappers/MediaCoverProxyMapper.cs
- src/Radarr.Http/Frontend/Mappers/StaticResourceMapperBase.cs
- src/Radarr.Http/Frontend/StaticResourceModule.cs
[common]
NO
Sometimes the server would hang when too many requests arrive at once - the threadpool would be exhausted and create new threads too slowly to catch up.
This swaps the static resource mapper to run async which helps take some of the load off and seems to stop it locking up so badly.
> Fixed: UI hanging after scrolling movie list too fast

- src/NzbDrone.Host/Bootstrap.cs
- src/NzbDrone.Host/Radarr.Host.csproj
NO
Register additional encodings besides the ones baked in netcore... Will add ~1mb to package size with System.Text.Encoding.CodePages dep.
I'm making an assumption Bootstrap is best place for this? 
Tested with a quick unit test in registering in HttpHeader and running GetEncoding('iso-8859-2), fails before with error from issue, passes with the registration. But I assume it's better to register up the stack (which makes a unit test a bit hard without just registering in the testbase as well, defeating the purpose of unit testing the method). 
* Fixes #5049
> Fixed: 'iso-8859-2' is not a supported encoding name

- src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
NO
Modification of the metadata exported by Radarr for Kodi (XBMX, Emby, Jellyfin) to adapt it to the scheme of version 18 and prepare it for version 19:
- Added new ratings scheme
- Added the fields userrating, top250, outline, tagline, playcount, lastplayed, country empty for use in Kodi (need this field in database)
- Added Director and Writer
- Added overview to set (empty, need this field in database)
- Change ID to TMDB (previously IMDB)
- Set True TMDB UniqueID instead of IMDB
- Modified thumb's sentence
- Remove <tmdbid>
- Reordered XML to match Kodi schema (https://kodi.wiki/view/NFO_files/Movies)
> Feature: Update of the fields in the NFO file for Kodi

- src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
- src/NzbDrone.Core/Parser/LanguageParser.cs
NO
As in the title. Almost no-one names their torrent "polish".
Fixes nothing.
> Parse Polish language

- src/NzbDrone.Core.Test/ParserTests/HashedReleaseFixture.cs
- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
[common]
NO
Handle release groups named like `D-Z0N3`
* Fixes #3273
---
thanks to @Taloth for the Regex help!
> Fixed: Correctly Parse Release Groups with a `-` in their name

- frontend/src/AddMovie/AddNewMovie/AddNewMovie.js
- frontend/src/AddMovie/AddNewMovie/AddNewMovieConnector.js
- frontend/src/AddMovie/AddNewMovie/AddNewMovieSearchResult.css
- frontend/src/AddMovie/AddNewMovie/AddNewMovieSearchResult.js
- frontend/src/AddMovie/AddNewMovie/AddNewMovieSearchResultConnector.js
- frontend/src/Components/Label.css
- frontend/src/Components/Label.js
- frontend/src/Movie/Details/MovieDetails.js
- frontend/src/Movie/Details/MovieDetailsConnector.js
- frontend/src/Movie/Details/MovieStatusLabel.css
- frontend/src/Movie/Details/MovieStatusLabel.js
- frontend/src/Utilities/Movie/getProgressBarKind.js
NO
This will address some other issues (related to colors as well)
- Add movie status to the main search page if the movie is already in the db (label on small screen otherwise progress bar under poster)
- Fix issues with yellow/grey movie status color not showing up properly (on search, index, details)
- Refactor the getMovieStatus to be more generic
Fixes: #5144 
Fixes: #5623
> Add movie status to the main search page

- src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
- src/NzbDrone.Core/Parser/QualityParser.cs
NO
-  Translation Keys-N/A
-  Wiki Updates-N/A
* Fixes #XXXX
Sonarr PR https://github.com/Sonarr/Sonarr/pull/4248
> Fixed: Parse standalone UHD as 4K if no other resolution info is present

- src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
Currently the scraper puts an https:// link, this is not compatible with the YouTube plugin, it needs to be in plugin format with YouTube ID
NO
Currently the scraper puts an https:// link, this is not compatible with the YouTube plugin, it needs to be in plugin format with YouTube ID
N/A
* Fixes https://github.com/Radarr/Radarr/issues/5796
> Fix: Youtube trailers do not play from scraped data

- src/NzbDrone.Common/EnvironmentInfo/OsInfo.cs
- src/NzbDrone.Common/Radarr.Common.csproj
NO
Set musl status at compile time instead of relying on `ldd` and `/bin/ls` existing, which it may not.
* Fixes #4890
> Fixed: Set musl status at compile time

- src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
- src/NzbDrone.Core/Parser/LanguageParser.cs
NO
Currently subbed releases (Czech, Lithuanian and Polish) reports as having that language, but when the file is downloaded, it is correctly detected with original language. This causes issues with custom format, when for example you are upgrading the release until expected language is found. 
None
> Treat subbed as unknown language

- src/NzbDrone.Core.Test/HealthCheck/Checks/MonoVersionCheckFixture.cs
- src/NzbDrone.Core.Test/HealthCheck/Checks/SqliteVersionCheckFixture.cs
- src/NzbDrone.Core/HealthCheck/Checks/MonoVersionCheck.cs
- src/NzbDrone.Core/HealthCheck/Checks/SqliteVersionCheck.cs
- src/NzbDrone.Core/Localization/Core/en.json
NO
Warn on Mono < 5.20 (though in practice it won't start) and SQLite < 3.9.0
* Fixes #5785
> Update version checks for Mono and SQLite

- src/Radarr.Api.V3/swagger.json
NO
fixed wrong type for Movie->titleSlug and Rating->value in swagger.json
> fixed wrong type for Movie->titleSlug and Rating->value in swagger.json

- src/NzbDrone.Common/EnvironmentInfo/RuntimeInfo.cs
- src/NzbDrone.Host/Bootstrap.cs
NO
The change to set ExecutingApplication in 26a04c9fd broke mono - it
returned the location of the mono executable and not radarr.
It seems that there was a change in behaviour in net5.0 which means we
can no longer use the same code in both cases.
* Fixes: issue reported on discord
> Fixed: Built-in updater for mono version

- frontend/src/Movie/Index/Menus/MovieIndexSortMenu.js
- frontend/src/Movie/Index/Posters/MovieIndexPoster.js
- frontend/src/Movie/Index/Posters/MovieIndexPosterInfo.js
- frontend/src/Movie/Index/Posters/MovieIndexPosters.js
- frontend/src/Movie/Index/Posters/Options/MovieIndexPosterOptionsModalContent.js
- src/NzbDrone.Core/Localization/Core/en.json
NO
Release date as a calculated value as an option on the Poster View - uses dates in this order
1. Earliest of physical/digital release (if both specified)
2. digital/physical release (if only one specified)
3. cinema release date
* Fixes #5656
> New poster view release date

- src/NzbDrone.Core/Download/Clients/Flood/Flood.cs
- src/NzbDrone.Core/Download/Clients/Flood/FloodProxy.cs
- src/NzbDrone.Core/Download/Clients/Flood/FloodSettings.cs
- src/NzbDrone.Core/Download/Clients/Flood/Models/AdditionalTags.cs
- src/NzbDrone.Core/Download/Clients/Flood/Types/Torrent.cs
- src/NzbDrone.Core/Download/Clients/Flood/Types/TorrentContent.cs
- src/NzbDrone.Core/Download/Clients/Flood/Types/TorrentListSummary.cs
NO
Add support for [Flood](https://flood.js.org), a modern Web UI for various torrent clients.
Closes #5793.
> Initial support for Flood

- src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs
- src/NzbDrone.Core/Organizer/FileNameBuilder.cs
NO
Certain cultures like "az" can cause the naming token regex to fail, leaving half of the filename not replaced as seen in the preview below. Ensuring we treat the regex as culture invariant fixes this.
Also adds a test to cycle thru every culture testing a typical naming token string
* Fixes #XXXX
> Fixed: Naming Token Regex can fail on certain Cultures

- src/NzbDrone.Core.Test/MediaFiles/MovieImport/Aggregation/Aggregators/AggregateReleaseGroupFixture.cs
- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
NO
Handle a handful of groups who don't follow standard naming.
These are manual exceptions and any additions will need to be manually added.
Currently this will handle the following groups that follow the format of `GroupName)` or `GroupName]`
- Tigole
- Joy
- YIFY
- YTS.MX
- FreetheFish
- afm72
It will also handle the following groups by checking for a Case Insensitive match against the exact name
- KRaLiMaRKo
- E.N.D
For future requests, a GHI should be opened with the release name and I should be pinged.
* Fixes #3550
* Fixes #5804 (see further comments)
> New: Handle select groups that do not follow -RlsGrp format

- src/NzbDrone.Api/DownloadClient/DownloadClientResource.cs
- src/NzbDrone.Api/Indexers/IndexerResource.cs
- src/NzbDrone.Api/Metadata/MetadataResource.cs
- src/NzbDrone.Api/NetImport/ImportExclusionsResource.cs
- src/NzbDrone.Api/NetImport/NetImportResource.cs
- src/NzbDrone.Api/Notifications/NotificationResource.cs
- src/NzbDrone.Api/ProviderModuleBase.cs
- src/NzbDrone.Api/ProviderResource.cs
- src/NzbDrone.Common/Serializer/System.Text.Json/PolymorphicWriteOnlyJsonConverter.cs
- src/NzbDrone.Integration.Test/ApiTests/IndexerFixture.cs
- src/Radarr.Api.V3/DownloadClient/DownloadClientResource.cs
- src/Radarr.Api.V3/ImportLists/ImportExclusionsResource.cs
- src/Radarr.Api.V3/ImportLists/ImportListResource.cs
- src/Radarr.Api.V3/Indexers/IndexerResource.cs
- src/Radarr.Api.V3/Metadata/MetadataResource.cs
- src/Radarr.Api.V3/Notifications/NotificationResource.cs
- src/Radarr.Api.V3/ProviderModuleBase.cs
- src/Radarr.Api.V3/ProviderResource.cs
- src/Radarr.Http/ErrorManagement/RadarrErrorPipeline.cs
NO
System.Text.Json doesn't support polymorphic serialization.  PR works around it by changing `ProviderResource` to `ProviderResource<T> : RestResource`, then we can use an explicit `List<T>` for the presets instead of `List<ProviderResource>`.
* Fixes issue reported on discord
> Fixed: Adding indexers from presets

- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
NO
Adds additional release groups that were not included in #5612:
- Anna
- Bandi
- Ghost
- Kappa
- MONOLITH
- Qman
- RZeroX
- SAMPA
- Silence
- theincognito
- t3nzin
- Vyndros
> Handle additional groups/encoders that do not follow -RlsGrp format

- src/NzbDrone.Core/Datastore/Converters/EmbeddedDocumentConverter.cs
- src/NzbDrone.Core/ThingiProvider/ProviderRepository.cs
NO
Prior to net5 only null values were ignored via ignoreNull = true for embedded doc converter and provider repo. Serialization settings `ignoreNull` was changed to Enum in net5. Original Net5 PR set these to Ignore `WhenWritingDefault` which in the case of booleans is `false` meaning provider settings with `false` values were not written to DB. This was troublesome when the default value of these settings was true meaning they could never be disabled. This change sets serialization settings to `WhenWritingNull` which only ignores if the value is explicitly null (acting like previous behavior). 
* Fixes #5836
> Fixed: Don't ignore default Boolean in db serialization

- frontend/src/Store/Actions/movieIndexActions.js
NO
Fixed bug with no default state in PosterView for showCinemaRelease and showReleaseDate as found by Nit
* No issue raised; information found https://discord.com/channels/264387956343570434/264387994302021632/809967577618317342
> Fix: Default states for Show Cinema Release and Show Release Date in Poster View

- src/NzbDrone.Core/Download/Clients/Deluge/DelugeSettings.cs
- src/NzbDrone.Core/Download/Clients/DownloadStation/DownloadStationSettings.cs
- src/NzbDrone.Core/Download/Clients/Flood/FloodSettings.cs
- src/NzbDrone.Core/Download/Clients/Hadouken/HadoukenSettings.cs
- src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetSettings.cs
- src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs
- src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdSettings.cs
- src/NzbDrone.Core/Download/Clients/Transmission/TransmissionSettings.cs
- src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs
- src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentProxy.cs
- src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentSettings.cs
(cherry picked from commit 85f4cbe94c6f00352e0d4a38f337fb9417d3032b)
NO
Puts Use SSL and other options in a more consistent order across the various download clients. 
* Fixes #6019
> Fix: Consistent SSL option for Download Clients

- src/NzbDrone.Core/Notifications/Email/EmailSettings.cs
NO
Changed spelling of Seperate to Separate as found by @Taloth
> Fixed: Spelling of Separate in Email Notification Settings

- src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserRequestGenerator.cs
- src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserSettings.cs
NO
Actually, Trakt Import List feature only allows personal list from authenticated user. This new option allow the user to set any user to import his lists.
> Add option to import from any user's personal list

- src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
- src/NzbDrone.Core/MediaFiles/DownloadedMovieImportService.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoLib.cs
- src/NzbDrone.Core/Parser/LanguageParser.cs
NO
- Fixes a sonarr and show log references -> radarr and movie
- Adds support for detecting 'castellano' as Spanish Language
-Adds support for detecting 'FRA' and 'FRE' as French Language
- Translation Keys-N/A
- Wiki Updates-N/A
* Fixes #6152
* Fixes #6136
> Various Fixes: Parser and Sonarr References

- frontend/src/Calendar/CalendarPageConnector.js
NO
missingMovieIds was originally picking up movies that had movies; by switching to "hasFile" this should no longer be the case (based on my testing) 
* Fixes #6165
> Fixed: Search Missing Movies on Calendar

- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
Closes #6044
NO
- Translation Keys - N/A
-  Wiki Updates - N/A
* Fixes #XXXX
> Fixed: Not capturing D-Z0N3 preceded with .-  Closes #6044

- src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
(cherry picked from commit 6934eafd4416322f4677414d3f7f997e82f1bca8)
NO
Rounds the duration seconds for Kodi metadata
* Fixes #6199
> Pull Sonarr commit 'Fixed: Round durationseconds in Kodi metadata'

- src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
New: Detect YTS.LT as a Release Group
NO
Fixes issue reported via discord
- N/A Translation Keys
- N/A Wiki Updates
* Fixes #XXXX
> Fixed: Incorrectly identifying YTS.LT as Lithuanian  Language

- frontend/src/InteractiveSearch/InteractiveSearchRow.js
NO
Links for interactive search results (Jackett + RARBG) don't open (HTTP 429 is returned). Adding `rel='noreferrer'` to the results links fixes the issue.
> Add noreferrer to links in interactive search results

- frontend/src/InteractiveSearch/InteractiveSearchRow.js
NO
Moves the release rejected tooltip to below the active line
* Fixes #6271
> Fixed: Interactive Search Release Rejected tooltip no longer covers download button

- src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/MapFixture.cs
- src/NzbDrone.Core/Parser/ParsingService.cs
NO
Resolves rejection of release when it is a Multi Language release, the indexer is set to identify Multi's as  Original and another language and the profile is set to require original. 
* Fixes #5786
> Fixed: Multi language release being rejected when indexer profile is setup for original and another language

- src/Radarr.Http/Extensions/RequestExtensions.cs
NO
Fixes an issue where an IPv6 shows mapped as an IPv6 and so doesn't show as local and so doesn't use x-real-ip or x-forwarded-for in the logs
https://discord.com/channels/264387956343570434/264388019585286144/847485427833372774
> Fixed: Real IP Logging when IPv4 mapped as IPv6

- src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
- src/NzbDrone.Core/Parser/QualityParser.cs
NO
Detect releases with "UHDBD" as Bluray quality. The added test cases are currently tagged as "HDTV".
* N/A
> Fixed: Detect "UHDBD" as BluRay quality

- src/NzbDrone.Common/Serializer/System.Text.Json/STJUtcConverter.cs
NO
Some indexers RSS sync is paging back too far, depending on system timezone.  I think all EmbeddedDocument dates should be deserialized as UTC and not local time.
* Fixes issue reported on prowlarr discord
> Fixed: RSS sync paging back too far for some indexers

- src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/TorrentDownloadStationFixture.cs
- src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/UsenetDownloadStationFixture.cs
- src/NzbDrone.Core/Download/Clients/DownloadStation/DiskStationApi.cs
- src/NzbDrone.Core/Download/Clients/DownloadStation/DownloadStation2Task.cs
- src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DiskStationProxyBase.cs
- src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxySelector.cs
- src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxyV1.cs
- src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxyV2.cs
- src/NzbDrone.Core/Download/Clients/DownloadStation/Responses/DiskStationError.cs
- src/NzbDrone.Core/Download/Clients/DownloadStation/Responses/DownloadStation2TaskInfoResponse.cs
- src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs
- src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs
NO
Added compatibility with the new Download Station API 'SYNO.DownloadStation2.Task'.
This will resolve the compatibility issue with the new version of Synology Download Stations 3.8.16-3566.
If the new 'SYNO.DownloadStation2.Task' API is available, use it, otherwise use the old 'SYNO.DownloadStation.Task'.
* Fixes #6062
* Fixes #6402
> Add compatibility with the new Download Station API 'SYNO.DownloadStation2.Task'

- src/NzbDrone.Core/Indexers/FileList/FileListSettings.cs
- src/NzbDrone.Core/Indexers/HDBits/HDBitsSettings.cs
- src/NzbDrone.Core/Indexers/IPTorrents/IPTorrentsSettings.cs
- src/NzbDrone.Core/Indexers/Nyaa/NyaaSettings.cs
- src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornSettings.cs
- src/NzbDrone.Core/Indexers/Rarbg/RarbgSettings.cs
- src/NzbDrone.Core/Indexers/TorrentRss/TorrentRssIndexerSettings.cs
- src/NzbDrone.Core/Indexers/Torznab/TorznabSettings.cs
YES - NO
The help link for indexer flags in the Indexer Setup screens was incorrect, and now points to the proper location in the wiki.
> Fixed: Update indexer flag help link

- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
NO
- Fixed: Incorrectly Parsing [PublicHD] as Release Group
- Corrected: Parser Test Naming
- Cleanse TorrentSuffixes before parsing group
-  Translation Keys
-  Wiki Updates
* Fixes #XXXX
> Fixed: Incorrectly Parsing [PublicHD] as Release Group

- src/NzbDrone.Core.Test/ParserTests/EditionParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
NO
fixes various edition parsing issues and adds support for additional editions
this edition regex is getting a bit nuts....
- Translation Keys
- Wiki Updates
* Closes #5717
> Fixed: Support for additional Movie Editions

- src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/ReservedDeviceNameFixture.cs
- src/NzbDrone.Core/Organizer/FileNameBuilder.cs
NO
Sonarr Pull for preventing conflicts with reserved device names
* Fixes #6517
> Fixed: Prevent conflicts with reserved device names

- src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
NO
more test cases are always a good thing
N/A
ref #5675  we did not have a test case for the H265 change
Discovered when backporting to sonarr
> add missing quality fixture test case

- src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/ReservedDeviceNameFixture.cs
Replace Sonarr reference in reserved device name tests
NO
Replace Sonarr reference in reserved device name tests.
> Replace Sonarr reference in reserved device name tests

- src/NzbDrone.Core.Test/NotificationTests/NotificationBaseFixture.cs
- src/NzbDrone.Core.Test/NotificationTests/SynologyIndexerFixture.cs
- src/NzbDrone.Core/MediaFiles/Events/MovieRenamedEvent.cs
- src/NzbDrone.Core/MediaFiles/RenameMovieFileService.cs
- src/NzbDrone.Core/MediaFiles/RenamedMovieFile.cs
- src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
- src/NzbDrone.Core/Notifications/Discord/Discord.cs
- src/NzbDrone.Core/Notifications/INotification.cs
- src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowser.cs
- src/NzbDrone.Core/Notifications/NotificationBase.cs
- src/NzbDrone.Core/Notifications/NotificationService.cs
- src/NzbDrone.Core/Notifications/Plex/Server/PlexServer.cs
- src/NzbDrone.Core/Notifications/Slack/Slack.cs
- src/NzbDrone.Core/Notifications/Synology/SynologyIndexer.cs
- src/NzbDrone.Core/Notifications/Webhook/Webhook.cs
- src/NzbDrone.Core/Notifications/Webhook/WebhookRenamePayload.cs
- src/NzbDrone.Core/Notifications/Webhook/WebhookRenamedMovieFile.cs
- src/NzbDrone.Core/Notifications/Xbmc/Xbmc.cs
NO
This PR resolves #5934, and pulls in 3c45349404f59064d1c8db0549401189c456e4c0 from the upstream Sonarr repo. It implements the changes from the above commit, renaming Episode -> Movie as required in both class, variable, and file names.
The new JSON events have the following format:
```
{
"movie": {
"id": 1,
"title": "Some Movie Title",
"year": 2020,
"releaseDate": "2020-01-01",
"folderPath": "C:\\Movies\\Some Movie Title (2020)",
"tmdbId": 0001,
"imdbId": "tt0000001"
},
"renamedMovieFiles": [
{
"previousRelativePath": "Some.Movie.Title.2020.mkv",
"previousPath": "C:\\Movies\\Some Movie Title (2020)\\Some.Movie.Title.2020.mkv",
"id": 1,
"relativePath": "Some Movie Title (2020).mkv",
"quality": "Bluray-1080p",
"qualityVersion": 1,
"releaseGroup": "Release Group",
"indexerFlags": "0", …
```
> New: Include renamed file information for Webhook and Custom Scripts

- src/NzbDrone.Core/Notifications/Simplepush/Simplepush.cs
- src/NzbDrone.Core/Notifications/Simplepush/SimplepushProxy.cs
- src/NzbDrone.Core/Notifications/Simplepush/SimplepushSettings.cs
NO
Adds support for [Simplepush](https://simplepush.io) notifications on Settings -> Connect.
Simplepush supports end-to-end encrypted notifications.
Once I have the okay from you guys, I would add support for end-to-end encrypted notifications into this PR.
Therefore it would be good to know if you prefer the end-to-end encryption code to be in this codebase or to be included from a library (that I would create)?
> New: Add support for Simplepush notifications

- frontend/src/Settings/General/HostSettings.js
(cherry picked from commit 943a3d80c4ff37cdffcd840190353d679c979493)
NO
Disables autofill of the port field within HostSettings (Sonarr Pull)
* Fixes #6611
> New: Disable autocomplete of port number

- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
Fixed: Incorrectly parsing RePACKPOST as Group
* Fixes #6407
> Fixed: Incorrectly parsing RePACKPOST as Group

- frontend/src/Movie/Details/MovieDetails.css
- frontend/src/Movie/Details/MovieDetails.js
NO
Adds a list of genres to the movies details page, only shows when not in mobile view. 
* Fixes #5657
> New: Added Genres to Movie Details page

- src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowser.cs
- src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserSettings.cs
NO
Adds On Delete Notifications for Emby - this ideally needs testing by someone who has Emby/Jellyfin and running NFS/CIFS as their filesystem for movie storage
* Fixes #4181
> New: Support On Delete Notifications for Emby

- src/NzbDrone.Core.Test/IndexerSearchTests/SearchDefinitionFixture.cs
- src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs
- src/NzbDrone.Core/Indexers/FileList/FileListRequestGenerator.cs
- src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
- src/NzbDrone.Core/Indexers/Nyaa/NyaaRequestGenerator.cs
- src/NzbDrone.Core/Indexers/Omgwtfnzbs/OmgwtfnzbsRequestGenerator.cs
- src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornRequestGenerator.cs
(cherry picked from commit 747a4164e24e9861cacad39cf7d94db398747b38)
NO
Sonarr pull 'Rename QueryTitles to CleanSceneTitles in SearchCriteriaBase'
* Fixes #6641
> Sonarr Pull 'Rename QueryTitles to CleanSceneTitles in SearchCriteriaBase'

- src/Radarr.Http/Authentication/AuthenticationBuilderExtensions.cs
Lidarr, Radarr, and Prowlarr (maybe Readarr too) all use
the same name for their Authentication cookies
.AspNetCore.Forms
Sonarr uses a different name "SonarrAuth"
this commit makes Radarr use "RadarrAuth"...
similar changes should likely be ported to Lidarr, Prowlarr (and possibly Readarr)
NO
> Fixed: Give a unique name to the cookie used by Radarr (and other arr apps)

- src/Radarr.Api.V3/Blocklist/BlocklistController.cs
- src/Radarr.Api.V3/History/HistoryController.cs
- src/Radarr.Api.V3/MovieFiles/MovieFileController.cs
- src/Radarr.Api.V3/Movies/MovieEditorController.cs
- src/Radarr.Api.V3/ProviderControllerBase.cs
- src/Radarr.Api.V3/Queue/QueueActionController.cs
- src/Radarr.Api.V3/Queue/QueueController.cs
See https://github.com/dotnet/runtime/issues/61995
NO
.NET 6 throws an error returning `new object()`, so return `new { }` instead
* Fixes #6483 
* possibly others
> Workaround .net error serializing new object()

- frontend/src/Components/Form/ProviderFieldFormGroup.js
- src/NzbDrone.Core/Annotations/FieldDefinitionAttribute.cs
- src/NzbDrone.Core/Notifications/Email/EmailSettings.cs
- src/NzbDrone.Core/Notifications/Mailgun/MailgunSettings.cs
- src/NzbDrone.Core/Notifications/PushBullet/PushBulletSettings.cs
- src/NzbDrone.Core/Notifications/Pushover/PushoverSettings.cs
- src/NzbDrone.Core/Notifications/SendGrid/SendGridSettings.cs
- src/Radarr.Http/ClientSchema/Field.cs
- src/Radarr.Http/ClientSchema/SchemaBuilder.cs
NO
Enables frontend placeholders to be set from the backend. 
Sets placeholders instead of defaults in some notifications
@bakerboy448  wanted better examples of email addresses in help text, this feels more suitable.
> New: Added Frontend Placeholders from the Backend

- frontend/src/AddMovie/AddNewMovie/AddNewMovie.js
NO
Correct the FAQ link on the Add New Movie page to go directly to the right section
> Fix FAQ Link on Add New Movie page

- src/NzbDrone.Core/Localization/Core/en.json
common commit
NO
Due to the confusing message, users frequently incorrectly believe Radarr deleted the file when it simply could no longer be seen.
*Ref  https://github.com/Sonarr/Sonarr/pull/4791
> Fixed: Better wording of MissingFromDisk

- src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
NO
- Fixed: Support movies with French in their title
- (Breaks) Regression: Dropped Support for poorly named French Releases
IMO it is better to support all movies that have `French` in their name than it is to not be able to parse any movie with `French` in the name and support the horribly named removed french release test case with a ton of info before the year
* Fixes #6821
> Fixed: Support movies with French in their title

- src/NzbDrone.Core.Test/Datastore/Migration/201_migrate_discord_from_slackFixture.cs
- src/NzbDrone.Core/Datastore/Migration/201_migrate_discord_from_slack.cs
- src/NzbDrone.Core/HealthCheck/Checks/SlackUrlCheck.cs
- src/NzbDrone.Core/Localization/Core/en.json
YES - 201
Health check for discord notifications setup as a slack notification. This is a warning message as users will get a better experience setting it up as a Discord Notification. 
@Qstick recommended that this is a healthcheck that we needed on [discord](https://discordapp.com/channels/264387956343570434/269962130982174720/910972822447341568)
> Migration and Health Check for Discord Notifications setup as Slack

- src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs
- src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs
Closes #6751
Fixes #6818
(cherry picked from commit b184e62fa7dd7ecd089619f176e6388c1c3be25d)
NO
* Fixes #XXXX
> Fixed: Get full path for download station instead of shared folder

- src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
- src/NzbDrone.Core/Parser/QualityParser.cs
> Fixed: Parsing of quality when release group contains Remux

- src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
- src/NzbDrone.Core/Parser/QualityParser.cs
NO
A fix for detecting specific cases as hardsubs when that was not the case, the specific cases are "horriblesubs" and "softsubs". Horriblesubs is a release group and softsubs speaks for itself.
I added some tests as well but I am unfamiliar with NUnit however they did seem to work.
> Fixed hardsub detection for some specific cases

- src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
- src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
NO
- In NewsnabifyTitle we now encode the url which will handle escaping any special characters (e.g. `&`)
- changes the replace from encoded space to actual space
- Per @markus101 he does not believe changing NewsnabifyTitle should have a negative impact
- common commit
* Fixes #6799
* Resolves https://github.com/Prowlarr/Prowlarr/issues/683
> Fixed: Escape Characters as needed for *znab queries

- frontend/src/Settings/MediaManagement/Naming/NamingModal.js
- src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatVideoDynamicRangeTypeFixture.cs
- src/NzbDrone.Core.Test/MediaFiles/MediaInfo/VideoFileInfoReaderFixture.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/HdrFormat.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
- src/NzbDrone.Core/Organizer/FileNameBuilder.cs
- src/Radarr.Api.V3/MovieFiles/MediaInfoResource.cs
NO
- New: Add {MediaInfo VideoDynamicRangeType} token for renaming
- New: Detect HDR Type
- Based on Sonarr 7b694ea71d7f78bad5c03393c4cf6f7a28ada1cb
- Bump to CURRENT_MEDIA_INFO_SCHEMA_REVISION to 9
* Closes #6789
* Fixes #4844
- [Related Message](https://discord.com/channels/264387956343570434/264387994302021632/923981553896423464)
- [Example JSON FFProbe Dumps](https://gist.github.com/bakerboy448/023c6ba3ee09d7db61b57f2175d396f9) thanks TRaSH
For Posterity - References (thanks Ta)
```
dv_bl_signal_compatibility_id – specifies a particular form of a
base-layer sub-stream that can be decoded to a signal compliant with a
particular set of standards, if any.
```
- https://professional.dolby.com/siteassets/content-creation/do …
> New: Add {MediaInfo VideoDynamicRangeType} token for renaming

- src/NzbDrone.Core/Download/Clients/Flood/Flood.cs
- src/NzbDrone.Core/Download/Clients/Flood/FloodProxy.cs
- src/NzbDrone.Core/Download/Clients/Flood/Types/FloodClientSettings.cs
NO
If Destination is not set for flood, fallback to the default from the client for status checks
> Fixed: Avoid download path check false positives for flood

- frontend/src/System/Status/Health/Health.js
- src/NzbDrone.Core.Test/HealthCheck/Checks/IndexerJackettAllCheckFixture.cs
- src/NzbDrone.Core.Test/IndexerTests/TorznabTests/TorznabFixture.cs
- src/NzbDrone.Core/HealthCheck/Checks/IndexerJackettAllCheck.cs
- src/NzbDrone.Core/Indexers/Torznab/Torznab.cs
- src/NzbDrone.Core/Localization/Core/en.json
NO
Jackett all is bad - stopping adding/editing indexers that have this and calls a health check for those that have the all endpoint configured!
> Jackett All healthcheck and verification

- src/NzbDrone.Common/Http/XmlRpcRequestBuilder.cs
- src/NzbDrone.Core/Download/Clients/Aria2/Aria2.cs
- src/NzbDrone.Core/Download/Clients/Aria2/Aria2Containers.cs
- src/NzbDrone.Core/Download/Clients/Aria2/Aria2Proxy.cs
- src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs
- src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentFault.cs
- src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentProxy.cs
- src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentTorrent.cs
- src/NzbDrone.Core/Download/Extensions/XmlExtensions.cs
- src/NzbDrone.Core/Radarr.Core.csproj
NO
Use our HttpClient so that we can control certificate validation.
* Fixes issue reported on discord
> Fixed: Use our own HttpClient for rTorrent RPC requests

- src/NzbDrone.Core/Localization/Core/en.json
NO
Changed the translation text warning on Search All. Previously said it could be canceled by restarting Radarr, but this is not true. Changed it to say disabling indexers instead.
> Fixed: Translation warning for search all

- src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
- src/NzbDrone.Core/Parser/QualityParser.cs
NO
Enhances existing parsing of `HDDVD` to account for `.`, `-`, etc. between HD and DVD
* Fixes #6925
> Fixed: Parse HD.DVD as BluRay

- src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoModel.cs
- src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrProxy.cs
- src/NzbDrone.Core/Radarr.Core.csproj
NO
These two properties make incorrect use of FFProbe.Analyse() method by passing in Stream as a string thus when serialization happens from Webhook, they fail. They are also not ignored because webhook serialization uses Newtonsoft and they are using STJson ignore attributes.
Given properties are not used, easy fix for 4.0 is to remove them. switching webhook to serialize with STJson may be dangerous for master at this point.
> Fixed: Webhook fails due to Frames/Analysis property serialization on MediaInfoModel

- src/NzbDrone.Core/Languages/Language.cs
- src/NzbDrone.Core/Parser/IsoLanguages.cs
NO
Fix the name of the Ukrainian language in the UI.
Also, fix the 3-letter ISO language mapping to correctly parse filenames with [UKR] suffix.
* Fixes #XXXX
> Fix Ukrainian language mappings

- src/NzbDrone.Core/Localization/Core/en.json
common commit
NO
Currently many users commonly are mislead by the existing helptext that implies indexer priority will change how indexers are searched or any other possibilities other than simply being a tiebreaker.
This clarifies the currently confusing helptext
- Tests
- [Wiki Updates](https://wiki.servarr.com) - already done 
`(Advanced Option) Indexer Priority - Priority of this indexer to prefer one indexer over another in release tiebreaker scenarios. 1 is highest priority and 50 is lowest priority.`
* Fixes #6967
> Fixed: Clarify Indexer Priority Helptext

- frontend/src/Store/Migrators/migrate.js
- frontend/src/Store/Migrators/migratePreDbToReleased.js
NO
Expands on https://github.com/Radarr/Radarr/commit/4d2a311e40d84ba6bf55130bfb6552a797912616 to remove the pre-DB option from cached settings in the frontend
> Fixed: Remove pre-DB from frontend storage

- src/NzbDrone.Update/UpdateEngine/DetectExistingVersion.cs
NO
Fixes the "unknown" version on non-windows platform - this is caused by the migration to .NET and not using mono on non-windows platforms
* Fixes #7098
> Fixed: Updater showing version being updated from on non-windows platforms

- frontend/src/Content/Images/Icons/manifest.json
NO
When you install Radarr as a PWA (i.e. using "Add to Home Screen" in Firefox for Android), it has the correct icon but the generic name "Website" since the manifest name field is null. [The name field is mandatory](https://developer.mozilla.org/en-US/docs/Web/Manifest/name).
See how Nzbget has the correct name, but Sonarr and Radarr do not.
* Fixes #XXXX
> PWA missing name

- src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
- src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs
- src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
- src/NzbDrone.Core/Parser/QualityParser.cs
NO
- New: Support for parsing [HDO] as HDO Group
- Fixed: Dont Parse HDRip as group
- New: Support for parsing various Anime Groups
- DusIctv
- DHD
- SEV
- CtrlHD
- -ZR-
- XZVN
- ADC
- Koten_Gars
- RH
- Kametsu
- BluDragon
- New:  Dont parse hash as release group
- Fixed tests
- Fixed: Better Cleansing of Tracker Announce Keys
- Fixed: Cleanse Notifiarr secret from URL in logs (API)
- Fixed: Treat 720p BR Remux as BluRay
- Fixed: Correctly Detect Remux prefixed by Brackets
- Fixed: Parsing of quality in DP.WEB releases
- N/A Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- N/A [Wiki Updates](https://wiki.servarr.com)
* Discord Report
* Fixes #6711
* Closes #6972
* Closes #6973 
* Closes #6978
* Closes #6979
* Closes #6974
* Closes #6975
* Closes #6977 
* Fixes #7009
* …
> Various Parsing Fixes & Enhancments

- src/NzbDrone.Core/Radarr.Core.csproj
NO
Update ffprobe:
- Remove dependency on libX11 on MacOS
- Add support for AV1 streams
* Fixes #XXXX
> Fixed: FFprobe failing on MacOS and AV1 streams

- src/NzbDrone.Core.Test/DecisionEngineTests/QueueSpecificationFixture.cs
- src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/AugmentersTests/AugmentWithOriginalLanguageFixture.cs
- src/NzbDrone.Core/CustomFormats/CustomFormatCalculationService.cs
- src/NzbDrone.Core/CustomFormats/Specifications/LanguageSpecification.cs
- src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs
- src/NzbDrone.Core/DecisionEngine/Specifications/QueueSpecification.cs
- src/NzbDrone.Core/Download/Pending/PendingReleaseService.cs
- src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs
- src/NzbDrone.Core/Parser/Augmenters/AugmentWithOriginalLanguage.cs
NO
This PR fixes the check for Original Language in custom formats.
Before the PR, the custom format will check if the release contains the language "Original" (which of course will fail). This PR will check with the actual original language of the movie.
* Fixes #6395
* Closes #6992
> Check "Original" language Custom Format with the real original language

- src/NzbDrone.Core.Test/Files/plex_watchlist.json
- src/NzbDrone.Core.Test/ImportListTests/Plex/PlexParserFixture.cs
- src/NzbDrone.Core/ImportLists/ImportListType.cs
- src/NzbDrone.Core/ImportLists/Plex/PlexImport.cs
- src/NzbDrone.Core/ImportLists/Plex/PlexListRequestGenerator.cs
- src/NzbDrone.Core/ImportLists/Plex/PlexListSettings.cs
- src/NzbDrone.Core/ImportLists/Plex/PlexParser.cs
- src/NzbDrone.Core/Notifications/Plex/PlexMediaType.cs
- src/NzbDrone.Core/Notifications/Plex/PlexTv/PlexTvService.cs
- src/NzbDrone.Core/Notifications/Plex/Server/PlexSectionItem.cs
- src/NzbDrone.Core/Notifications/Plex/Server/PlexServerProxy.cs
- src/NzbDrone.Core/Notifications/Plex/Server/PlexServerService.cs
NO
Plex has a new watchlist feature that they've been fleshing out. I've been using it and wanted to see support in Radarr. I've implemented a basic import list implementation taking cues from the existing trakt integration. Where possible I've re-used or enhanced existing Plex response models rather than write new code. I'm a node dev professionally and haven't written C# in years so any and all feedback is very welcome.
* Closes #5705 
* Closes #7188 
* Closes #7187
> Add support for Plex Watchlist importing

- frontend/src/App/App.js
- frontend/src/Components/Page/PageContent.js
- frontend/src/Settings/General/HostSettings.js
- src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
- src/NzbDrone.Core/Instrumentation/ReconfigureLogging.cs
- src/NzbDrone.Core/Localization/Core/en.json
- src/NzbDrone.Core/Validation/RuleBuilderExtensions.cs
- src/Radarr.Api.V3/Config/HostConfigController.cs
- src/Radarr.Api.V3/Config/HostConfigResource.cs
- src/Radarr.Api.V3/System/SystemController.cs
- src/Radarr.Http/Frontend/InitializeJsController.cs
NO
Seperates the syslog level from the file log level
Adds an option to have a custom application name for syslog to enable knowing what logs are for what instance when logging multiple instances
> New: Seperate Syslog Level from log level and add Syslog custom app name

- src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
- src/NzbDrone.Core/Parser/LanguageParser.cs
NO
Added term "brazilian" to Brazilian Portuguese regex
- [ X ] Tests
- [ X ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ X ] [Wiki Updates](https://wiki.servarr.com)
* Fixes #XXXX
> Added term "brazilian" to Brazilian Portuguese regex

- src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
- src/NzbDrone.Core/Parser/QualityParser.cs
NO
Add 'HQCAM' token to cam source regex to fix cam sources not being matched correctly.
Ex. "Thor : Love and Thunder (2022) 1080p HQCAM ENG x264 AAC - QRips" is not matched as CAM
> Match 'HQCAM' as CAM source

- azure-pipelines.yml
- src/NuGet.config
- src/NzbDrone.Core.Test/Datastore/DatabaseFixture.cs
- src/NzbDrone.Core/Datastore/Migration/212_postgres_update_timestamp_columns_to_with_timezone.cs
- src/NzbDrone.Core/Radarr.Core.csproj
Yes - 212
Fluent Migrator creates Timestamp without time zone columns by default, when combined with a non UTC timezone this causes issues with dates. 
Sets each column to DataType Timestamp with time zone.
> Fixed: Postgres timezone issues

- src/NzbDrone.Core/IndexerSearch/MoviesSearchService.cs
… download/processing of unmonitored movies
| NO
Set userInvoked to true for manually triggered searches, to allow for download/processing of unmonitored movies. Per discord discussion
> Fixed: User Triggered Auto Searches now ignores monitored status

- src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
NO
Adds the missing `watched` element in metadata writes. Everything else was already in place, reading the original state, etc. It's just the element that wasn't being written to the new *.nfo* file. This behavior is now 1:1 with Sonarr.
* Fixes [#7435](https://github.com/Radarr/Radarr/issues/7435)
> Fix watch state not preserved on metadata rewrite

- src/NzbDrone.Core/Movies/MoveMovieService.cs
In the success print by the logger, a message is being printed that indicates the movie was successfully moved to the source folder, not the destination folder.
I updated the logger statement to print that the movie was moved successfully to the destination folder.
NO
This pull request fixes a logger print statement. Fairly simple fix that should have limited impact.
- No todos
[Issue# 7440](https://github.com/Radarr/Radarr/issues/7440)
> Logger fix for a successful move

- src/NzbDrone.Core.Test/RootFolderTests/RootFolderServiceFixture.cs
- src/NzbDrone.Core/RootFolders/RootFolderService.cs
NO
"Import Movies" shows recycle bin as an unmapped folder and tries to match a movie to the folder.
This excludes recycle bin from that folder list (if configured in settings).
- [ X ] Tests
n/a
> Fixed: Configured recycle bin is excluded from import.

- src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs
NO
When trace logging is enabled and the HttpClient makes a request with a large content response (eg. Usenet history), the trace log call which dumps the response results in a hung thread.
I had this occur with a response length of approx 700k.
There were no exceptions thrown, the thread simply hung and was unable to recover.
> Fixed: Large content responses crash trace logger causing hung thread.

- src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
- src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs
NO
Log cleanse when tracing is enabled is extremely slow for large json files.
This fixes the log clense regex and adds additional tests.
* Fixes #7578
> Fix: Trace logging postgres cleanse for large json files.

- frontend/src/Components/Page/Toolbar/PageToolbarButton.css
NO
Prevents PageToolbarButton overlap when labels are too long by increasing the width of the button to `min-content`
Current behavior:
Behavior after PR:
* Fixes #7553
> Fixed: Toolbar Button labels overlap

- src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
NO
After troubleshooting in the Discord support channel, it was established that the alternate name for the YTS release group didn't get parsed correctly.
I have no experience with this and I hope I have added everything properly.
> Fixed: Add YTS.AG to the exception Release Groups

- .github/workflows/azuresync.yml
- .github/workflows/lock.yml
- .github/workflows/support.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
Fixed: Add HQMUX to the exception Release Groups
NO
This fixes HQMUX not getting recognized as the release group for multiple releases.
> Fixed: Add HQMUX to the exception Release Groups

- src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
- src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs
NO
This removes webhook ID and token from logging when using discord webhooks.
- [ X ] Tests
Originally Reported in Sonarr:
https://github.com/Sonarr/Sonarr/issues/5169
> Fixed: Discord webhook logs now get cleansed to remove webhook id and token

- frontend/src/Settings/MediaManagement/Naming/NamingModal.js
- src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs
- src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
NO
Uses `stero_mode` to detect 3D from ffprobe for video files with correct metadata
* Fixes #7695
> Fixed: Detect 3D in some video files

- src/NzbDrone.Core/Indexers/RssParser.cs
This is only meant to be more helpful when reading the exceptions log.
While implementing a rss service, this kept throwing and it does not show the original exception so I can fix what's being returned.
> chore: Chain exceptions when trying to get rss's item size

- frontend/src/Styles/Themes/index.js
- src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
- src/NzbDrone.Core/Localization/Core/en.json
Co-authored-by: Qstick <qstick@gmail.com>
(cherry picked from commit 4ca5a213fa0fc29ed93e7e31b080728d6fa7f1f3)
NO
Adds support for `prefers-color-scheme` to use the OS preferred theme (light or dark) and also makes it default with the option for the user to force the theme that they want in UI Settings
- N/A
* Fixes #7845
> New: Auto theme option to match OS theme

- src/NzbDrone.Core/Radarr.Core.csproj
NO
Includes https://github.com/alanmcgovern/monotorrent/pull/584, which fixes an issue that causes Radarr to fail to download some torrents.
* Fixes #XXXX
> Bump MonoTorrent to 2.0.7

- src/NzbDrone.Core/Download/DownloadService.cs
NO
If an unknown release is grabbed, it's very difficult to determine from the logs which movie it was grabbed from. For example, previously in logs it would display
```
DownloadService: Report sent to SABnzbd. The.Ultimate.Oppa.2022.1080p.AMZN.WEB-DL.DDP5.1.x264-HDMAX
```
This PR adds extra debugging info in logs to allow us to trace back much easier
```
DownloadService: Expensive Candy (2022) report sent to SABnzbd. The.Ultimate.Oppa.2022.1080p.AMZN.WEB-DL.DDP5.1.x264-HDMAX
```
None
None
None
> Include movie title and year when logging report

- frontend/src/Components/Menu/FilterMenu.js
- frontend/src/Components/Menu/PageMenuButton.css
- frontend/src/Components/Menu/PageMenuButton.js
NO
Fixing the filter indicator display in Search Panel.  Pulling in a Sonarr change that fixes the position and using the ToolbarMenuButton as the indicator logic was moved there in a previous change. 
Filter enabled: 
No filter enabled (all results shown):
- [N/A] Tests
- [N/A] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ N/A] [Wiki Updates](https://wiki.servarr.com)
* Fixes #7082
> Fix: Re-enable Filter Search Indicator

- .gitignore
Unless the repository owners wish to have these files in their repo, they should be ignored so that contributors are not stepping around these files.
> chore(git): Ignore `.idea/` completely

- src/NzbDrone.Core/Radarr.Core.csproj
(cherry picked from commit c08b45156425d84e51072093d0ead42f1c105ad5)
Sonarr Pull
Fixes: #8004
> Bump ImageSharp to 2.1.3

- src/NzbDrone.Core.Test/MediaFiles/DownloadedMoviesImportServiceFixture.cs
- src/NzbDrone.Core/Download/CompletedDownloadService.cs
- src/NzbDrone.Core/MediaFiles/DownloadedMovieImportService.cs
- src/NzbDrone.Core/MediaFiles/FileExtensions.cs
New: Show warning in queue if download contains executable or archive file and no video file was detected
(cherry picked from commit b15b6a079846b21cac8476820fce9cde81732291)
Fixes: #7908
> Improve handling of releases without video files

- src/NzbDrone.Core/Movies/MovieCutoffService.cs
(cherry picked from commit  f05e109b50cca496e7b42e2833eff161a43e12f4)
Sonarr Pull
* Fixes #8017
> Fixed: Avoid Sqlite Error when all profiles have lowest quality cutoff

- src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
(cherry picked from commit 99e60196a4e513d6340a090de4a5517f205e7a29)
* Fixes #7777
> Fixed: Parse year in title from square brackets

- src/NzbDrone.Core.Test/IndexerTests/PTPTests/PTPFixture.cs
- src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornParser.cs
NO
PTP returns UTC timestamps, without a timezone specifier. Previously, users would see skewed publish dates, as the UTC timestamps were being parsed as if they were in the system's timezone. To fix this, we just assume the publish date is in UTC.
* Fixes #8050
> Fixed: Releases from PTP showing skewed publish date

- src/NzbDrone.Core.Test/OrganizerTests/CleanFixture.cs
- src/NzbDrone.Core/Organizer/FileNameBuilder.cs
Database Migration
NO
Description
This is to remove initial dot in filenames. Hence, unix-like system won't see the files as hidden.
Issues Fixed or Closed by this PR
Fixes #4350
> remove initial dot in filename

- src/NzbDrone.Core/Localization/Core/en.json
NO
add an s and some explicit wording
- [] Tests
* Fixes confusion from a missing `s`
> Update library clean helptext

- frontend/src/Settings/DownloadClients/RemotePathMappings/RemotePathMapping.css
- frontend/src/Settings/DownloadClients/RemotePathMappings/RemotePathMappings.css
NO
Fixes the remote path mapping UI being pushed off-screen at lower resolutions/widths and making the edit button inaccessible. The changes mostly mirror the relevant changes in Sonarr/Sonarr@979ea44, but also aligns headers and paths at lower resolutions.
**Before:**
**After:**
* Fixes #6686
> Fixed: Remote path mapping UI being partially hidden on smaller screens

- src/NzbDrone.Core/Extras/Subtitles/ExistingSubtitleImporter.cs
- src/NzbDrone.Core/Extras/Subtitles/SubtitleService.cs
- src/NzbDrone.Core/Parser/LanguageParser.cs
When renaming movies with associated subtitle files that weren't directly imported by Radarr, subtitle tags like SDH, Forced, HI, would be lost. This affected setups like Bazarr or other ways of manually putting subtitle files in the movies' folder. Files imported alongside video files in automatic or manual imports weren't affected.
Tags were already getting parsed, but weren't getting passed along to the records.
* Fixes #7710
* Fixes #8275 
* Fixes #8392
> Fix tags for existing subtitle files getting lost in renaming 

- src/NzbDrone.Core/CustomFormats/CustomFormatCalculationService.cs
- src/NzbDrone.Core/MediaFiles/MovieImport/Specifications/UpgradeSpecification.cs
Fixes #8431
- Remove erroneous Year and Imdbid from ParseCustomFormat, not needed
NO
title
- [] Tests
* Fixes #XXXX
> Fixed: Upgrades blocked: UpgradeSpecification error

- src/NzbDrone.Core.Test/MediaFiles/DiskScanServiceTests/ScanFixture.cs
- src/NzbDrone.Core.Test/MediaFiles/MovieFileMovingServiceTests/MoveMovieFileFixture.cs
- src/NzbDrone.Core.Test/MovieTests/MovieFolderPathBuilderFixture.cs
- src/NzbDrone.Core.Test/MovieTests/RefreshMovieServiceFixture.cs
- src/NzbDrone.Core/RootFolders/RootFolderService.cs
- src/Radarr.Api.V3/Movies/MovieController.cs
NO
Set the root folder path for movies without destroying the db
* Closes #8456
> Fixed: RootFolderPath not set for Movies from API

- src/NzbDrone.Core/ImportLists/Radarr/RadarrAPIResource.cs
- src/NzbDrone.Core/ImportLists/Radarr/RadarrImport.cs
NO
When syncing two Radarr instances, if one or more root folders had been selected as a filter, the sync would always find 0 matches. This was caused by the import list looking for a `rootFolderPath` property in the `/movie` API request, which exists in Sonarr's API but not Radarr's. This makes the import process look for and compare a `path` property instead. 
None
> Fixed: Radarr import list not finding any matches when filtering by Root Folders

- frontend/src/Content/Images/Icons/manifest.json
NO
https://github.com/Sonarr/Sonarr/pull/5689 for Radarr. Use relative paths in the manifest instead of absolute paths.
* Fixes #8608
> Fix: Use relative paths instead of absolute paths for webmanifest

- src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
- src/NzbDrone.Core/Parser/QualityParser.cs
NO
Correctly parses P2P Blu-ray disks as well as Scene releases as BR-DISK
* Fixes
* https://github.com/Radarr/Radarr/issues/6307
* https://github.com/Radarr/Radarr/issues/3223
> Correctly parse SCENE and P2P BluRay DISKS releases

- frontend/src/index.ejs
- frontend/src/login.html
NO
Set `theme-color` to Radarr's web UI sidebar color, like Sonarr.
* Fixes #XXXX
> Set frontend `theme-color` to sidebar color

- src/NzbDrone.Core.Test/Housekeeping/Housekeepers/CleanupOrphanedImportListMoviesFixture.cs
- src/NzbDrone.Core.Test/ImportListTests/ImportListSyncServiceFixture.cs
- src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedImportListMovies.cs
- src/NzbDrone.Core/ImportLists/FetchAndParseImportListService.cs
- src/NzbDrone.Core/ImportLists/ImportListBase.cs
- src/NzbDrone.Core/ImportLists/ImportListSyncService.cs
NO
Don't clean or process results if we didn't do anything during the list sync. Also adds housekeeper for ListMovies when lists are gone (incase the event driven delete event gets missed due to restart or other app failure)
* Fixes #9011
> Fixed: Don't Clean if no lists synced

- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
NO
Fixing the release group parser not correctly recognizing `YIFY` in some releases.
> fix(parser): not correctly recognizing YIFY RlsGrp

- src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
- src/NzbDrone.Core/Parser/QualityParser.cs
NO
Correctly Parse German Scene REMUXes based on German scene rules --> https://scenerules.org/t.html?id=2016_DE_AVC.nfo
* Fixes https://github.com/Radarr/Radarr/issues/6307
* That issue wasn't really fixed
> Correctly Parse German Scene Bluray REMUXes

- src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
- src/NzbDrone.Core/Parser/Parser.cs
NO
X-bit e.g. 24-bit parsed as group
* Fixes #XXXX
> Fixed: Dont Parse 24-bit as group

- src/NzbDrone.Core.Test/IndexerTests/IndexerBaseFixture.cs
- src/NzbDrone.Core.Test/IndexerTests/TestIndexer.cs
- src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
- src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs
- src/NzbDrone.Core/Parser/LanguageParser.cs
- src/NzbDrone.Core/Parser/Parser.cs
NO
This PR consists of 3 parts (split by commit):
1. Added tests related to the `Multi` tag in releases
2. Correctly parses German DL and ML tags
The `DL` tag (Dual Language) is quite like the `Multi` tag, but for the German Scene, it specifies that the release contains the German and the original language.
The `ML` tag (Multi Language) contains the following languages: `German`, `Original`, `English` or more ([examples on xrel.to](https://www.xrel.to/p2p/releases.html?search_results=MRUJJIw4j3167540907&page=4))
3. It fixes #6474 by hardcoding some specific known movie titles that contain the word "German" so that the regex excludes these releases.
* Fixes #6474
> German DL and ML tag

- src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
- src/NzbDrone.Core/Organizer/FileNameBuilder.cs
NO
Instead of using the first frame for any video stream, read only frames associated with the primary video stream. 
* Fixes #9616 
* Fixes #9619
> Fixed: Only use frames for Primary video stream for analysis

- src/NzbDrone.Core/Notifications/NotificationBase.cs
- src/NzbDrone.Core/Notifications/Telegram/Telegram.cs
NO
Using branded title for Telegram nitification messages for more convenient determination of notification source in case of using multiple notificators in one Telegram channel or group.
* Fixes #9845
> Use branded message title for Telegram notifications

- src/NzbDrone.Core.Test/MetadataSource/SkyHook/SkyHookProxySearchFixture.cs
- src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
NO
The aim of this pull request is to add the ability to use IMDB and TMDB movie page URLs as valid search terms on the Add New Movie page.
N/A
* Fixes #10511
> New: Parse IMDB and TMDB URLs as search terms
